insert into aseguradoras (rfc, nombre) values ('CNR197962XB8', 'Wunsch and Sons');
insert into aseguradoras (rfc, nombre) values ('VFH778160XU8', 'Smitham LLC');
insert into aseguradoras (rfc, nombre) values ('GCU129000VC4', 'Connelly, Olson and Johnson');
insert into aseguradoras (rfc, nombre) values ('QFD290780EI7', 'Pouros, Murphy and Gusikowski');
insert into aseguradoras (rfc, nombre) values ('VHK268988LY1', 'Haag, Cummings and Schroeder');
insert into aseguradoras (rfc, nombre) values ('TBR676356QY6', 'Swift-Runte');
insert into aseguradoras (rfc, nombre) values ('BVG442351WV5', 'Greenholt, Weimann and Balistreri');
insert into aseguradoras (rfc, nombre) values ('MWF324952WO7', 'Schoen, Turner and Stanton');
insert into aseguradoras (rfc, nombre) values ('FYA094697QL2', 'Ankunding Inc');
insert into aseguradoras (rfc, nombre) values ('YJR177561FE3', 'Mueller LLC');
insert into aseguradoras (rfc, nombre) values ('GNH604619XT0', 'Kerluke-Emmerich');
insert into aseguradoras (rfc, nombre) values ('OIU786659OB3', 'Bernhard and Sons');
insert into aseguradoras (rfc, nombre) values ('EYL703371LQ0', 'Yundt, Purdy and Rosenbaum');
insert into aseguradoras (rfc, nombre) values ('YAG655616DT3', 'Conn-Becker');
insert into aseguradoras (rfc, nombre) values ('PLJ172144LQ8', 'Legros LLC');
insert into aseguradoras (rfc, nombre) values ('WEY990265EJ5', 'Kirlin Group');
insert into aseguradoras (rfc, nombre) values ('DBO949842QE8', 'Moore-Bartell');
insert into aseguradoras (rfc, nombre) values ('VMN108669KQ4', 'Brekke, McDermott and Lesch');
insert into aseguradoras (rfc, nombre) values ('WTE680570MJ1', 'Jacobson-Moen');
insert into aseguradoras (rfc, nombre) values ('OSR200113BT7', 'Robel and Sons');
insert into aseguradoras (rfc, nombre) values ('XAA255976SH0', 'Wisoky, Predovic and O''Reilly');
insert into aseguradoras (rfc, nombre) values ('SJH089638PE2', 'Murphy, Block and Kuhlman');
insert into aseguradoras (rfc, nombre) values ('ZUO569927IA1', 'Zulauf-Daniel');
insert into aseguradoras (rfc, nombre) values ('TJQ569444JS4', 'Abbott, Anderson and Spinka');
insert into aseguradoras (rfc, nombre) values ('BVL963197RH5', 'Feeney-Hayes');
insert into aseguradoras (rfc, nombre) values ('HCQ423439YY8', 'Schaden, Krajcik and Cremin');
insert into aseguradoras (rfc, nombre) values ('MJA996671JI3', 'Pagac, Veum and Bergstrom');
insert into aseguradoras (rfc, nombre) values ('YEE154724RU9', 'Murphy LLC');
insert into aseguradoras (rfc, nombre) values ('WMN224602XP9', 'Pfeffer, Hodkiewicz and Brown');
insert into aseguradoras (rfc, nombre) values ('CJP526370QS7', 'Raynor-Crooks');
insert into aseguradoras (rfc, nombre) values ('DGP666954KW1', 'Bahringer, Heidenreich and Medhurst');
insert into aseguradoras (rfc, nombre) values ('UDU492803DO6', 'Spinka, Ritchie and Torp');
insert into aseguradoras (rfc, nombre) values ('IMR247727PJ3', 'Rutherford, Dibbert and Kuhlman');
insert into aseguradoras (rfc, nombre) values ('IXF669200PY1', 'Wiza, Mann and Lindgren');
insert into aseguradoras (rfc, nombre) values ('PEV502855VJ2', 'Turcotte, DuBuque and Barton');
insert into aseguradoras (rfc, nombre) values ('KVV379018RR6', 'Funk LLC');
insert into aseguradoras (rfc, nombre) values ('IBQ266018BP2', 'Spencer-Spencer');
insert into aseguradoras (rfc, nombre) values ('MRA753439PW3', 'Cremin-Schmidt');
insert into aseguradoras (rfc, nombre) values ('YLA660564SX9', 'Blanda, Aufderhar and Prosacco');
insert into aseguradoras (rfc, nombre) values ('YQF827222UZ8', 'Heller, Gerlach and Hegmann');
insert into aseguradoras (rfc, nombre) values ('ZWW863688XJ2', 'Marquardt-Grant');
insert into aseguradoras (rfc, nombre) values ('ZJT250140VL3', 'Funk-Mosciski');
insert into aseguradoras (rfc, nombre) values ('JOH116354YK0', 'Waters-Walsh');
insert into aseguradoras (rfc, nombre) values ('QOM859077MU9', 'Moore-Krajcik');
insert into aseguradoras (rfc, nombre) values ('TDR629102NM3', 'Beatty-Gibson');
insert into aseguradoras (rfc, nombre) values ('IVR054537SJ1', 'Pfannerstill Group');
insert into aseguradoras (rfc, nombre) values ('EWD232810PR8', 'Rempel LLC');
insert into aseguradoras (rfc, nombre) values ('CSA272056DM1', 'Corkery, Rowe and Schamberger');
insert into aseguradoras (rfc, nombre) values ('XUZ919887LF1', 'Abbott, Fahey and Kuphal');
insert into aseguradoras (rfc, nombre) values ('PWC290176RT8', 'Rippin-Smitham');
insert into aseguradoras (rfc, nombre) values ('CSX634502MH0', 'Lubowitz-Bahringer');
insert into aseguradoras (rfc, nombre) values ('ESL104843MG2', 'Farrell Inc');
insert into aseguradoras (rfc, nombre) values ('ONU392740HF9', 'Schinner Inc');
insert into aseguradoras (rfc, nombre) values ('VKP641443CJ1', 'Harris, Weber and Morissette');
insert into aseguradoras (rfc, nombre) values ('KLH408648IE1', 'Swift Inc');
insert into aseguradoras (rfc, nombre) values ('DKO958725ME8', 'Gerlach-Ferry');
insert into aseguradoras (rfc, nombre) values ('BXO749584CS7', 'Lindgren, Reichert and Nicolas');
insert into aseguradoras (rfc, nombre) values ('TFD242013QJ6', 'MacGyver-Erdman');
insert into aseguradoras (rfc, nombre) values ('IPM524196AV9', 'Ritchie-Stark');
insert into aseguradoras (rfc, nombre) values ('YSE624814RX6', 'Medhurst Inc');
insert into aseguradoras (rfc, nombre) values ('IQM553568TF1', 'Dach and Sons');
insert into aseguradoras (rfc, nombre) values ('IXU920619IB5', 'Ullrich and Sons');
insert into aseguradoras (rfc, nombre) values ('KNZ273677PF9', 'Yost, Beer and Sauer');
insert into aseguradoras (rfc, nombre) values ('QSL068082UE8', 'Franecki, Ledner and O''Hara');
insert into aseguradoras (rfc, nombre) values ('PLQ365846EG5', 'Doyle Inc');
insert into aseguradoras (rfc, nombre) values ('EDU642018SF5', 'Stamm-Kassulke');
insert into aseguradoras (rfc, nombre) values ('WFY911425FG1', 'Waelchi LLC');
insert into aseguradoras (rfc, nombre) values ('WRE764157MZ3', 'Nicolas, Frami and Powlowski');
insert into aseguradoras (rfc, nombre) values ('HZY984932DZ0', 'Gutkowski, Bergnaum and Breitenberg');
insert into aseguradoras (rfc, nombre) values ('GTD214743KM1', 'Ullrich-Wuckert');
insert into aseguradoras (rfc, nombre) values ('DQP685544OW2', 'Krajcik Inc');
insert into aseguradoras (rfc, nombre) values ('GPB417551CS6', 'Walker and Sons');
insert into aseguradoras (rfc, nombre) values ('GVE180947TA5', 'Jerde, Hickle and King');
insert into aseguradoras (rfc, nombre) values ('EMO929756KX3', 'Stokes-Yost');
insert into aseguradoras (rfc, nombre) values ('XGR286513SL1', 'Frami-Keebler');
insert into aseguradoras (rfc, nombre) values ('PEF862896JQ0', 'Boyle-Cormier');
insert into aseguradoras (rfc, nombre) values ('FMT823778QU8', 'Schumm-O''Keefe');
insert into aseguradoras (rfc, nombre) values ('JCA079317GV2', 'Monahan, Miller and Fahey');
insert into aseguradoras (rfc, nombre) values ('VCQ247406NX0', 'Abbott-Swaniawski');
insert into aseguradoras (rfc, nombre) values ('YIX902801CA0', 'Trantow, Haag and Funk');
insert into aseguradoras (rfc, nombre) values ('HHG660979LQ3', 'Osinski, Friesen and Stracke');
insert into aseguradoras (rfc, nombre) values ('GML196834CU0', 'Blick Group');
insert into aseguradoras (rfc, nombre) values ('OWE132653XN1', 'Hahn-Lockman');
insert into aseguradoras (rfc, nombre) values ('QBB755043MD9', 'Hilll Inc');
insert into aseguradoras (rfc, nombre) values ('ZUP611344VP5', 'Durgan-O''Keefe');
insert into aseguradoras (rfc, nombre) values ('WFA461076WT1', 'Waters, Herzog and Bogisich');
insert into aseguradoras (rfc, nombre) values ('JLM870731NK1', 'Anderson-Vandervort');
insert into aseguradoras (rfc, nombre) values ('TPN261126DV3', 'Boyer Group');
insert into aseguradoras (rfc, nombre) values ('ZGM292241RT9', 'Rath-Cruickshank');
insert into aseguradoras (rfc, nombre) values ('NIY124034YE0', 'Paucek Group');
insert into aseguradoras (rfc, nombre) values ('BQH499144AM4', 'Streich LLC');
insert into aseguradoras (rfc, nombre) values ('ILP381774OJ2', 'Hand-Frami');
insert into aseguradoras (rfc, nombre) values ('JOL588750AF4', 'Bernier, Bogan and Hamill');
insert into aseguradoras (rfc, nombre) values ('TPN801122SD3', 'Stoltenberg Group');
insert into aseguradoras (rfc, nombre) values ('CJZ234625VR9', 'Kohler Inc');
insert into aseguradoras (rfc, nombre) values ('PAM146609PA6', 'Maggio, Ruecker and Weimann');
insert into aseguradoras (rfc, nombre) values ('NYE129595BZ4', 'Schiller, Champlin and Von');
insert into aseguradoras (rfc, nombre) values ('TUG227887IO9', 'Parker Group');
insert into aseguradoras (rfc, nombre) values ('TQB303865AO0', 'Morar, Kling and Wintheiser');
insert into aseguradoras (rfc, nombre) values ('UEB994499GZ5', 'Gulgowski, Wisoky and Crist');
insert into aseguradoras (rfc, nombre) values ('DTB520165NN3', 'Walker-Welch');
insert into aseguradoras (rfc, nombre) values ('IQF401540HB9', 'Huel Inc');
insert into aseguradoras (rfc, nombre) values ('CRA980087NK0', 'Green-Botsford');
insert into aseguradoras (rfc, nombre) values ('LCU069021JH7', 'Reinger Inc');
insert into aseguradoras (rfc, nombre) values ('KVF641018PI8', 'Kuphal LLC');
insert into aseguradoras (rfc, nombre) values ('MQC030832LI8', 'Feeney, Schuppe and Considine');
insert into aseguradoras (rfc, nombre) values ('UVG274201LF9', 'Beier-Prosacco');
insert into aseguradoras (rfc, nombre) values ('DRO021513XD3', 'Howell, Hirthe and Gorczany');
insert into aseguradoras (rfc, nombre) values ('PXK448807QS2', 'Aufderhar, Wuckert and Mante');
insert into aseguradoras (rfc, nombre) values ('WTL102683RP3', 'Greenholt, Brown and Wilkinson');
insert into aseguradoras (rfc, nombre) values ('QFK231013RO7', 'Witting and Sons');
insert into aseguradoras (rfc, nombre) values ('ABI801809GZ9', 'Cassin LLC');
insert into aseguradoras (rfc, nombre) values ('IUQ119581WG4', 'Cummerata, Reinger and Hermiston');
insert into aseguradoras (rfc, nombre) values ('HPV878743FX1', 'Dibbert, Daugherty and Langworth');
insert into aseguradoras (rfc, nombre) values ('XCS508275XD9', 'Morissette, Ward and Greenfelder');
insert into aseguradoras (rfc, nombre) values ('QZU243692EA3', 'Sporer LLC');
insert into aseguradoras (rfc, nombre) values ('NGA594441OM6', 'Harber, Bogan and Kovacek');
insert into aseguradoras (rfc, nombre) values ('SYA809859CZ6', 'Doyle, Gerlach and Heidenreich');
insert into aseguradoras (rfc, nombre) values ('IOX680281PG3', 'Wisoky-Lakin');
insert into aseguradoras (rfc, nombre) values ('QWL966310PK6', 'Mitchell-Hagenes');
insert into aseguradoras (rfc, nombre) values ('QJN954670FX0', 'Huel, Senger and Ortiz');
insert into aseguradoras (rfc, nombre) values ('VWE071931ZA9', 'Reichert-Emard');
insert into aseguradoras (rfc, nombre) values ('UJN604543CB0', 'Considine Inc');
insert into aseguradoras (rfc, nombre) values ('GJV177515ZL9', 'Price LLC');
insert into aseguradoras (rfc, nombre) values ('QZL968541GL4', 'Haley Inc');
insert into aseguradoras (rfc, nombre) values ('OCU040507OC1', 'Powlowski-Cremin');
insert into aseguradoras (rfc, nombre) values ('OWC289515KE0', 'Kunze Group');
insert into aseguradoras (rfc, nombre) values ('ZKV053083ED6', 'Cronin-Cassin');
insert into aseguradoras (rfc, nombre) values ('KNH370123WJ7', 'Douglas, Cormier and Goyette');
insert into aseguradoras (rfc, nombre) values ('WHN312425PD0', 'Kertzmann LLC');
insert into aseguradoras (rfc, nombre) values ('ITU281812GW1', 'Toy-Wilkinson');
insert into aseguradoras (rfc, nombre) values ('IVE572787HL0', 'Labadie LLC');
insert into aseguradoras (rfc, nombre) values ('YMR723834TF9', 'Schiller Inc');
insert into aseguradoras (rfc, nombre) values ('ZOK703856IN0', 'Hilpert, MacGyver and Hackett');
insert into aseguradoras (rfc, nombre) values ('AXH654218NT9', 'Daugherty-Klein');
insert into aseguradoras (rfc, nombre) values ('KUR894138ZD8', 'Walsh Group');
insert into aseguradoras (rfc, nombre) values ('JTV257468YE4', 'Abernathy and Sons');
insert into aseguradoras (rfc, nombre) values ('NBY017608VZ9', 'Ebert-Ledner');
insert into aseguradoras (rfc, nombre) values ('HNL874887ZR3', 'Hansen and Sons');
insert into aseguradoras (rfc, nombre) values ('TWK888270DC8', 'Mayer and Sons');
insert into aseguradoras (rfc, nombre) values ('FWI326925GZ0', 'Koelpin-Wilkinson');
insert into aseguradoras (rfc, nombre) values ('LPJ875381TS1', 'Witting-Nitzsche');
insert into aseguradoras (rfc, nombre) values ('MZD366331KI6', 'Schiller Inc');
insert into aseguradoras (rfc, nombre) values ('BDQ169148WT7', 'Blick and Sons');
insert into aseguradoras (rfc, nombre) values ('XCP842072UG7', 'Maggio-Maggio');
insert into aseguradoras (rfc, nombre) values ('AWO615265PP0', 'Kunze-Marquardt');
insert into aseguradoras (rfc, nombre) values ('SJO099443XD8', 'Raynor Group');
insert into aseguradoras (rfc, nombre) values ('KSU366584YS1', 'Treutel LLC');
insert into aseguradoras (rfc, nombre) values ('PXM757827LY0', 'Grimes and Sons');
insert into aseguradoras (rfc, nombre) values ('QLN646382VP2', 'Reilly Group');
insert into aseguradoras (rfc, nombre) values ('FYY037716IS7', 'Douglas-Gislason');
insert into aseguradoras (rfc, nombre) values ('NPX942336PJ1', 'Hauck LLC');
insert into aseguradoras (rfc, nombre) values ('EMM857918NH1', 'Prohaska Inc');
insert into aseguradoras (rfc, nombre) values ('FXW087682XA6', 'Cronin LLC');
insert into aseguradoras (rfc, nombre) values ('IQM356472GQ6', 'Armstrong-Kutch');
insert into aseguradoras (rfc, nombre) values ('CVM436798LA5', 'Adams Group');
insert into aseguradoras (rfc, nombre) values ('ZSG001311EO7', 'Oberbrunner, Moore and Heathcote');
insert into aseguradoras (rfc, nombre) values ('KQG003867YL9', 'Veum, Dietrich and Altenwerth');
insert into aseguradoras (rfc, nombre) values ('AXJ422613TO8', 'Blanda-Strosin');
insert into aseguradoras (rfc, nombre) values ('FZP955462NE5', 'Gottlieb-Brown');
insert into aseguradoras (rfc, nombre) values ('PJD568154UD5', 'Willms, Fahey and Kirlin');
insert into aseguradoras (rfc, nombre) values ('YDI839536OH4', 'Miller Inc');
insert into aseguradoras (rfc, nombre) values ('ZHH408364US9', 'Pagac-Bruen');
insert into aseguradoras (rfc, nombre) values ('DSX803906KD9', 'Crona-Upton');
insert into aseguradoras (rfc, nombre) values ('KYF977986UD2', 'Crist-Bins');
insert into aseguradoras (rfc, nombre) values ('JLT473736RZ5', 'Rath, Bayer and Rutherford');
insert into aseguradoras (rfc, nombre) values ('NQS987535XK0', 'Kilback, Keeling and Collins');
insert into aseguradoras (rfc, nombre) values ('IEM400163CQ9', 'Ondricka Inc');
insert into aseguradoras (rfc, nombre) values ('XJG513803PG7', 'Wisozk, Abbott and Glover');
insert into aseguradoras (rfc, nombre) values ('MCN576460TG8', 'Kassulke Inc');
insert into aseguradoras (rfc, nombre) values ('WNX544989KN1', 'Brakus-Runolfsson');
insert into aseguradoras (rfc, nombre) values ('TDA578591DA8', 'Kiehn-Denesik');
insert into aseguradoras (rfc, nombre) values ('OKK671416DQ8', 'O''Reilly-Dach');
insert into aseguradoras (rfc, nombre) values ('MLB541871LM0', 'Willms Group');
insert into aseguradoras (rfc, nombre) values ('ASG742706AV3', 'Schumm-Mraz');
insert into aseguradoras (rfc, nombre) values ('MJI478671RO7', 'Hagenes, Schuster and Willms');
insert into aseguradoras (rfc, nombre) values ('ETL856138GP3', 'Kuhn-Howell');
insert into aseguradoras (rfc, nombre) values ('RXT727586KR5', 'Botsford, Volkman and Wolff');
insert into aseguradoras (rfc, nombre) values ('IUV284944YC6', 'Sipes LLC');
insert into aseguradoras (rfc, nombre) values ('KQA137145NM3', 'Lehner-Effertz');
insert into aseguradoras (rfc, nombre) values ('HXW786661FI5', 'Flatley and Sons');
insert into aseguradoras (rfc, nombre) values ('ZOU741736HA9', 'Hane, Hegmann and Kassulke');
insert into aseguradoras (rfc, nombre) values ('HFG679882WR9', 'McKenzie, Block and Heathcote');
insert into aseguradoras (rfc, nombre) values ('ITE753921RH8', 'Ullrich, Baumbach and Heathcote');
insert into aseguradoras (rfc, nombre) values ('SPS589331SQ3', 'Kunde Inc');
insert into aseguradoras (rfc, nombre) values ('VTT189680AS7', 'Connelly Inc');
insert into aseguradoras (rfc, nombre) values ('UUH331200IV4', 'Lockman, Kihn and Dooley');
insert into aseguradoras (rfc, nombre) values ('PJK488598HN4', 'Parisian, Mills and Rempel');
insert into aseguradoras (rfc, nombre) values ('EES117398HS4', 'Weimann-Simonis');
insert into aseguradoras (rfc, nombre) values ('NME661403KL9', 'Abbott Inc');
insert into aseguradoras (rfc, nombre) values ('SZS967254LB9', 'Gulgowski and Sons');
insert into aseguradoras (rfc, nombre) values ('NNQ776012LU7', 'Harber-Volkman');
insert into aseguradoras (rfc, nombre) values ('CVL784867RE8', 'Emard-Cassin');
insert into aseguradoras (rfc, nombre) values ('KJW018565RS5', 'Yost, Vandervort and Hahn');
insert into aseguradoras (rfc, nombre) values ('KHM090411QV5', 'Hahn and Sons');
insert into aseguradoras (rfc, nombre) values ('OVR917043CB6', 'Conn, Bosco and Herman');
insert into aseguradoras (rfc, nombre) values ('OJC993442PE5', 'Kulas, Thiel and Hyatt');
insert into aseguradoras (rfc, nombre) values ('SWV383632RE5', 'Corwin-Harris');
insert into aseguradoras (rfc, nombre) values ('QNW012977BX0', 'Brown Group');
insert into aseguradoras (rfc, nombre) values ('HBP016535YC4', 'Halvorson Inc');
