insert into aseguradoras (rfc, nombre) values ('BUU0331002F4', 'Kilback, Renner and Nolan');
insert into aseguradoras (rfc, nombre) values ('TRJ5167154B9', 'Hilll-Koch');
insert into aseguradoras (rfc, nombre) values ('PKI0996391Z9', 'Daniel, Luettgen and Senger');
insert into aseguradoras (rfc, nombre) values ('TLG0432523M9', 'Braun Inc');
insert into aseguradoras (rfc, nombre) values ('JMD5437984D6', 'Mueller Group');
insert into aseguradoras (rfc, nombre) values ('YSS7601898H7', 'Johns Inc');
insert into aseguradoras (rfc, nombre) values ('NSP8658888C9', 'Weber, Rippin and Ryan');
insert into aseguradoras (rfc, nombre) values ('FPP5986014N2', 'Wyman, Gleichner and Rutherford');
insert into aseguradoras (rfc, nombre) values ('UPG0983958Q6', 'Johnston, Goyette and Lowe');
insert into aseguradoras (rfc, nombre) values ('NZV6470690R3', 'Kirlin LLC');
insert into aseguradoras (rfc, nombre) values ('MQC9090107G2', 'Jones LLC');
insert into aseguradoras (rfc, nombre) values ('PDF6983635B6', 'Ward, Feest and Ruecker');
insert into aseguradoras (rfc, nombre) values ('QIQ0425973X3', 'Christiansen-Zboncak');
insert into aseguradoras (rfc, nombre) values ('LNW0543102W1', 'Dibbert and Sons');
insert into aseguradoras (rfc, nombre) values ('STK0012994O0', 'Larkin and Sons');
insert into aseguradoras (rfc, nombre) values ('MRO0785255F4', 'Gleichner and Sons');
insert into aseguradoras (rfc, nombre) values ('GQX0066365V4', 'Littel, Halvorson and Glover');
insert into aseguradoras (rfc, nombre) values ('XJP2024497P0', 'Corwin-Mertz');
insert into aseguradoras (rfc, nombre) values ('PWH4023715K6', 'Goldner, Kutch and Gerlach');
insert into aseguradoras (rfc, nombre) values ('QGG8370499O2', 'Schinner-Schaefer');
insert into aseguradoras (rfc, nombre) values ('WFQ1014408N8', 'Champlin, Rosenbaum and Lowe');
insert into aseguradoras (rfc, nombre) values ('MOW6536929X7', 'Welch Group');
insert into aseguradoras (rfc, nombre) values ('UXE2516355R8', 'Gerlach Group');
insert into aseguradoras (rfc, nombre) values ('OMP4345510P4', 'Stehr and Sons');
insert into aseguradoras (rfc, nombre) values ('MRV2403860H8', 'Tillman-Deckow');
insert into aseguradoras (rfc, nombre) values ('USH5466257G7', 'Beatty, Funk and Thompson');
insert into aseguradoras (rfc, nombre) values ('RWM1728057K1', 'Predovic, Halvorson and Padberg');
insert into aseguradoras (rfc, nombre) values ('MJY2828451C3', 'Wunsch-Blick');
insert into aseguradoras (rfc, nombre) values ('KCX1452458C7', 'Torphy-Willms');
insert into aseguradoras (rfc, nombre) values ('JKV1524857C2', 'Moen Inc');
insert into aseguradoras (rfc, nombre) values ('LTU9658715E6', 'Swift, Sauer and Hermiston');
insert into aseguradoras (rfc, nombre) values ('XFT0416417F7', 'Gleason-Fay');
insert into aseguradoras (rfc, nombre) values ('OFJ7932135L9', 'Schowalter and Sons');
insert into aseguradoras (rfc, nombre) values ('BWM3877838H4', 'Wiza-Bashirian');
insert into aseguradoras (rfc, nombre) values ('CAJ7598668N2', 'Emmerich, Kihn and Erdman');
insert into aseguradoras (rfc, nombre) values ('DYP5812351O9', 'Will, Nicolas and Hand');
insert into aseguradoras (rfc, nombre) values ('GYY4742919J6', 'Pouros LLC');
insert into aseguradoras (rfc, nombre) values ('NVH4877001A9', 'Bednar, Steuber and Kuvalis');
insert into aseguradoras (rfc, nombre) values ('MIX6500334Z9', 'Howell-Heller');
insert into aseguradoras (rfc, nombre) values ('VCL0717919G6', 'Ondricka, Bayer and Zboncak');
insert into aseguradoras (rfc, nombre) values ('DKY2768858Y8', 'Rath and Sons');
insert into aseguradoras (rfc, nombre) values ('GOO3678952U3', 'Lehner, O''Hara and Walker');
insert into aseguradoras (rfc, nombre) values ('BTH6805847C5', 'Steuber LLC');
insert into aseguradoras (rfc, nombre) values ('VTC0166258C8', 'Olson, Bauch and Botsford');
insert into aseguradoras (rfc, nombre) values ('FEJ0451653N5', 'Bogisich-Steuber');
insert into aseguradoras (rfc, nombre) values ('YWX4603036K5', 'Boyer, Predovic and Gleichner');
insert into aseguradoras (rfc, nombre) values ('YXP5773770X2', 'Davis, Kovacek and Bechtelar');
insert into aseguradoras (rfc, nombre) values ('LSL1794627C7', 'Jakubowski, Pouros and Hilll');
insert into aseguradoras (rfc, nombre) values ('VZT7647877K3', 'Schulist, Bauch and Kuhic');
insert into aseguradoras (rfc, nombre) values ('FAK8483612Q2', 'Heaney-Weber');
insert into aseguradoras (rfc, nombre) values ('WMQ7465873T8', 'Kunde-Heidenreich');
insert into aseguradoras (rfc, nombre) values ('EIW7043298X0', 'Reichert Group');
insert into aseguradoras (rfc, nombre) values ('JJN2712177K1', 'Fahey, Ankunding and West');
insert into aseguradoras (rfc, nombre) values ('ZIE7140897W8', 'Harris-Kuphal');
insert into aseguradoras (rfc, nombre) values ('TUW8388207D5', 'Bogisich Group');
insert into aseguradoras (rfc, nombre) values ('HXN0303797V2', 'Prosacco-Parisian');
insert into aseguradoras (rfc, nombre) values ('USI1640988E7', 'Ullrich Inc');
insert into aseguradoras (rfc, nombre) values ('HSG7569069X9', 'Bruen-Quigley');
insert into aseguradoras (rfc, nombre) values ('SGI3281133W3', 'Beahan, Bogan and Robel');
insert into aseguradoras (rfc, nombre) values ('RWJ0159289Y7', 'Hammes-Reilly');
insert into aseguradoras (rfc, nombre) values ('MET3995236L9', 'Grimes Group');
insert into aseguradoras (rfc, nombre) values ('GEJ1854295Q4', 'Abshire and Sons');
insert into aseguradoras (rfc, nombre) values ('AGH1077223U1', 'Terry, Beier and Tremblay');
insert into aseguradoras (rfc, nombre) values ('RYU3368135C1', 'Rutherford, Wilkinson and Bauch');
insert into aseguradoras (rfc, nombre) values ('KJG8315151E7', 'Frami, Wuckert and Murray');
insert into aseguradoras (rfc, nombre) values ('DLP4916661F1', 'Shanahan-Cormier');
insert into aseguradoras (rfc, nombre) values ('HPT5989428D5', 'Kunde, Crooks and Reynolds');
insert into aseguradoras (rfc, nombre) values ('PAH3958715W1', 'Abbott, Stokes and Ondricka');
insert into aseguradoras (rfc, nombre) values ('ECX8827186Y5', 'Bogisich and Sons');
insert into aseguradoras (rfc, nombre) values ('WEY6324827T6', 'O''Connell, Daniel and Harber');
insert into aseguradoras (rfc, nombre) values ('PUL3346815I9', 'Cummerata LLC');
insert into aseguradoras (rfc, nombre) values ('AUU9037988A7', 'Littel Inc');
insert into aseguradoras (rfc, nombre) values ('UGY2744200Y4', 'Luettgen-Metz');
insert into aseguradoras (rfc, nombre) values ('OYU3006062X3', 'Bradtke Group');
insert into aseguradoras (rfc, nombre) values ('EMW5045085C4', 'Ortiz-Olson');
insert into aseguradoras (rfc, nombre) values ('VVA7300263V4', 'Hauck-Johns');
insert into aseguradoras (rfc, nombre) values ('IGG8764322V1', 'Leannon-Sanford');
insert into aseguradoras (rfc, nombre) values ('RNA7337250L2', 'Abbott-Ratke');
insert into aseguradoras (rfc, nombre) values ('KRZ6120354Z7', 'Jerde and Sons');
insert into aseguradoras (rfc, nombre) values ('AEV1847520V0', 'Bauch-Bartoletti');
insert into aseguradoras (rfc, nombre) values ('URQ0719212J7', 'Ullrich Inc');
insert into aseguradoras (rfc, nombre) values ('LHI6112193R2', 'Paucek Group');
insert into aseguradoras (rfc, nombre) values ('TAG1043293L6', 'Bahringer, Rolfson and White');
insert into aseguradoras (rfc, nombre) values ('BPT0500646B0', 'Morar and Sons');
insert into aseguradoras (rfc, nombre) values ('LPY7403876A8', 'Purdy, Hettinger and Hintz');
insert into aseguradoras (rfc, nombre) values ('FIX4997251N7', 'Rosenbaum, Kunze and Langworth');
insert into aseguradoras (rfc, nombre) values ('CEI7620251X3', 'Schoen-Ortiz');
insert into aseguradoras (rfc, nombre) values ('KAN0374833J2', 'King and Sons');
insert into aseguradoras (rfc, nombre) values ('YGE4863428Z6', 'Corkery, Hauck and Ratke');
insert into aseguradoras (rfc, nombre) values ('IRS8106607E6', 'Flatley-Lesch');
insert into aseguradoras (rfc, nombre) values ('NPX7488485I9', 'Glover-Tillman');
insert into aseguradoras (rfc, nombre) values ('YQJ4044134S6', 'Dicki, Metz and Lynch');
insert into aseguradoras (rfc, nombre) values ('ODZ0757779Y4', 'Wolf Group');
insert into aseguradoras (rfc, nombre) values ('WPS0253455B4', 'Altenwerth-Bednar');
insert into aseguradoras (rfc, nombre) values ('JRX6660943W9', 'Kemmer-Olson');
insert into aseguradoras (rfc, nombre) values ('BEA3345987T3', 'Renner, Mitchell and Koch');
insert into aseguradoras (rfc, nombre) values ('GAI9257498O7', 'Johnson, Goodwin and Walsh');
insert into aseguradoras (rfc, nombre) values ('VDD6236277L7', 'Bruen Group');
insert into aseguradoras (rfc, nombre) values ('JLF0876624I2', 'Gusikowski, Bernier and Mitchell');
insert into aseguradoras (rfc, nombre) values ('YYA4757352J3', 'Abshire LLC');
insert into aseguradoras (rfc, nombre) values ('GKD4364547Z5', 'Keeling-Auer');
insert into aseguradoras (rfc, nombre) values ('HKC3908093F7', 'Ebert LLC');
insert into aseguradoras (rfc, nombre) values ('FDA7716493Q1', 'Lindgren-Mayer');
insert into aseguradoras (rfc, nombre) values ('CLA3652430R5', 'Lubowitz and Sons');
insert into aseguradoras (rfc, nombre) values ('ETM9288287Q2', 'Grant Inc');
insert into aseguradoras (rfc, nombre) values ('MDM4663081Q5', 'Toy, Sawayn and Marks');
insert into aseguradoras (rfc, nombre) values ('VKA0730289T2', 'Rippin-Abbott');
insert into aseguradoras (rfc, nombre) values ('KBX1688763A0', 'Hauck, Ratke and Tillman');
insert into aseguradoras (rfc, nombre) values ('KLW4758879E7', 'Windler, Schmitt and Purdy');
insert into aseguradoras (rfc, nombre) values ('JVQ2832051J9', 'Casper and Sons');
insert into aseguradoras (rfc, nombre) values ('WKV7170964Y6', 'O''Connell LLC');
insert into aseguradoras (rfc, nombre) values ('IIS5530306T5', 'Steuber-Hessel');
insert into aseguradoras (rfc, nombre) values ('VLO4873761C6', 'O''Conner-Raynor');
insert into aseguradoras (rfc, nombre) values ('VWG6655185V6', 'Purdy LLC');
insert into aseguradoras (rfc, nombre) values ('BTL0068507P5', 'Harber Group');
insert into aseguradoras (rfc, nombre) values ('RCD4007499Q0', 'Hilll, Kassulke and Abernathy');
insert into aseguradoras (rfc, nombre) values ('ZIM0086452L2', 'Hane and Sons');
insert into aseguradoras (rfc, nombre) values ('QCE5160974V9', 'McGlynn, Wolf and Kirlin');
insert into aseguradoras (rfc, nombre) values ('OJZ8669147A1', 'Prosacco, Hauck and Reynolds');
insert into aseguradoras (rfc, nombre) values ('ZMP2069710K9', 'Bradtke-Marquardt');
insert into aseguradoras (rfc, nombre) values ('VJO6853808I7', 'Wiza, Carter and Padberg');
insert into aseguradoras (rfc, nombre) values ('OZZ9037116I0', 'Rohan LLC');
insert into aseguradoras (rfc, nombre) values ('CLV1666194M6', 'Johns Group');
insert into aseguradoras (rfc, nombre) values ('YXE1341787E4', 'Dicki, Gaylord and Corwin');
insert into aseguradoras (rfc, nombre) values ('UEN7186319F9', 'Vandervort-Casper');
insert into aseguradoras (rfc, nombre) values ('XYV0893039M1', 'Farrell Group');
insert into aseguradoras (rfc, nombre) values ('PHB5603956Z0', 'Crist, Hoppe and Walter');
insert into aseguradoras (rfc, nombre) values ('ZCB1548939O5', 'Leffler Inc');
insert into aseguradoras (rfc, nombre) values ('UBR4126548J1', 'Mills LLC');
insert into aseguradoras (rfc, nombre) values ('JJQ2881143B4', 'Stokes Inc');
insert into aseguradoras (rfc, nombre) values ('YNB4692678X1', 'Littel LLC');
insert into aseguradoras (rfc, nombre) values ('MNK8971847A9', 'Boehm-Boyer');
insert into aseguradoras (rfc, nombre) values ('YIB6040719K0', 'Dach, Turcotte and Walsh');
insert into aseguradoras (rfc, nombre) values ('VMY0200195Y8', 'Greenfelder, Haley and Bins');
insert into aseguradoras (rfc, nombre) values ('YQA9367208N6', 'Beer-O''Conner');
insert into aseguradoras (rfc, nombre) values ('GWG3354329Q2', 'Walter-Deckow');
insert into aseguradoras (rfc, nombre) values ('FBB9543061C4', 'Harris Inc');
insert into aseguradoras (rfc, nombre) values ('TKF3675863P8', 'Bergstrom, Lueilwitz and Ortiz');
insert into aseguradoras (rfc, nombre) values ('JUV0620889B0', 'Emard and Sons');
insert into aseguradoras (rfc, nombre) values ('BWW6314670J0', 'Ziemann Inc');
insert into aseguradoras (rfc, nombre) values ('YBV8516989C1', 'Koss-Moen');
insert into aseguradoras (rfc, nombre) values ('LZW6729100B0', 'Bayer, Renner and Prohaska');
insert into aseguradoras (rfc, nombre) values ('ZYD0146917H5', 'Bradtke, Treutel and Hackett');
insert into aseguradoras (rfc, nombre) values ('XCU3107781E8', 'Hagenes LLC');
insert into aseguradoras (rfc, nombre) values ('UYM6877431X1', 'Wilkinson, Kautzer and Shields');
insert into aseguradoras (rfc, nombre) values ('ZPY0229458S0', 'Pollich Inc');
insert into aseguradoras (rfc, nombre) values ('QAW2360244Y0', 'Hodkiewicz Inc');
insert into aseguradoras (rfc, nombre) values ('GIX7527747K1', 'Leannon-Pagac');
insert into aseguradoras (rfc, nombre) values ('NKK6098997R7', 'Ortiz-Gerhold');
insert into aseguradoras (rfc, nombre) values ('NJR7358373T9', 'Will Inc');
insert into aseguradoras (rfc, nombre) values ('VDQ9578074J1', 'Smitham-Barton');
insert into aseguradoras (rfc, nombre) values ('LKS8287995L6', 'Bailey-Wehner');
insert into aseguradoras (rfc, nombre) values ('DZD8868895U1', 'Stiedemann LLC');
insert into aseguradoras (rfc, nombre) values ('DIS5194198X6', 'Pollich, Hackett and VonRueden');
insert into aseguradoras (rfc, nombre) values ('XEF8056694E6', 'Nader LLC');
insert into aseguradoras (rfc, nombre) values ('GXJ6300177I7', 'Kautzer-McCullough');
insert into aseguradoras (rfc, nombre) values ('FWP4684092K5', 'Turner-Cole');
insert into aseguradoras (rfc, nombre) values ('VOJ6132015L8', 'Quitzon-Littel');
insert into aseguradoras (rfc, nombre) values ('VIL5768045R4', 'Sauer-Heller');
insert into aseguradoras (rfc, nombre) values ('ACV5520249C4', 'Mayer, Reichert and Hayes');
insert into aseguradoras (rfc, nombre) values ('JGS3537400M6', 'Jerde, Wintheiser and Bins');
insert into aseguradoras (rfc, nombre) values ('NDS9278705W7', 'Waters, Kuhn and Lubowitz');
insert into aseguradoras (rfc, nombre) values ('BEE1524962R4', 'Denesik, Becker and Senger');
insert into aseguradoras (rfc, nombre) values ('JLC2067193N8', 'Roob Inc');
insert into aseguradoras (rfc, nombre) values ('VWH5179187N9', 'Howell, Senger and Murazik');
insert into aseguradoras (rfc, nombre) values ('PTY7953903T9', 'Prosacco-O''Connell');
insert into aseguradoras (rfc, nombre) values ('KSJ8505357H5', 'Collier Group');
insert into aseguradoras (rfc, nombre) values ('DSX9588388D5', 'Lowe, Hilpert and Harris');
insert into aseguradoras (rfc, nombre) values ('MHP0642429I5', 'Mertz LLC');
insert into aseguradoras (rfc, nombre) values ('QGQ6199132N4', 'Watsica Inc');
insert into aseguradoras (rfc, nombre) values ('JPA1376463T3', 'Koepp-Denesik');
insert into aseguradoras (rfc, nombre) values ('PWI5739775B5', 'Harris-Jerde');
insert into aseguradoras (rfc, nombre) values ('AZA2763080V1', 'Okuneva-Emard');
insert into aseguradoras (rfc, nombre) values ('NSP4276344P5', 'Dickinson, Lehner and Langosh');
insert into aseguradoras (rfc, nombre) values ('AFT8990792N8', 'Simonis Inc');
insert into aseguradoras (rfc, nombre) values ('MNA5175377S4', 'Wiza-Harris');
insert into aseguradoras (rfc, nombre) values ('ECZ4056034K0', 'Little Group');
insert into aseguradoras (rfc, nombre) values ('OSV5826034N3', 'Goodwin Inc');
insert into aseguradoras (rfc, nombre) values ('NCA0939396R0', 'Gorczany, Rohan and Greenfelder');
insert into aseguradoras (rfc, nombre) values ('AQX2699493F5', 'Williamson-Abernathy');
insert into aseguradoras (rfc, nombre) values ('BXI8282235F9', 'O''Hara-Lehner');
insert into aseguradoras (rfc, nombre) values ('OBW8126457J9', 'Hartmann-Kassulke');
insert into aseguradoras (rfc, nombre) values ('FAF6870014U4', 'Nikolaus and Sons');
insert into aseguradoras (rfc, nombre) values ('FEG8082693O7', 'Morissette, Greenholt and Grady');
insert into aseguradoras (rfc, nombre) values ('KRY3242705J3', 'Barton-Klein');
insert into aseguradoras (rfc, nombre) values ('XVU4809384G9', 'Wilkinson-Langosh');
insert into aseguradoras (rfc, nombre) values ('QOY1999507K3', 'Schiller LLC');
insert into aseguradoras (rfc, nombre) values ('XIK4875414D6', 'Stoltenberg-Krajcik');
insert into aseguradoras (rfc, nombre) values ('CYH2612586C6', 'Nicolas-Herman');
insert into aseguradoras (rfc, nombre) values ('ZES8570717P5', 'Connelly-Torp');
insert into aseguradoras (rfc, nombre) values ('GNQ4436627N6', 'Grimes, Marks and Flatley');
insert into aseguradoras (rfc, nombre) values ('TVM0827064T4', 'Robel, Bauch and Shields');
insert into aseguradoras (rfc, nombre) values ('LEH6489788U9', 'Krajcik, Ullrich and Yost');
insert into aseguradoras (rfc, nombre) values ('TTD7304664U0', 'Kuvalis, Huels and Ondricka');
insert into aseguradoras (rfc, nombre) values ('HLA9462287P9', 'Corkery-Kessler');
insert into aseguradoras (rfc, nombre) values ('BJR2979734V2', 'Paucek-Lebsack');
insert into aseguradoras (rfc, nombre) values ('LCU0608877H1', 'Abernathy-Cruickshank');
insert into aseguradoras (rfc, nombre) values ('QPL0651112W5', 'Braun-Orn');
insert into aseguradoras (rfc, nombre) values ('FAD9748433J6', 'Hirthe-King');
insert into aseguradoras (rfc, nombre) values ('UHC1686076B6', 'Durgan, Davis and Lakin');
