insert into aseguradoras (rfc, nombre) values ('OIU786659OB3', 'Bernhard and Sons');
insert into aseguradoras (rfc, nombre) values ('EYL703371LQ0', 'Yundt, Purdy and Rosenbaum');
insert into aseguradoras (rfc, nombre) values ('YAG655616DT3', 'Conn-Becker');
insert into aseguradoras (rfc, nombre) values ('PLJ172144LQ8', 'Legros LLC');
insert into aseguradoras (rfc, nombre) values ('WEY990265EJ5', 'Kirlin Group');
insert into aseguradoras (rfc, nombre) values ('DBO949842QE8', 'Moore-Bartell');
insert into aseguradoras (rfc, nombre) values ('VMN108669KQ4', 'Brekke, McDermott and Lesch');
insert into aseguradoras (rfc, nombre) values ('WTE680570MJ1', 'Jacobson-Moen');
insert into aseguradoras (rfc, nombre) values ('OSR200113BT7', 'Robel and Sons');
insert into aseguradoras (rfc, nombre) values ('XAA255976SH0', 'Wisoky, Predovic and O''Reilly');
insert into aseguradoras (rfc, nombre) values ('SJH089638PE2', 'Murphy, Block and Kuhlman');
insert into aseguradoras (rfc, nombre) values ('ZUO569927IA1', 'Zulauf-Daniel');
insert into aseguradoras (rfc, nombre) values ('TJQ569444JS4', 'Abbott, Anderson and Spinka');
insert into aseguradoras (rfc, nombre) values ('BVL963197RH5', 'Feeney-Hayes');
insert into aseguradoras (rfc, nombre) values ('HCQ423439YY8', 'Schaden, Krajcik and Cremin');
insert into aseguradoras (rfc, nombre) values ('MJA996671JI3', 'Pagac, Veum and Bergstrom');
insert into aseguradoras (rfc, nombre) values ('YEE154724RU9', 'Murphy LLC');
insert into aseguradoras (rfc, nombre) values ('WMN224602XP9', 'Pfeffer, Hodkiewicz and Brown');
insert into aseguradoras (rfc, nombre) values ('CJP526370QS7', 'Raynor-Crooks');
insert into aseguradoras (rfc, nombre) values ('DGP666954KW1', 'Bahringer, Heidenreich and Medhurst');
insert into aseguradoras (rfc, nombre) values ('UDU492803DO6', 'Spinka, Ritchie and Torp');
insert into aseguradoras (rfc, nombre) values ('IMR247727PJ3', 'Rutherford, Dibbert and Kuhlman');
insert into aseguradoras (rfc, nombre) values ('IXF669200PY1', 'Wiza, Mann and Lindgren');
insert into aseguradoras (rfc, nombre) values ('PEV502855VJ2', 'Turcotte, DuBuque and Barton');
insert into aseguradoras (rfc, nombre) values ('KVV379018RR6', 'Funk LLC');
insert into aseguradoras (rfc, nombre) values ('IBQ266018BP2', 'Spencer-Spencer');
insert into aseguradoras (rfc, nombre) values ('MRA753439PW3', 'Cremin-Schmidt');
insert into aseguradoras (rfc, nombre) values ('YLA660564SX9', 'Blanda, Aufderhar and Prosacco');
insert into aseguradoras (rfc, nombre) values ('YQF827222UZ8', 'Heller, Gerlach and Hegmann');
insert into aseguradoras (rfc, nombre) values ('ZWW863688XJ2', 'Marquardt-Grant');

