insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('JM6710', '64661', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FD9539', '97356', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('AM6700', '34097', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RZ0345', '28948', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('HB0206', '69396', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WB5715', '61847', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('GN5671', '02444', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('KI5412', '82176', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WQ3620', '22556', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('GI7349', '66230', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OY1564', '35862', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UP3214', '74078', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TP1151', '11257', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UY5276', '83186', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LE4752', '96008', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OU4142', '32547', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YN6053', '57877', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('HI4135', '26321', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BP5905', '70231', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ET7503', '79103', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TN8413', '10727', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IF1497', '47674', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('EG1945', '70347', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('HE0650', '53626', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QL3980', '17424', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('DV1982', '84795', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FM3582', '81688', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IJ8159', '32003', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('DJ7311', '99117', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MA6579', '72489', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OA1193', '11253', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IY5666', '45685', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MC0666', '61335', 'Trabajo Social');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LL8491', '22475', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('GQ6489', '78093', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TQ6260', '51792', 'Psicologia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MQ0790', '14062', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BH6222', '93981', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZK6469', '10748', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BT2844', '93069', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IY3866', '37704', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('JV0309', '45511', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RV6738', '56418', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QH2781', '53159', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FD8118', '76797', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MB6146', '02770', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UG0875', '85262', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('JM7982', '11984', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TP5401', '13448', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BA1414', '75638', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FM9072', '19781', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WZ8474', '85381', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('JI0587', '35945', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('CI4526', '11246', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('GV9151', '30262', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('NE7026', '53597', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OO6633', '58573', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TC2387', '07362', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BR6719', '31954', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('XA7790', '36987', 'Arquitectura');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WW0068', '28341', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TS2892', '79039', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('NU6100', '31166', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('SX8661', '45865', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('XV5162', '88448', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TA6361', '11710', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('DT6703', '53108', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('AH5936', '15128', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RH9584', '29894', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IK6555', '31715', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BD7245', '27703', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WK5285', '94577', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('SF8049', '03302', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TX4738', '21655', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('SP5151', '60913', 'Trabajo Social');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MX7742', '58176', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UV5988', '25243', 'Medicina');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LZ5168', '89187', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZY5211', '90277', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LH9099', '65683', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FR9051', '33971', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZO5757', '67561', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BY6510', '05074', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UY9235', '08904', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('KH4509', '35170', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('VZ8275', '86660', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('DW3534', '82713', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('HC3690', '26098', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OS6242', '09932', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LE3285', '23470', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('XA6490', '62430', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OZ7199', '56953', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('AN1866', '92688', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IC9902', '15442', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RH0595', '38510', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YT8310', '51949', 'Ingenieria');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('CI2141', '93295', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TE5872', '47456', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WF8437', '45453', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('KQ6829', '90142', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('NX8438', '64607', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UE8128', '70619', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FJ7559', '32700', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RY4005', '33556', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YW5311', '96691', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('DE4914', '51524', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IJ6530', '12061', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YM9616', '44694', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZF1969', '09937', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LF2220', '74212', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UH1822', '35762', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('HF3806', '35073', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('KE2135', '48855', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('KR4505', '86988', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZU4398', '99490', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('EJ7141', '29196', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('EI5713', '19918', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FD3879', '22090', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('KW8858', '01569', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('NX0829', '58842', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('GP5976', '97594', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TC2926', '53121', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WP1495', '68124', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UG3233', '72933', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LK3511', '39084', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BS7247', '35348', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('VX5794', '89138', 'Trabajo Social');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZJ0897', '08547', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('JA0175', '85449', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TV6012', '09772', 'Trabajo Social');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MJ5905', '24324', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZN3910', '67240', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('JW4098', '48434', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UQ4124', '60872', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IU1655', '64074', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('IQ6434', '19154', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('AW3166', '83970', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('NP5119', '94522', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('PA5259', '21197', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('AH4270', '28151', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YY1425', '47832', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZB9322', '47769', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ES9742', '74239', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BH6375', '11507', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('XD4406', '16786', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QT7701', '63850', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MH1500', '59532', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OO0269', '47877', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TD8962', '52428', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('SP8071', '19764', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YA5767', '67016', 'Ingenieria');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('FU5239', '27692', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('WN7697', '90320', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UZ2691', '65865', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MS6982', '29253', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('PQ7072', '11814', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QP9039', '82061', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LW9333', '29694', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OV0478', '88068', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QH8144', '66542', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QA3114', '02288', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('GK7373', '65437', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('DV3667', '71917', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZW7656', '81628', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('CM9673', '66008', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BD8763', '76931', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('HJ8618', '55436', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YK1803', '77353', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('PG6462', '50351', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('TT3203', '60475', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LK4309', '74703', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('PX9006', '99560', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YP0400', '96280', 'ENALLT');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('YH1118', '09745', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('MZ9645', '20662', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UP2166', '20992', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QS5855', '17298', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('HX3721', '60446', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BJ0650', '68878', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ML8974', '11180', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('VM0420', '32524', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('BF2145', '30253', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RD8605', '76598', 'Arquitectura');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OP7520', '41900', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RN9127', '85020', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('NQ5265', '31749', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('QB0579', '86994', 'Trabajo Social');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('SS5996', '63608', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('OA7373', '88828', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('KT8179', '19835', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('DU2455', '32821', 'Contaduria y Administracion');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('AF3949', '31312', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('VM4407', '95065', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('ZC5641', '35331', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LP2407', '93248', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('UI1199', '79207', 'Economia');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('NW6905', '29659', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('PC4772', '46472', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('LJ6373', '10433', 'Quimica');
insert into clientes (id_persona, id_cliente, ubicacion_cu) values ('RB1827', '10187', 'Economia');
