insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08105', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('04052', 'Gustavo A. Madero', 'Sonora', 'Molinito', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('22496', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 59);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('07594', 'Miguel Hidalgo', 'Universidad', 'Molinito', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11688', 'Miguel Hidalgo', 'Sonora', 'Molinito', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('16945', 'Azcapotzalco', 'Universidad', 'Coapa', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('45005', 'Miguel Hidalgo', 'Universidad', 'Coapa', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('67502', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15974', 'Azcapotzalco', 'Universidad', 'Coapa', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61174', 'Miguel Hidalgo', 'Sonora', 'Molinito', 53);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('49963', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('30685', 'Tlalpan', 'Toreo', 'Molinito', 53);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('37591', 'Azcapotzalco', 'Sonora', 'Coapa', 83);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('83876', 'Miguel Hidalgo', 'Universidad', 'Coapa', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('85257', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('05046', 'Miguel Hidalgo', 'Sonora', 'Coapa', 9);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('14958', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('04493', 'Miguel Hidalgo', 'Sonora', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('17241', 'Azcapotzalco', 'Universidad', 'Coapa', 75);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65603', 'Miguel Hidalgo', 'Universidad', 'Molinito', 90);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('73549', 'Benito Juarez', 'Toreo', 'Molinito', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('27995', 'Cuauhtemoc', 'Toreo', 'Molinito', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('41862', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 82);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('47043', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 49);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('45560', 'Miguel Hidalgo', 'Sonora', 'Coapa', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64257', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('09364', 'Tlalpan', 'Sonora', 'Coapa', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('66772', 'Benito Juarez', 'Sonora', 'Molinito', 100);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('72199', 'Cuauhtemoc', 'Sonora', 'Copilco', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('58797', 'Benito Juarez', 'Sonora', 'Molinito', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('68310', 'Azcapotzalco', 'Sonora', 'Coapa', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('16817', 'Miguel Hidalgo', 'Garibaldi', 'Rep. Costa Rica', 49);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11562', 'Miguel Hidalgo', 'Sonora', 'Coapa', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('67151', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('92427', 'Cuauhtemoc', 'Universidad', 'Molinito', 80);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('30569', 'Miguel Hidalgo', 'Universidad', 'Molinito', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('94316', 'Azcapotzalco', 'Universidad', 'Coapa', 18);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('47403', 'Azcapotzalco', 'Sonora', 'Coapa', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('28287', 'Miguel Hidalgo', 'Sonora', 'Molinito', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32407', 'Miguel Hidalgo', 'Sonora', 'Coapa', 15);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('87774', 'Miguel Hidalgo', 'Zacatepec', 'Rep. Brasil', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('69370', 'Azcapotzalco', 'Zacatepec', 'Molinito', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('13416', 'Iztacalco', 'Universidad', 'Molinito', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('21151', 'Azcapotzalco', 'Universidad', 'Coapa', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('50972', 'Miguel Hidalgo', 'Sonora', 'Coapa', 21);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('96421', 'Coyoacan', 'Sonora', 'Rep. Brasil', 12);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('63945', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('70488', 'Cuauhtemoc', 'Sonora', 'Molinito', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('91740', 'Miguel Hidalgo', 'Garibaldi', 'Rep. Brasil', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15601', 'Miguel Hidalgo', 'Sonora', 'Coapa', 42);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('39824', 'Azcapotzalco', 'Toreo', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('50224', 'Cuauhtemoc', 'Zacatepec', 'Molinito', 88);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('58206', 'Coyoacan', 'Sonora', 'Coapa', 49);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('62388', 'Cuauhtemoc', 'Sonora', 'Coapa', 11);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('57463', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 40);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64896', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('44755', 'Azcapotzalco', 'Barrio Norte', 'Rep. Costa Rica', 38);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('40427', 'Benito Juarez', 'Sonora', 'Coapa', 77);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('09299', 'Cuauhtemoc', 'Toreo', 'Coapa', 18);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('55404', 'Azcapotzalco', 'Sonora', 'Coapa', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('41108', 'Miguel Hidalgo', 'Sonora', 'Coapa', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('49463', 'Miguel Hidalgo', 'Sonora', 'Coapa', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('68255', 'Azcapotzalco', 'Universidad', 'Rep. Brasil', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('59865', 'Azcapotzalco', 'Universidad', 'Molinito', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('26752', 'Miguel Hidalgo', 'Universidad', 'Coapa', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('68771', 'Azcapotzalco', 'Toreo', 'Molinito', 100);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('05246', 'Benito Juarez', 'Sonora', 'Molinito', 15);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('78971', 'Cuauhtemoc', 'Toreo', 'Coapa', 9);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65013', 'Cuauhtemoc', 'Garibaldi', 'Coapa', 82);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('82066', 'Cuauhtemoc', 'Sonora', 'Coapa', 26);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('10206', 'Miguel Hidalgo', 'Universidad', 'Molinito', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65895', 'Miguel Hidalgo', 'Toreo', 'Coapa', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('94399', 'Gustavo A. Madero', 'Universidad', 'Rep. Brasil', 11);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('20549', 'Azcapotzalco', 'Universidad', 'Rep. Brasil', 71);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('53579', 'Azcapotzalco', 'Sonora', 'Molinito', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('62046', 'Tlalpan', 'Universidad', 'Coapa', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('75165', 'Cuauhtemoc', 'Sonora', 'Coapa', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24350', 'Miguel Hidalgo', 'Sonora', 'Molinito', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('03232', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 23);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('47677', 'Miguel Hidalgo', 'Sonora', 'Coapa', 87);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('09918', 'Benito Juarez', 'Universidad', 'Molinito', 89);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('23767', 'Azcapotzalco', 'Sonora', 'Salto del Agua', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95482', 'Azcapotzalco', 'Sonora', 'Coapa', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('02384', 'Miguel Hidalgo', 'Sonora', 'Molinito', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('57695', 'Azcapotzalco', 'Sonora', 'Molinito', 7);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('76998', 'Benito Juarez', 'Sonora', 'Rep. Costa Rica', 50);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('37751', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33247', 'Miguel Hidalgo', 'Universidad', 'Coapa', 8);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('96180', 'Azcapotzalco', 'Toreo', 'Molinito', 8);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('76785', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 94);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33414', 'Cuauhtemoc', 'Toreo', 'Rep. Costa Rica', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('42611', 'Miguel Hidalgo', 'Sonora', 'Coapa', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('18559', 'Tlalpan', 'Sonora', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('23401', 'Miguel Hidalgo', 'Toreo', 'Salto del Agua', 34);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95337', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('76463', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 35);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32269', 'Miguel Hidalgo', 'Sonora', 'Coapa', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97485', 'Benito Juarez', 'Universidad', 'Rep. Brasil', 99);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32758', 'Miguel Hidalgo', 'Sonora', 'Coapa', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33845', 'Benito Juarez', 'Universidad', 'Coapa', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97505', 'Azcapotzalco', 'Sonora', 'Molinito', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15930', 'Miguel Hidalgo', 'Sonora', 'Coapa', 40);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('74211', 'Miguel Hidalgo', 'Sonora', 'Coapa', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('49278', 'Coyoacan', 'Sonora', 'Rep. Costa Rica', 100);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('80000', 'Cuauhtemoc', 'Universidad', 'Molinito', 62);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('84884', 'Miguel Hidalgo', 'Universidad', 'Molinito', 35);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('98911', 'Cuauhtemoc', 'Universidad', 'Molinito', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32114', 'Azcapotzalco', 'Sonora', 'Molinito', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('58578', 'Azcapotzalco', 'Sonora', 'Coapa', 100);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('26385', 'Miguel Hidalgo', 'Universidad', 'Coapa', 35);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('81277', 'Miguel Hidalgo', 'Toreo', 'Coapa', 9);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('19059', 'Benito Juarez', 'Sonora', 'Copilco', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('43348', 'Miguel Hidalgo', 'Sonora', 'Coapa', 77);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('72978', 'Azcapotzalco', 'Sonora', 'Molinito', 77);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15581', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 94);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('13281', 'Benito Juarez', 'Universidad', 'Rep. Brasil', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('34648', 'Cuauhtemoc', 'Zacatepec', 'Molinito', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('67914', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('78808', 'Benito Juarez', 'Sonora', 'Coapa', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('58989', 'Cuauhtemoc', 'Sonora', 'Molinito', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('31040', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 87);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('99545', 'Miguel Hidalgo', 'Universidad', 'Molinito', 8);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('85483', 'Azcapotzalco', 'Zacatepec', 'Coapa', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('59601', 'Azcapotzalco', 'Sonora', 'Molinito', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('98311', 'Coyoacan', 'Universidad', 'Coapa', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65488', 'Miguel Hidalgo', 'Sonora', 'Molinito', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('99978', 'Cuauhtemoc', 'Universidad', 'Minnesota', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('07291', 'Miguel Hidalgo', 'Sonora', 'Coapa', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('14460', 'Miguel Hidalgo', 'Toreo', 'Coapa', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24758', 'Azcapotzalco', 'Universidad', 'Molinito', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('94281', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('60015', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('07245', 'Gustavo A. Madero', 'Garibaldi', 'Molinito', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('72602', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 59);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('43569', 'Azcapotzalco', 'Sonora', 'Coapa', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11602', 'Miguel Hidalgo', 'Sonora', 'Coapa', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('34151', 'Miguel Hidalgo', 'Sonora', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('63481', 'Azcapotzalco', 'Sonora', 'Molinito', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61105', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('52980', 'Benito Juarez', 'Ciudad Universitaria', 'Coapa', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24215', 'Miguel Hidalgo', 'Sonora', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('07002', 'Azcapotzalco', 'Sonora', 'Coapa', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('52449', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('75887', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 35);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('98960', 'Azcapotzalco', 'Universidad', 'Coapa', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('40945', 'Gustavo A. Madero', 'Universidad', 'Coapa', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('23859', 'Miguel Hidalgo', 'Garibaldi', 'Coapa', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24909', 'Gustavo A. Madero', 'Sonora', 'Coapa', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('49030', 'Miguel Hidalgo', 'Sonora', 'Molinito', 50);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('23923', 'Miguel Hidalgo', 'Sonora', 'Molinito', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('10608', 'Miguel Hidalgo', 'Sonora', 'Coapa', 87);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('52331', 'Miguel Hidalgo', 'Universidad', 'Molinito', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('85777', 'Azcapotzalco', 'Sonora', 'Molinito', 35);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35226', 'Cuauhtemoc', 'Sonora', 'Coapa', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('50226', 'Miguel Hidalgo', 'Universidad', 'Coapa', 44);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('17178', 'Benito Juarez', 'Universidad', 'Coapa', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('55284', 'Azcapotzalco', 'Ciudad Universitaria', 'Molinito', 57);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('05115', 'Miguel Hidalgo', 'Sonora', 'Coapa', 7);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('17036', 'Azcapotzalco', 'Universidad', 'Coapa', 92);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97314', 'Azcapotzalco', 'Sonora', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35743', 'Benito Juarez', 'Sonora', 'Coapa', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97713', 'Coyoacan', 'Sonora', 'Coapa', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35050', 'Benito Juarez', 'Sonora', 'Coapa', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('46426', 'Azcapotzalco', 'Toreo', 'Rep. Brasil', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('46637', 'Miguel Hidalgo', 'Toreo', 'Rep. Brasil', 42);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97092', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 60);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('78193', 'Benito Juarez', 'Sonora', 'Coapa', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('83692', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('51556', 'Azcapotzalco', 'Toreo', 'Coapa', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('23123', 'Miguel Hidalgo', 'Sonora', 'Molinito', 60);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('96039', 'Cuauhtemoc', 'Zacatepec', 'Coapa', 87);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11960', 'Cuauhtemoc', 'Universidad', 'Coapa', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('12773', 'Miguel Hidalgo', 'Universidad', 'Coapa', 54);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('58352', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('52618', 'Azcapotzalco', 'Sonora', 'Molinito', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('54674', 'Miguel Hidalgo', 'Universidad', 'Coapa', 10);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('21935', 'Cuauhtemoc', 'Sonora', 'Coapa', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('42978', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 18);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('78272', 'Magdalena Contreras', 'Sonora', 'Coapa', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('73559', 'Benito Juarez', 'Sonora', 'Coapa', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('02169', 'Miguel Hidalgo', 'Sonora', 'Coapa', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('10758', 'Azcapotzalco', 'Zacatepec', 'Coapa', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('52234', 'Azcapotzalco', 'Universidad', 'Molinito', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08808', 'Azcapotzalco', 'Sonora', 'Molinito', 10);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('60750', 'Miguel Hidalgo', 'Toreo', 'Coapa', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33802', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95440', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('80812', 'Miguel Hidalgo', 'Sonora', 'Coapa', 62);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('93621', 'Miguel Hidalgo', 'Sonora', 'Molinito', 53);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97830', 'Benito Juarez', 'Universidad', 'Molinito', 53);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('56146', 'Miguel Hidalgo', 'Sonora', 'Coapa', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('85896', 'Cuauhtemoc', 'Sonora', 'Molinito', 39);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95235', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 82);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('04152', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('92835', 'Azcapotzalco', 'Sonora', 'Coapa', 99);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15546', 'Cuauhtemoc', 'Sonora', 'Doctor Vertiz', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97756', 'Miguel Hidalgo', 'Universidad', 'Molinito', 90);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('68373', 'Miguel Hidalgo', 'Toreo', 'Coapa', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('22282', 'Miguel Hidalgo', 'Universidad', 'Molinito', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('99910', 'Cuauhtemoc', 'Sonora', 'Coapa', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('43404', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('41889', 'Miguel Hidalgo', 'Sonora', 'Coapa', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('80397', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('19338', 'Coyoacan', 'Garibaldi', 'Molinito', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('98618', 'Azcapotzalco', 'Sonora', 'Coapa', 29);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('22699', 'Azcapotzalco', 'Sonora', 'Molinito', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('29126', 'Miguel Hidalgo', 'Sonora', 'Coapa', 18);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11139', 'Benito Juarez', 'Sonora', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('85360', 'Benito Juarez', 'Sonora', 'Coapa', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97202', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('10338', 'Cuauhtemoc', 'Sonora', 'Coapa', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('84825', 'Cuauhtemoc', 'Sonora', 'Coapa', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('13457', 'Miguel Hidalgo', 'Sonora', 'Coapa', 83);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('34955', 'Cuauhtemoc', 'Universidad', 'Coapa', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('06763', 'Azcapotzalco', 'Sonora', 'Rep. Brasil', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('89095', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 41);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('78012', 'Miguel Hidalgo', 'Sonora', 'Molinito', 54);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('57007', 'Miguel Hidalgo', 'Sonora', 'Coapa', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('73699', 'Azcapotzalco', 'Sonora', 'Molinito', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11120', 'Miguel Hidalgo', 'Roma', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('44857', 'Miguel Hidalgo', 'Sonora', 'Coapa', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('71062', 'Miguel Hidalgo', 'Toreo', 'Coapa', 89);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32975', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('70200', 'Miguel Hidalgo', 'Sonora', 'Coapa', 35);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('20335', 'Miguel Hidalgo', 'Sonora', 'Molinito', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('73095', 'Azcapotzalco', 'Sonora', 'Coapa', 9);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('86569', 'Azcapotzalco', 'Toreo', 'Coapa', 41);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('76289', 'Miguel Hidalgo', 'Sonora', 'Coapa', 27);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('71515', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('72495', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('18374', 'Miguel Hidalgo', 'Universidad', 'Coapa', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('00599', 'Miguel Hidalgo', 'Zacatepec', 'Rep. Brasil', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64141', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('00739', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('34202', 'Miguel Hidalgo', 'Universidad', 'Coapa', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('48272', 'Coyoacan', 'Roma', 'Coapa', 45);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('71007', 'Azcapotzalco', 'Sonora', 'Coapa', 89);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32213', 'Azcapotzalco', 'Universidad', 'Coapa', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('17855', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 33);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('56741', 'Cuauhtemoc', 'Garibaldi', 'Coapa', 82);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('66113', 'Miguel Hidalgo', 'Toreo', 'Coapa', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('73598', 'Azcapotzalco', 'Insurgentes', 'Rep. Costa Rica', 59);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('50753', 'Benito Juarez', 'Sonora', 'Molinito', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11531', 'Benito Juarez', 'Sonora', 'Coapa', 40);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('03308', 'Azcapotzalco', 'Toreo', 'Coapa', 57);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('98753', 'Miguel Hidalgo', 'Sonora', 'Coapa', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('28316', 'Miguel Hidalgo', 'Sonora', 'Coapa', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32681', 'Miguel Hidalgo', 'Sonora', 'Molinito', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('13042', 'Benito Juarez', 'Universidad', 'Doctor Vertiz', 92);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('31202', 'Cuauhtemoc', 'Zacatepec', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('66505', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 42);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('03987', 'Miguel Hidalgo', 'Sonora', 'Coapa', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65742', 'Miguel Hidalgo', 'Sonora', 'Coapa', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('29212', 'Azcapotzalco', 'Universidad', 'Salto del Agua', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95183', 'Cuauhtemoc', 'Sonora', 'Coapa', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('80616', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('70493', 'Miguel Hidalgo', 'Universidad', 'Molinito', 40);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('00856', 'Azcapotzalco', 'Sonora', 'Coapa', 18);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15885', 'Cuauhtemoc', 'Sonora', 'Coapa', 62);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('98989', 'Cuauhtemoc', 'Toreo', 'Rep. Costa Rica', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('42892', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 38);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('43065', 'Miguel Hidalgo', 'Universidad', 'Coapa', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('21743', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 56);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('44138', 'Coyoacan', 'Sonora', 'Rep. Costa Rica', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('20062', 'Miguel Hidalgo', 'Sonora', 'Coapa', 83);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('54038', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('57226', 'Miguel Hidalgo', 'Universidad', 'Coapa', 79);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('80402', 'Azcapotzalco', 'Toreo', 'Molinito', 62);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('19140', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('23138', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('91998', 'Miguel Hidalgo', 'Toreo', 'Coapa', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('16584', 'Miguel Hidalgo', 'Sonora', 'Coapa', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('14881', 'Benito Juarez', 'Universidad', 'Rep. Brasil', 60);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('05575', 'Miguel Hidalgo', 'Garibaldi', 'Coapa', 82);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('38581', 'Miguel Hidalgo', 'Sonora', 'Coapa', 77);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('69463', 'Miguel Hidalgo', 'Sonora', 'Coapa', 21);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33735', 'Miguel Hidalgo', 'Toreo', 'Molinito', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('98555', 'Azcapotzalco', 'Sonora', 'Molinito', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65963', 'Benito Juarez', 'Universidad', 'Rep. Costa Rica', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('54098', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 53);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('66239', 'Miguel Hidalgo', 'Universidad', 'Molinito', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('03093', 'Miguel Hidalgo', 'Universidad', 'Coapa', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('54933', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('69616', 'Cuauhtemoc', 'Universidad', 'Coapa', 45);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95114', 'Azcapotzalco', 'Sonora', 'Molinito', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08989', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('54063', 'Cuauhtemoc', 'Toreo', 'Salto del Agua', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('50556', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 69);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('52662', 'Miguel Hidalgo', 'Universidad', 'Coapa', 87);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('89944', 'Miguel Hidalgo', 'Universidad', 'Molinito', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('31082', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('37995', 'Cuauhtemoc', 'Universidad', 'Coapa', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('57738', 'Azcapotzalco', 'Sonora', 'Rep. Brasil', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61355', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('71268', 'Miguel Hidalgo', 'Universidad', 'Coapa', 71);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('02177', 'Azcapotzalco', 'Toreo', 'Molinito', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64419', 'Cuauhtemoc', 'Universidad', 'Coapa', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('81584', 'Miguel Hidalgo', 'Sonora', 'Molinito', 41);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('83476', 'Azcapotzalco', 'Zacatepec', 'Coapa', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('88767', 'Miguel Hidalgo', 'Toreo', 'Coapa', 10);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11555', 'Miguel Hidalgo', 'Sonora', 'Coapa', 89);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('21160', 'Miguel Hidalgo', 'Sonora', 'Coapa', 34);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('73870', 'Cuauhtemoc', 'Sonora', 'Coapa', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('17422', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('16779', 'Azcapotzalco', 'Sonora', 'Coapa', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08700', 'Azcapotzalco', 'Toreo', 'Coapa', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('07397', 'Azcapotzalco', 'Sonora', 'Coapa', 58);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('30538', 'Miguel Hidalgo', 'Sonora', 'Molinito', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('99299', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 75);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64003', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Molinito', 88);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('51242', 'Benito Juarez', 'Universidad', 'Coapa', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('47228', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 49);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('42168', 'Cuauhtemoc', 'Coapa', 'Molinito', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('75733', 'Azcapotzalco', 'Sonora', 'Coapa', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('47735', 'Azcapotzalco', 'Universidad', 'Molinito', 61);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('69668', 'Miguel Hidalgo', 'Sonora', 'Coapa', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64060', 'Miguel Hidalgo', 'Sonora', 'Doctor Vertiz', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('19295', 'Cuauhtemoc', 'Sonora', 'Coapa', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('92603', 'Cuauhtemoc', 'Sonora', 'Coapa', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('89509', 'Miguel Hidalgo', 'Universidad', 'Coapa', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('12872', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('14736', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Molinito', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('47711', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61644', 'Miguel Hidalgo', 'Sonora', 'Coapa', 58);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('84030', 'Miguel Hidalgo', 'Sonora', 'Coapa', 7);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('85193', 'Iztapalapa', 'Ciudad Universitaria', 'Coapa', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('90125', 'Miguel Hidalgo', 'Sonora', 'Coapa', 42);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08712', 'Cuauhtemoc', 'Zacatepec', 'Rep. Costa Rica', 21);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('38683', 'Azcapotzalco', 'Universidad', 'Coapa', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33962', 'Azcapotzalco', 'Sonora', 'Copilco', 79);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32523', 'Azcapotzalco', 'Sonora', 'Coapa', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('29014', 'Azcapotzalco', 'Toreo', 'Coapa', 10);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('54507', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 39);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('18444', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 39);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('70088', 'Miguel Hidalgo', 'Universidad', 'Coapa', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95348', 'Coyoacan', 'Universidad', 'Coapa', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('76664', 'Azcapotzalco', 'Universidad', 'Coapa', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('46590', 'Miguel Hidalgo', 'Sonora', 'Coapa', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('22010', 'Coyoacan', 'Toreo', 'Molinito', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('83637', 'Azcapotzalco', 'Ciudad Universitaria', 'Coapa', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('19940', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('18552', 'Cuauhtemoc', 'Universidad', 'Coapa', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('86188', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 38);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('42870', 'Azcapotzalco', 'Sonora', 'Molinito', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24133', 'Benito Juarez', 'Ciudad Universitaria', 'Coapa', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11804', 'Coyoacan', 'Sonora', 'Coapa', 99);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('39261', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 15);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('12868', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('90648', 'Azcapotzalco', 'Zacatepec', 'Molinito', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15817', 'Miguel Hidalgo', 'Sonora', 'Molinito', 94);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24984', 'Cuauhtemoc', 'Tacubaya', 'Rep. Costa Rica', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('03022', 'Miguel Hidalgo', 'Sonora', 'Molinito', 38);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15127', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 12);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('07834', 'Cuauhtemoc', 'Sonora', 'Molinito', 44);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('42175', 'Benito Juarez', 'Universidad', 'Coapa', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('30286', 'Miguel Hidalgo', 'Toreo', 'Coapa', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('48716', 'Azcapotzalco', 'Universidad', 'Coapa', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('10053', 'Benito Juarez', 'Sonora', 'Coapa', 7);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('02621', 'Cuauhtemoc', 'Insurgentes', 'Rep. Costa Rica', 58);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('20013', 'Miguel Hidalgo', 'Sonora', 'Molinito', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('18354', 'Miguel Hidalgo', 'Sonora', 'Molinito', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('78268', 'Miguel Hidalgo', 'Sonora', 'Coapa', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('26509', 'Miguel Hidalgo', 'Sonora', 'Molinito', 23);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('07395', 'Cuauhtemoc', 'Universidad', 'Rep. Costa Rica', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('59818', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('22586', 'Miguel Hidalgo', 'Toreo', 'Coapa', 18);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61598', 'Cuauhtemoc', 'Toreo', 'Molinito', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08425', 'Azcapotzalco', 'Universidad', 'Coapa', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('48847', 'Miguel Hidalgo', 'Sonora', 'Coapa', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24694', 'Coyoacan', 'Sonora', 'Molinito', 62);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('27560', 'Azcapotzalco', 'Ciudad Universitaria', 'Coapa', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('89226', 'Benito Juarez', 'Toreo', 'Coapa', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('38075', 'Miguel Hidalgo', 'Sonora', 'Molinito', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('48997', 'Azcapotzalco', 'Sonora', 'Molinito', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35579', 'Miguel Hidalgo', 'Universidad', 'Coapa', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61871', 'Benito Juarez', 'Zacatepec', 'Rep. Costa Rica', 23);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('70074', 'Miguel Hidalgo', 'Sonora', 'Molinito', 38);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('68653', 'Tlalpan', 'Toreo', 'Coapa', 39);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('51641', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 92);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('00036', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('69847', 'Miguel Hidalgo', 'Universidad', 'Coapa', 12);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35045', 'Benito Juarez', 'Toreo', 'Rep. Brasil', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('62140', 'Azcapotzalco', 'Universidad', 'Molinito', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('88808', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61032', 'Azcapotzalco', 'Sonora', 'Molinito', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('02554', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('67014', 'Miguel Hidalgo', 'Roma', 'Molinito', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('91792', 'Cuauhtemoc', 'Sonora', 'Coapa', 80);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('89641', 'Azcapotzalco', 'Sonora', 'Molinito', 37);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('80796', 'Azcapotzalco', 'Toreo', 'Doctor Vertiz', 2);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('09901', 'Azcapotzalco', 'Universidad', 'Coapa', 45);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('40315', 'Tlalpan', 'Toreo', 'Molinito', 26);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33272', 'Cuauhtemoc', 'Zacatepec', 'Rep. Costa Rica', 38);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('51988', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('47927', 'Miguel Hidalgo', 'Toreo', 'Molinito', 35);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('67897', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 79);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('75081', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64181', 'Azcapotzalco', 'Sonora', 'Coapa', 12);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('82907', 'Azcapotzalco', 'Sonora', 'Coapa', 100);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35365', 'Miguel Hidalgo', 'Universidad', 'Coapa', 42);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('00508', 'Azcapotzalco', 'Sonora', 'Coapa', 43);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('38356', 'Cuauhtemoc', 'Sonora', 'Salto del Agua', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('67639', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 8);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('68907', 'Miguel Hidalgo', 'Sonora', 'Molinito', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('76437', 'Miguel Hidalgo', 'Sonora', 'Coapa', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('69208', 'Miguel Hidalgo', 'Sonora', 'Molinito', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('36612', 'Miguel Hidalgo', 'Toreo', 'Coapa', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('55301', 'Miguel Hidalgo', 'Sonora', 'Molinito', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('03032', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('39912', 'Miguel Hidalgo', 'Universidad', 'Coapa', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('20527', 'Azcapotzalco', 'Toreo', 'Coapa', 80);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('41547', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 88);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('51440', 'Benito Juarez', 'Universidad', 'Coapa', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('57362', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('92616', 'Miguel Hidalgo', 'Toreo', 'Molinito', 21);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('72067', 'Azcapotzalco', 'Sonora', 'Minnesota', 99);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24386', 'Miguel Hidalgo', 'Toreo', 'Salto del Agua', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('82380', 'Miguel Hidalgo', 'Universidad', 'Coapa', 49);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('13291', 'Miguel Hidalgo', 'Universidad', 'Coapa', 58);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('58053', 'Azcapotzalco', 'Universidad', 'Coapa', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('34720', 'Cuauhtemoc', 'Universidad', 'Molinito', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('78463', 'Cuauhtemoc', 'Ciudad Universitaria', 'Rep. Costa Rica', 58);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('48735', 'Miguel Hidalgo', 'Toreo', 'Coapa', 34);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('83829', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 39);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('31196', 'Miguel Hidalgo', 'Sonora', 'Molinito', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('22414', 'Miguel Hidalgo', 'Toreo', 'Coapa', 8);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('85922', 'Azcapotzalco', 'Universidad', 'Coapa', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('77594', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 88);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('36288', 'Azcapotzalco', 'Coapa', 'Doctor Vertiz', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('25289', 'Miguel Hidalgo', 'Sonora', 'Coapa', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08644', 'Azcapotzalco', 'Zacatepec', 'Molinito', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('95423', 'Miguel Hidalgo', 'Sonora', 'Molinito', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('12382', 'Miguel Hidalgo', 'Sonora', 'Molinito', 42);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('39236', 'Gustavo A. Madero', 'Sonora', 'Coapa', 41);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('59471', 'Miguel Hidalgo', 'Toreo', 'Coapa', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('52410', 'Miguel Hidalgo', 'Sonora', 'Minnesota', 79);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('60365', 'Azcapotzalco', 'Sonora', 'Molinito', 33);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('15700', 'Azcapotzalco', 'Sonora', 'Coapa', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24829', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Molinito', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('32648', 'Benito Juarez', 'Sonora', 'Rep. Costa Rica', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('83553', 'Cuauhtemoc', 'Universidad', 'Molinito', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('04211', 'Azcapotzalco', 'Zacatepec', 'Molinito', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35482', 'Miguel Hidalgo', 'Toreo', 'Coapa', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('46969', 'Miguel Hidalgo', 'Universidad', 'Coapa', 17);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('10297', 'Miguel Hidalgo', 'Sonora', 'Coapa', 39);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('84543', 'Miguel Hidalgo', 'Sonora', 'Coapa', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61868', 'Azcapotzalco', 'Sonora', 'Coapa', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('24934', 'Miguel Hidalgo', 'Insurgentes', 'Coapa', 10);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64471', 'Azcapotzalco', 'Universidad', 'Coapa', 49);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('34946', 'Benito Juarez', 'Sonora', 'Molinito', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('58186', 'Benito Juarez', 'Sonora', 'Coapa', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('55261', 'Cuauhtemoc', 'Sonora', 'Coapa', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('33830', 'Miguel Hidalgo', 'Sonora', 'Minnesota', 34);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('57576', 'Azcapotzalco', 'Universidad', 'Coapa', 22);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('72255', 'Cuauhtemoc', 'Universidad', 'Coapa', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('75989', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 20);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('60178', 'Miguel Hidalgo', 'Sonora', 'Coapa', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('71596', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Molinito', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('49602', 'Miguel Hidalgo', 'Universidad', 'Molinito', 16);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('80336', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('60734', 'Cuauhtemoc', 'Universidad', 'Coapa', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('51757', 'Miguel Hidalgo', 'Sonora', 'Coapa', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('14572', 'Cuauhtemoc', 'Zacatepec', 'Molinito', 90);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('12428', 'Miguel Hidalgo', 'Sonora', 'Coapa', 75);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('00721', 'Cuauhtemoc', 'Sonora', 'Coapa', 90);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('56362', 'Azcapotzalco', 'Universidad', 'Salto del Agua', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('43590', 'Azcapotzalco', 'Ciudad Universitaria', 'Coapa', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('62181', 'Azcapotzalco', 'Sonora', 'Coapa', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('40374', 'Miguel Hidalgo', 'Universidad', 'Coapa', 17);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('75498', 'Miguel Hidalgo', 'Sonora', 'Molinito', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('84011', 'Azcapotzalco', 'Sonora', 'Coapa', 23);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('88439', 'Miguel Hidalgo', 'Universidad', 'Molinito', 61);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('45440', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('73229', 'Miguel Hidalgo', 'Sonora', 'Molinito', 22);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('61615', 'Miguel Hidalgo', 'Sonora', 'Coapa', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('13069', 'Miguel Hidalgo', 'Sonora', 'Coapa', 44);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('97292', 'Miguel Hidalgo', 'Sonora', 'Molinito', 69);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('83218', 'Miguel Hidalgo', 'Sonora', 'Molinito', 12);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('70562', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('69757', 'Miguel Hidalgo', 'Sonora', 'Coapa', 94);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('64612', 'Miguel Hidalgo', 'Sonora', 'Molinito', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('45545', 'Azcapotzalco', 'Universidad', 'Coapa', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('48487', 'Azcapotzalco', 'Sonora', 'Molinito', 26);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('44588', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Molinito', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65749', 'Cuauhtemoc', 'Universidad', 'Coapa', 54);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('08027', 'Miguel Hidalgo', 'Sonora', 'Molinito', 72);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('65151', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 58);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('11131', 'Miguel Hidalgo', 'Sonora', 'Molinito', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('45617', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 23);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('62575', 'Azcapotzalco', 'Universidad', 'Coapa', 33);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('04670', 'Azcapotzalco', 'Universidad', 'Coapa', 50);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('67336', 'Cuauhtemoc', 'Sonora', 'Coapa', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('09853', 'Miguel Hidalgo', 'Sonora', 'Coapa', 45);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('86407', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('12798', 'Tlalpan', 'Toreo', 'Molinito', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('23761', 'Miguel Hidalgo', 'Sonora', 'Coapa', 11);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('94894', 'Miguel Hidalgo', 'Universidad', 'Coapa', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('35109', 'Miguel Hidalgo', 'Toreo', 'Copilco', 17);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('77351', 'Azcapotzalco', 'Sonora', 'Coapa', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values ('56923', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Rep. Brasil', 32);
