insert into destino (id_viaje, delegacion, colonia, calle, lote) values (40086, 'Iztalapa', 'Ermita', 'Torres', 69);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (77490, 'Iztalapa', 'Ermita', 'Torres', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (77590, 'Magdalena Contreras', 'Universidad', 'Torres', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (35867, 'Coyoacan', 'Insurgentes', 'Torres', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (40689, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (30317, 'Iztalapa', 'Insurgentes', 'Torres', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (34519, 'Iztalapa', 'Insurgentes', 'Masaryk', 61);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (26619, 'Magdalena Contreras', 'Ermita', 'Odontologia', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (71350, 'Coyoacan', 'Ermita', 'Copilco', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (68606, 'Iztalapa', 'Insurgentes', 'Torres', 10);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (63128, 'Iztalapa', 'Ermita', 'Torres', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (64525, 'Iztalapa', 'Universidad', 'Torres', 54);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (33436, 'Tlalpan', 'Ermita', 'Copilco', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (71357, 'Magdalena Contreras', 'Ermita', 'Torres', 37);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (49395, 'Magdalena Contreras', 'Universidad', 'Torres', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (34309, 'Coyoacan', 'Ermita', 'Masaryk', 53);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (32187, 'Iztalapa', 'Ermita', 'Torres', 9);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (35727, 'Coyoacan', 'Universidad', 'Copilco', 26);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (91118, 'Tlalpan', 'Insurgentes', 'Torres', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (68292, 'Iztalapa', 'Ermita', 'Torres', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (10208, 'Iztalapa', 'Insurgentes', 'Torres', 7);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (53049, 'Iztalapa', 'Ermita', 'Torres', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (21445, 'Coyoacan', 'Ciudad Universitaria', 'Copilco', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (27791, 'Iztalapa', 'Ermita', 'Masaryk', 21);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (28458, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (40204, 'Iztalapa', 'Insurgentes', 'Torres', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (31355, 'Tlalpan', 'Ermita', 'Torres', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (12836, 'Magdalena Contreras', 'Ermita', 'Copilco', 62);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (61546, 'Iztalapa', 'Universidad', 'Torres', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (36904, 'Iztalapa', 'Insurgentes', 'Masaryk', 29);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (52156, 'Iztalapa', 'Ermita', 'Torres', 98);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (71070, 'Iztalapa', 'Universidad', 'Torres', 77);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (84022, 'Iztalapa', 'Ciudad Universitaria', 'Masaryk', 29);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (85091, 'Iztalapa', 'Ermita', 'Torres', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (12615, 'Tlalpan', 'Ermita', 'Torres', 45);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (48584, 'Iztalapa', 'Ermita', 'Masaryk', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (86039, 'Tlalpan', 'Ciudad Universitaria', 'Torres', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (67231, 'Tlalpan', 'Ermita', 'Torres', 83);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (80021, 'Tlalpan', 'Ciudad Universitaria', 'Odontologia', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (74424, 'Iztalapa', 'Ermita', 'Torres', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (29340, 'Iztalapa', 'Ermita', 'Torres', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (92766, 'Coyoacan', 'Ciudad Universitaria', 'Torres', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (29984, 'Tlalpan', 'Ermita', 'Torres', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (13806, 'Iztalapa', 'Ermita', 'Torres', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (85489, 'Tlalpan', 'Ciudad Universitaria', 'Masaryk', 37);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (89297, 'Tlalpan', 'Ermita', 'Masaryk', 70);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (12049, 'Tlalpan', 'Ermita', 'Masaryk', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (79737, 'Tlalpan', 'Ermita', 'Masaryk', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (14822, 'Magdalena Contreras', 'Universidad', 'Copilco', 69);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (68946, 'Iztalapa', 'Ciudad Universitaria', 'Copilco', 9);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (46851, 'Coyoacan', 'Insurgentes', 'Masaryk', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (55824, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 26);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (44857, 'Iztalapa', 'Ermita', 'Torres', 50);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (90895, 'Tlalpan', 'Ciudad Universitaria', 'Masaryk', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (78688, 'Iztalapa', 'Ermita', 'Torres', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (11070, 'Tlalpan', 'Ermita', 'Torres', 94);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (89206, 'Magdalena Contreras', 'Insurgentes', 'Masaryk', 29);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (37747, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (20723, 'Tlalpan', 'Ciudad Universitaria', 'Torres', 99);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (21792, 'Coyoacan', 'Ermita', 'Odontologia', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (57820, 'Iztalapa', 'Universidad', 'Odontologia', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (29467, 'Iztalapa', 'Insurgentes', 'Torres', 2);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (49967, 'Iztalapa', 'Ermita', 'Torres', 30);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (46791, 'Iztalapa', 'Ermita', 'Copilco', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (12562, 'Tlalpan', 'Insurgentes', 'Torres', 99);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (34818, 'Magdalena Contreras', 'Ermita', 'Torres', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (84563, 'Tlalpan', 'Universidad', 'Copilco', 40);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (29058, 'Iztalapa', 'Ermita', 'Masaryk', 99);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (66961, 'Tlalpan', 'Insurgentes', 'Torres', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (29382, 'Tlalpan', 'Ermita', 'Torres', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (65992, 'Tlalpan', 'Ermita', 'Torres', 44);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (64191, 'Magdalena Contreras', 'Ermita', 'Torres', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (13178, 'Iztalapa', 'Insurgentes', 'Torres', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (64291, 'Tlalpan', 'Ermita', 'Torres', 40);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (39016, 'Iztalapa', 'Ermita', 'Masaryk', 26);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (15660, 'Iztalapa', 'Ermita', 'Odontologia', 23);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (82386, 'Tlalpan', 'Universidad', 'Torres', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (97530, 'Tlalpan', 'Insurgentes', 'Torres', 55);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (46028, 'Iztalapa', 'Ermita', 'Masaryk', 68);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (30393, 'Tlalpan', 'Ermita', 'Torres', 11);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (31814, 'Coyoacan', 'Ermita', 'Torres', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (57029, 'Iztalapa', 'Ermita', 'Odontologia', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (77650, 'Iztalapa', 'Ermita', 'Masaryk', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (91944, 'Iztalapa', 'Insurgentes', 'Masaryk', 47);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (73426, 'Tlalpan', 'Insurgentes', 'Copilco', 70);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (37053, 'Iztalapa', 'Ermita', 'Torres', 41);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (72141, 'Iztalapa', 'Ermita', 'Torres', 53);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (52348, 'Iztalapa', 'Ermita', 'Torres', 70);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (23873, 'Iztalapa', 'Insurgentes', 'Torres', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (27280, 'Iztalapa', 'Insurgentes', 'Copilco', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (61117, 'Tlalpan', 'Ermita', 'Copilco', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (82838, 'Tlalpan', 'Universidad', 'Torres', 77);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (64680, 'Coyoacan', 'Ermita', 'Masaryk', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (22202, 'Iztalapa', 'Ermita', 'Masaryk', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (20510, 'Iztalapa', 'Insurgentes', 'Masaryk', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (43648, 'Tlalpan', 'Universidad', 'Masaryk', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (87352, 'Tlalpan', 'Ermita', 'Masaryk', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (31623, 'Iztalapa', 'Insurgentes', 'Torres', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (93559, 'Iztalapa', 'Insurgentes', 'Torres', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (29970, 'Magdalena Contreras', 'Universidad', 'Odontologia', 1);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (99328, 'Coyoacan', 'Insurgentes', 'Masaryk', 17);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (39120, 'Iztalapa', 'Universidad', 'Odontologia', 46);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (97312, 'Tlalpan', 'Ermita', 'Masaryk', 82);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (73077, 'Iztalapa', 'Ciudad Universitaria', 'Masaryk', 48);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (41651, 'Magdalena Contreras', 'Ciudad Universitaria', 'Torres', 80);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (64668, 'Tlalpan', 'Ciudad Universitaria', 'Torres', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (96276, 'Tlalpan', 'Ermita', 'Torres', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (33480, 'Tlalpan', 'Insurgentes', 'Torres', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (24588, 'Iztalapa', 'Ermita', 'Torres', 8);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (57849, 'Iztalapa', 'Ermita', 'Masaryk', 33);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (62932, 'Iztalapa', 'Ermita', 'Torres', 67);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (67179, 'Iztalapa', 'Ermita', 'Torres', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (26216, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 80);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (63895, 'Magdalena Contreras', 'Insurgentes', 'Torres', 10);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (18802, 'Magdalena Contreras', 'Ciudad Universitaria', 'Masaryk', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (61161, 'Coyoacan', 'Ciudad Universitaria', 'Torres', 9);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (21867, 'Iztalapa', 'Insurgentes', 'Torres', 57);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (57780, 'Iztalapa', 'Universidad', 'Torres', 65);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (68705, 'Iztalapa', 'Ermita', 'Torres', 27);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (97009, 'Iztalapa', 'Insurgentes', 'Masaryk', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (85463, 'Coyoacan', 'Insurgentes', 'Torres', 31);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (60068, 'Coyoacan', 'Ermita', 'Torres', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (72942, 'Iztalapa', 'Insurgentes', 'Odontologia', 81);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (64731, 'Tlalpan', 'Ermita', 'Torres', 75);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (89180, 'Iztalapa', 'Ermita', 'Masaryk', 41);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (53050, 'Iztalapa', 'Universidad', 'Odontologia', 38);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (14828, 'Coyoacan', 'Insurgentes', 'Torres', 64);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (86467, 'Magdalena Contreras', 'Ermita', 'Torres', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (89027, 'Iztalapa', 'Ciudad Universitaria', 'Copilco', 44);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (14123, 'Tlalpan', 'Ermita', 'Copilco', 95);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (87259, 'Iztalapa', 'Ermita', 'Torres', 87);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (32227, 'Iztalapa', 'Ermita', 'Torres', 13);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (64978, 'Iztalapa', 'Ermita', 'Copilco', 17);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (76494, 'Iztalapa', 'Universidad', 'Masaryk', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (66457, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 90);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (92159, 'Iztalapa', 'Insurgentes', 'Torres', 97);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (61391, 'Iztalapa', 'Ermita', 'Torres', 52);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (77888, 'Coyoacan', 'Insurgentes', 'Torres', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (43495, 'Coyoacan', 'Ciudad Universitaria', 'Torres', 57);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (47553, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 11);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (14780, 'Magdalena Contreras', 'Insurgentes', 'Copilco', 74);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (11182, 'Tlalpan', 'Ermita', 'Torres', 85);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (26223, 'Iztalapa', 'Insurgentes', 'Torres', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (20857, 'Iztalapa', 'Insurgentes', 'Copilco', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (90194, 'Iztalapa', 'Universidad', 'Copilco', 43);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (43753, 'Iztalapa', 'Ermita', 'Odontologia', 60);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (93143, 'Iztalapa', 'Universidad', 'Odontologia', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (68695, 'Tlalpan', 'Ermita', 'Torres', 78);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (40219, 'Iztalapa', 'Ermita', 'Masaryk', 15);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (16270, 'Iztalapa', 'Universidad', 'Masaryk', 26);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (69383, 'Tlalpan', 'Universidad', 'Torres', 59);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (42936, 'Magdalena Contreras', 'Universidad', 'Torres', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (95499, 'Iztalapa', 'Ermita', 'Masaryk', 7);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (44510, 'Iztalapa', 'Insurgentes', 'Copilco', 94);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (70931, 'Iztalapa', 'Ermita', 'Torres', 59);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (59495, 'Iztalapa', 'Ermita', 'Torres', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (76204, 'Iztalapa', 'Ermita', 'Copilco', 28);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (69223, 'Coyoacan', 'Universidad', 'Torres', 36);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (88339, 'Iztalapa', 'Ermita', 'Torres', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (75333, 'Iztalapa', 'Ermita', 'Copilco', 54);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (47206, 'Iztalapa', 'Insurgentes', 'Torres', 45);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (99938, 'Iztalapa', 'Insurgentes', 'Torres', 92);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (83895, 'Tlalpan', 'Ermita', 'Masaryk', 70);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (93509, 'Iztalapa', 'Insurgentes', 'Masaryk', 45);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (29300, 'Tlalpan', 'Insurgentes', 'Torres', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (54307, 'Tlalpan', 'Universidad', 'Copilco', 61);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (91861, 'Coyoacan', 'Ermita', 'Torres', 79);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (24152, 'Iztalapa', 'Ciudad Universitaria', 'Odontologia', 49);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (57893, 'Iztalapa', 'Ermita', 'Copilco', 96);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (26851, 'Iztalapa', 'Insurgentes', 'Odontologia', 56);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (92574, 'Iztalapa', 'Ermita', 'Torres', 75);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (78222, 'Magdalena Contreras', 'Insurgentes', 'Torres', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (63961, 'Magdalena Contreras', 'Ciudad Universitaria', 'Torres', 54);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (74381, 'Magdalena Contreras', 'Universidad', 'Torres', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (96209, 'Iztalapa', 'Ermita', 'Torres', 51);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (58475, 'Tlalpan', 'Ermita', 'Torres', 91);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (66826, 'Iztalapa', 'Universidad', 'Torres', 5);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (26380, 'Iztalapa', 'Ermita', 'Odontologia', 32);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (99434, 'Tlalpan', 'Insurgentes', 'Masaryk', 58);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (53357, 'Tlalpan', 'Insurgentes', 'Odontologia', 3);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (12333, 'Iztalapa', 'Insurgentes', 'Torres', 4);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (31618, 'Iztalapa', 'Ermita', 'Copilco', 84);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (40332, 'Iztalapa', 'Insurgentes', 'Copilco', 6);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (98079, 'Magdalena Contreras', 'Ermita', 'Masaryk', 34);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (53640, 'Iztalapa', 'Insurgentes', 'Copilco', 86);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (60359, 'Iztalapa', 'Insurgentes', 'Torres', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (87745, 'Coyoacan', 'Ermita', 'Torres', 66);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (80095, 'Iztalapa', 'Ermita', 'Torres', 20);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (38529, 'Iztalapa', 'Ermita', 'Masaryk', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (44771, 'Coyoacan', 'Insurgentes', 'Torres', 63);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (24820, 'Iztalapa', 'Ermita', 'Torres', 88);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (45486, 'Iztalapa', 'Insurgentes', 'Torres', 24);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (10087, 'Tlalpan', 'Insurgentes', 'Odontologia', 25);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (85371, 'Coyoacan', 'Ermita', 'Masaryk', 76);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (89202, 'Coyoacan', 'Ermita', 'Torres', 73);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (89102, 'Iztalapa', 'Ciudad Universitaria', 'Copilco', 2);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (54929, 'Tlalpan', 'Insurgentes', 'Torres', 14);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (75599, 'Iztalapa', 'Ermita', 'Copilco', 19);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (51261, 'Coyoacan', 'Ermita', 'Torres', 93);
insert into destino (id_viaje, delegacion, colonia, calle, lote) values (34630, 'Tlalpan', 'Insurgentes', 'Odontologia', 8);
