insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YA8183', 'Miguel Hidalgo', 'Universidad', 'Coapa', 91);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QB4837', 'Azcapotzalco', 'Toreo', 'Coapa', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NI3785', 'Benito Juarez', 'Zacatepec', 'Molinito', 22);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MU7335', 'Cuauhtemoc', 'Universidad', 'Coapa', 93);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VZ5098', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 37);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MK8010', 'Azcapotzalco', 'Ciudad Universitaria', 'Coapa', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YM3028', 'Miguel Hidalgo', 'Sonora', 'Coapa', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SW2929', 'Azcapotzalco', 'Sonora', 'Coapa', 89);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HN1671', 'Miguel Hidalgo', 'Universidad', 'Coapa', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YE3970', 'Miguel Hidalgo', 'Toreo', 'Coapa', 57);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YV6666', 'Azcapotzalco', 'Sonora', 'Molinito', 40);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OM5096', 'Azcapotzalco', 'Sonora', 'Coapa', 50);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BO6105', 'Benito Juarez', 'Sonora', 'Salto del Agua', 6);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DB0706', 'Miguel Hidalgo', 'Sonora', 'Molinito', 62);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WP6655', 'Tlalpan', 'Sonora', 'Rep. Brasil', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IP7984', 'Cuauhtemoc', 'Toreo', 'Rep. Costa Rica', 52);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PD0662', 'Cuauhtemoc', 'Toreo', 'Molinito', 13);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LC5338', 'Miguel Hidalgo', 'Sonora', 'Coapa', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YU5577', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 42);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UI5143', 'Miguel Hidalgo', 'Toreo', 'Molinito', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HU2301', 'Azcapotzalco', 'Zacatepec', 'Rep. Brasil', 32);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WL4324', 'Miguel Hidalgo', 'Sonora', 'Coapa', 45);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NL8258', 'Miguel Hidalgo', 'Sonora', 'Molinito', 72);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MD3500', 'Azcapotzalco', 'Toreo', 'Coapa', 39);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KY5631', 'Benito Juarez', 'Sonora', 'Coapa', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TW4477', 'Miguel Hidalgo', 'Sonora', 'Coapa', 90);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IJ7566', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Rep. Costa Rica', 65);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KM5323', 'Miguel Hidalgo', 'Universidad', 'Coapa', 3);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IO1731', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 24);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AA9586', 'Azcapotzalco', 'Toreo', 'Coapa', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MP9181', 'Cuauhtemoc', 'Zacatepec', 'Coapa', 85);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AI0127', 'Miguel Hidalgo', 'Sonora', 'Molinito', 6);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PP6109', 'Tlalpan', 'Ciudad Universitaria', 'Coapa', 85);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ME4788', 'Coyoacan', 'Sonora', 'Doctor Vertiz', 45);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SE4359', 'Miguel Hidalgo', 'Sonora', 'Coapa', 52);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZS9104', 'Miguel Hidalgo', 'Toreo', 'Molinito', 26);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JY6771', 'Miguel Hidalgo', 'Universidad', 'Coapa', 2);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MI2085', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 10);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BZ3822', 'Benito Juarez', 'Bondojito', 'Coapa', 96);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RR5583', 'Miguel Hidalgo', 'Sonora', 'Molinito', 96);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YG1966', 'Miguel Hidalgo', 'Sonora', 'Molinito', 29);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IK8325', 'Azcapotzalco', 'Zacatepec', 'Rep. Brasil', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MS2485', 'Azcapotzalco', 'Universidad', 'Coapa', 47);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JA3839', 'Miguel Hidalgo', 'Sonora', 'Coapa', 29);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WW6328', 'Miguel Hidalgo', 'Universidad', 'Coapa', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AT7217', 'Cuauhtemoc', 'Zacatepec', 'Molinito', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZA9301', 'Miguel Hidalgo', 'Sonora', 'Coapa', 31);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PM2582', 'Benito Juarez', 'Sonora', 'Doctor Vertiz', 47);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AU7719', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GF5255', 'Benito Juarez', 'Universidad', 'Doctor Vertiz', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EX0857', 'Azcapotzalco', 'Sonora', 'Molinito', 8);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DC0293', 'Miguel Hidalgo', 'Universidad', 'Molinito', 16);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SO4585', 'Benito Juarez', 'Sonora', 'Coapa', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PH9330', 'Azcapotzalco', 'Sonora', 'Odontologia', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JD2792', 'Miguel Hidalgo', 'Sonora', 'Molinito', 95);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KU2325', 'Miguel Hidalgo', 'Sonora', 'Coapa', 99);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GI9363', 'Azcapotzalco', 'Universidad', 'Coapa', 20);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DN6280', 'Azcapotzalco', 'Zacatepec', 'Salto del Agua', 43);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NL3894', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 24);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ND2680', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 96);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZJ7369', 'Azcapotzalco', 'Sonora', 'Molinito', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WI4610', 'Azcapotzalco', 'Sonora', 'Coapa', 57);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NB1710', 'Gustavo A. Madero', 'Sonora', 'Coapa', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BG2732', 'Miguel Hidalgo', 'Toreo', 'Coapa', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FT9227', 'Miguel Hidalgo', 'Sonora', 'Coapa', 70);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VC2377', 'Azcapotzalco', 'Universidad', 'Coapa', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NC0282', 'Azcapotzalco', 'Ciudad Universitaria', 'Salto del Agua', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GW5062', 'Cuauhtemoc', 'Garibaldi', 'Coapa', 40);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BA5244', 'Miguel Hidalgo', 'Sonora', 'Coapa', 75);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QY4642', 'Miguel Hidalgo', 'Toreo', 'Coapa', 9);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WQ7927', 'Benito Juarez', 'Universidad', 'Rep. Brasil', 96);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NQ9917', 'Miguel Hidalgo', 'Sonora', 'Coapa', 97);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KH2068', 'Miguel Hidalgo', 'Sonora', 'Molinito', 32);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YC7547', 'Azcapotzalco', 'Ciudad Universitaria', 'Rep. Costa Rica', 5);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JL4754', 'Miguel Hidalgo', 'Toreo', 'Coapa', 1);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JA8152', 'Miguel Hidalgo', 'Universidad', 'Coapa', 44);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DR5129', 'Azcapotzalco', 'Universidad', 'Coapa', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EM4507', 'Miguel Hidalgo', 'Toreo', 'Molinito', 62);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QI1305', 'Miguel Hidalgo', 'Sonora', 'Molinito', 93);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KH5780', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 98);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UK0162', 'Azcapotzalco', 'Sonora', 'Molinito', 1);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CF7472', 'Benito Juarez', 'Universidad', 'Molinito', 65);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RF9275', 'Cuauhtemoc', 'Sonora', 'Coapa', 18);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TO4369', 'Miguel Hidalgo', 'Insurgentes', 'Coapa', 43);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YA8680', 'Miguel Hidalgo', 'Sonora', 'Coapa', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KP4894', 'Azcapotzalco', 'Sonora', 'Coapa', 16);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VU8426', 'Azcapotzalco', 'Toreo', 'Molinito', 9);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BA8931', 'Miguel Hidalgo', 'Garibaldi', 'Coapa', 49);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WM7475', 'Cuauhtemoc', 'Universidad', 'Coapa', 51);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SS0724', 'Azcapotzalco', 'Universidad', 'Coapa', 42);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NP5488', 'Azcapotzalco', 'Sonora', 'Coapa', 57);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WA9126', 'Miguel Hidalgo', 'Universidad', 'Coapa', 85);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GB3172', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 22);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WW4260', 'Cuauhtemoc', 'Universidad', 'Coapa', 83);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MR6084', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 87);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UY6055', 'Azcapotzalco', 'Universidad', 'Rep. Brasil', 62);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QD7251', 'Miguel Hidalgo', 'Sonora', 'Coapa', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SE8955', 'Azcapotzalco', 'Sonora', 'Coapa', 30);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HW5770', 'Azcapotzalco', 'Universidad', 'Coapa', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TF8971', 'Benito Juarez', 'Universidad', 'Molinito', 19);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EO0203', 'Azcapotzalco', 'Tacubaya', 'Coapa', 78);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MU0949', 'Miguel Hidalgo', 'Universidad', 'Coapa', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VP7167', 'Miguel Hidalgo', 'Universidad', 'Coapa', 51);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OG4425', 'Azcapotzalco', 'Universidad', 'Molinito', 97);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FM7517', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 9);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XT7093', 'Coyoacan', 'Universidad', 'Coapa', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JT2790', 'Miguel Hidalgo', 'Sonora', 'Doctor Vertiz', 38);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KV0765', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JV0983', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 86);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PU3088', 'Azcapotzalco', 'Sonora', 'Coapa', 48);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SL0358', 'Miguel Hidalgo', 'Sonora', 'Coapa', 21);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OG4839', 'Azcapotzalco', 'Universidad', 'Coapa', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KK7715', 'Miguel Hidalgo', 'Sonora', 'Molinito', 100);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MK6969', 'Coyoacan', 'Universidad', 'Salto del Agua', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FO9141', 'Azcapotzalco', 'Zacatepec', 'Molinito', 39);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KA0984', 'Benito Juarez', 'Sonora', 'Coapa', 28);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JI3079', 'Miguel Hidalgo', 'Sonora', 'Coapa', 30);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BS2625', 'Miguel Hidalgo', 'Universidad', 'Coapa', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NE0921', 'Miguel Hidalgo', 'Universidad', 'Coapa', 82);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LE3544', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LP6239', 'Benito Juarez', 'Sonora', 'Coapa', 85);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NZ6747', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 52);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ME0262', 'Miguel Hidalgo', 'Sonora', 'Coapa', 6);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TA0159', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 87);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OC5830', 'Miguel Hidalgo', 'Sonora', 'Molinito', 60);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZS8736', 'Azcapotzalco', 'Sonora', 'Molinito', 88);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NP9534', 'Azcapotzalco', 'Toreo', 'Coapa', 78);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PZ8511', 'Tlalpan', 'Roma', 'Coapa', 98);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GE5508', 'Cuauhtemoc', 'Sonora', 'Coapa', 3);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GB3867', 'Azcapotzalco', 'Universidad', 'Coapa', 8);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AJ5345', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Molinito', 71);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EB6199', 'Miguel Hidalgo', 'Sonora', 'Coapa', 5);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SF9639', 'Cuauhtemoc', 'Zacatepec', 'Coapa', 78);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LT7377', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 69);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IS7823', 'Cuauhtemoc', 'Toreo', 'Coapa', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZV7118', 'Azcapotzalco', 'Toreo', 'Rep. Costa Rica', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RU8001', 'Azcapotzalco', 'Universidad', 'Coapa', 59);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RE5011', 'Cuauhtemoc', 'Universidad', 'Molinito', 50);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NT5475', 'Miguel Hidalgo', 'Sonora', 'Coapa', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WM7797', 'Miguel Hidalgo', 'Universidad', 'Molinito', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BV4563', 'Miguel Hidalgo', 'Universidad', 'Molinito', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JM0127', 'Azcapotzalco', 'Sonora', 'Coapa', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WN9905', 'Miguel Hidalgo', 'Sonora', 'Coapa', 38);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GH6924', 'Miguel Hidalgo', 'Universidad', 'Coapa', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LI9561', 'Miguel Hidalgo', 'Sonora', 'Copilco', 37);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RB8830', 'Azcapotzalco', 'Sonora', 'Doctor Vertiz', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MN3077', 'Miguel Hidalgo', 'Sonora', 'Coapa', 31);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RI3270', 'Azcapotzalco', 'Universidad', 'Coapa', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YT1292', 'Azcapotzalco', 'Ciudad Universitaria', 'Coapa', 12);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IR8444', 'Miguel Hidalgo', 'Sonora', 'Molinito', 55);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FZ9718', 'Benito Juarez', 'Sonora', 'Coapa', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XB4802', 'Miguel Hidalgo', 'Universidad', 'Molinito', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DK6313', 'Miguel Hidalgo', 'Sonora', 'Molinito', 65);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LP2265', 'Miguel Hidalgo', 'Universidad', 'Coapa', 82);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TX4116', 'Miguel Hidalgo', 'Sonora', 'Molinito', 70);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WW4490', 'Tlalpan', 'Universidad', 'Coapa', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OF6973', 'Azcapotzalco', 'Sonora', 'Coapa', 24);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OL5360', 'Azcapotzalco', 'Sonora', 'Molinito', 100);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BY3158', 'Cuauhtemoc', 'Sonora', 'Coapa', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VV4066', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 82);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QF1265', 'Coyoacan', 'Toreo', 'Coapa', 22);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DM0075', 'Cuauhtemoc', 'Sonora', 'Coapa', 73);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OB2902', 'Gustavo A. Madero', 'Sonora', 'Coapa', 86);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UM0788', 'Miguel Hidalgo', 'Sonora', 'Coapa', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CQ9918', 'Azcapotzalco', 'Sonora', 'Coapa', 44);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VS8019', 'Miguel Hidalgo', 'Sonora', 'Molinito', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GY4015', 'Azcapotzalco', 'Universidad', 'Coapa', 40);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PP4829', 'Azcapotzalco', 'Insurgentes', 'Molinito', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BZ8200', 'Azcapotzalco', 'Sonora', 'Coapa', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IE7379', 'Azcapotzalco', 'Toreo', 'Coapa', 94);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IF3851', 'Miguel Hidalgo', 'Sonora', 'Coapa', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IX1529', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 20);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WF9045', 'Miguel Hidalgo', 'Sonora', 'Molinito', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SD0929', 'Miguel Hidalgo', 'Sonora', 'Molinito', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IU4902', 'Miguel Hidalgo', 'Roma', 'Rep. Costa Rica', 29);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ES3112', 'Azcapotzalco', 'Toreo', 'Rep. Brasil', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UY7025', 'Azcapotzalco', 'Toreo', 'Coapa', 29);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IR4324', 'Miguel Hidalgo', 'Sonora', 'Coapa', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GB0915', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 43);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CQ9239', 'Cuauhtemoc', 'Sonora', 'Molinito', 21);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UY7834', 'Miguel Hidalgo', 'Sonora', 'Molinito', 70);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BO9654', 'Azcapotzalco', 'Toreo', 'Coapa', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PM7183', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 50);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PL9883', 'Cuauhtemoc', 'Universidad', 'Coapa', 99);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NO6766', 'Cuauhtemoc', 'Universidad', 'Coapa', 48);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OP4883', 'Miguel Hidalgo', 'Universidad', 'Coapa', 8);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LB5545', 'Cuauhtemoc', 'Sonora', 'Coapa', 38);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FX4418', 'Benito Juarez', 'Universidad', 'Coapa', 93);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FV4052', 'Miguel Hidalgo', 'Sonora', 'Coapa', 43);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DT0260', 'Azcapotzalco', 'Universidad', 'Coapa', 30);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PJ2671', 'Azcapotzalco', 'Sonora', 'Coapa', 73);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GU2441', 'Miguel Hidalgo', 'Sonora', 'Molinito', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LI5349', 'Iztacalco', 'Toreo', 'Coapa', 88);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HN3064', 'Tlalpan', 'Toreo', 'Coapa', 47);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QB8866', 'Magdalena Contreras', 'Sonora', 'Coapa', 47);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZG3644', 'Miguel Hidalgo', 'Sonora', 'Coapa', 3);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UY0317', 'Miguel Hidalgo', 'Sonora', 'Coapa', 13);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KT0384', 'Benito Juarez', 'Sonora', 'Coapa', 77);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LJ7128', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CN9664', 'Cuauhtemoc', 'Universidad', 'Molinito', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EK5968', 'Miguel Hidalgo', 'Toreo', 'Coapa', 51);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BD2301', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SU2964', 'Miguel Hidalgo', 'Sonora', 'Molinito', 18);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AR7770', 'Miguel Hidalgo', 'Universidad', 'Coapa', 29);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KX2900', 'Cuauhtemoc', 'Sonora', 'Molinito', 57);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EZ0038', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JG7187', 'Miguel Hidalgo', 'Zacatepec', 'Rep. Costa Rica', 97);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DM0623', 'Coyoacan', 'Sonora', 'Coapa', 49);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VC5288', 'Miguel Hidalgo', 'Toreo', 'Coapa', 58);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XE4488', 'Miguel Hidalgo', 'Toreo', 'Coapa', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UC0313', 'Cuauhtemoc', 'Sonora', 'Coapa', 88);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YE3548', 'Miguel Hidalgo', 'Sonora', 'Copilco', 97);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TB8522', 'Miguel Hidalgo', 'Sonora', 'Coapa', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VJ0345', 'Miguel Hidalgo', 'Sonora', 'Coapa', 88);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZZ2183', 'Benito Juarez', 'Universidad', 'Molinito', 12);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TJ6803', 'Miguel Hidalgo', 'Sonora', 'Molinito', 19);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LC6184', 'Azcapotzalco', 'Universidad', 'Molinito', 51);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EL6214', 'Gustavo A. Madero', 'Sonora', 'Salto del Agua', 5);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CP8502', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 36);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KE6130', 'Azcapotzalco', 'Toreo', 'Coapa', 50);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VE8297', 'Benito Juarez', 'Sonora', 'Rep. Costa Rica', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XF5908', 'Azcapotzalco', 'Ciudad Universitaria', 'Molinito', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OT4152', 'Miguel Hidalgo', 'Toreo', 'Coapa', 37);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZL5507', 'Azcapotzalco', 'Toreo', 'Rep. Brasil', 50);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RM7541', 'Benito Juarez', 'Toreo', 'Coapa', 11);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JU6062', 'Azcapotzalco', 'Sonora', 'Coapa', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GC6061', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 46);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VE2301', 'Azcapotzalco', 'Universidad', 'Rep. Brasil', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MT9203', 'Miguel Hidalgo', 'Sonora', 'Molinito', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NE4040', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RT8296', 'Cuauhtemoc', 'Sonora', 'Molinito', 9);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GX9199', 'Miguel Hidalgo', 'Toreo', 'Salto del Agua', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GV8919', 'Iztacalco', 'Sonora', 'Molinito', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NC6794', 'Miguel Hidalgo', 'Universidad', 'Coapa', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SV8515', 'Miguel Hidalgo', 'Toreo', 'Molinito', 85);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZU8874', 'Miguel Hidalgo', 'Insurgentes', 'Coapa', 44);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YN8518', 'Azcapotzalco', 'Universidad', 'Rep. Brasil', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KC0862', 'Azcapotzalco', 'Sonora', 'Coapa', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GA1233', 'Coyoacan', 'Sonora', 'Coapa', 83);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NS1761', 'Azcapotzalco', 'Toreo', 'Rep. Costa Rica', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VC7717', 'Coyoacan', 'Sonora', 'Coapa', 46);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JE1286', 'Miguel Hidalgo', 'Universidad', 'Coapa', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OW4672', 'Azcapotzalco', 'Sonora', 'Coapa', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IH0054', 'Miguel Hidalgo', 'Sonora', 'Coapa', 94);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IX4658', 'Azcapotzalco', 'Toreo', 'Doctor Vertiz', 87);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DU9387', 'Miguel Hidalgo', 'Sonora', 'Coapa', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WP1683', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 52);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BX5967', 'Cuauhtemoc', 'Sonora', 'Molinito', 29);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WR1799', 'Azcapotzalco', 'Zacatepec', 'Molinito', 48);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WT2390', 'Azcapotzalco', 'Toreo', 'Coapa', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XT8591', 'Miguel Hidalgo', 'Toreo', 'Molinito', 59);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MK9903', 'Cuauhtemoc', 'Sonora', 'Coapa', 39);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JJ2872', 'Coyoacan', 'Sonora', 'Coapa', 28);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SJ8761', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VR5595', 'Azcapotzalco', 'Sonora', 'Molinito', 59);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AV5603', 'Azcapotzalco', 'Universidad', 'Molinito', 30);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GT9876', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 41);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JJ5521', 'Azcapotzalco', 'Sonora', 'Molinito', 29);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UI1444', 'Miguel Hidalgo', 'Toreo', 'Coapa', 70);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DY9998', 'Miguel Hidalgo', 'Universidad', 'Molinito', 52);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VA7810', 'Azcapotzalco', 'Sonora', 'Coapa', 52);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YB0327', 'Cuauhtemoc', 'Sonora', 'Coapa', 46);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SQ3074', 'Azcapotzalco', 'Universidad', 'Molinito', 83);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AI7344', 'Miguel Hidalgo', 'Sonora', 'Coapa', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OL2035', 'Azcapotzalco', 'Toreo', 'Molinito', 1);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YT8888', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 31);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OD1064', 'Miguel Hidalgo', 'Universidad', 'Molinito', 93);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QV9989', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 51);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ER6804', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 96);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YY4279', 'Coyoacan', 'Universidad', 'Salto del Agua', 53);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YJ9299', 'Cuauhtemoc', 'Zacatepec', 'Coapa', 14);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JC6106', 'Benito Juarez', 'Sonora', 'Coapa', 86);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BV6303', 'Azcapotzalco', 'Ciudad Universitaria', 'Molinito', 20);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZH8413', 'Benito Juarez', 'Toreo', 'Salto del Agua', 32);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CY9617', 'Gustavo A. Madero', 'Sonora', 'Coapa', 20);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OB8895', 'Miguel Hidalgo', 'Toreo', 'Coapa', 59);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FH2854', 'Cuauhtemoc', 'Toreo', 'Coapa', 93);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LB7552', 'Benito Juarez', 'Sonora', 'Coapa', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HL4657', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 51);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UD2932', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 46);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EJ4193', 'Cuauhtemoc', 'Sonora', 'Coapa', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XK9604', 'Cuauhtemoc', 'Sonora', 'Coapa', 69);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EG1010', 'Azcapotzalco', 'Sonora', 'Coapa', 49);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VT3100', 'Miguel Hidalgo', 'Toreo', 'Molinito', 78);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BT5891', 'Benito Juarez', 'Universidad', 'Coapa', 36);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MJ4407', 'Cuauhtemoc', 'Sonora', 'Salto del Agua', 83);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WA2467', 'Miguel Hidalgo', 'Toreo', 'Molinito', 87);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OQ7772', 'Azcapotzalco', 'Sonora', 'Molinito', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VD7089', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 5);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OP0838', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LW4747', 'Miguel Hidalgo', 'Toreo', 'Molinito', 39);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WW2706', 'Cuauhtemoc', 'Sonora', 'Coapa', 91);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AM1009', 'Miguel Hidalgo', 'Sonora', 'Coapa', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RK0629', 'Miguel Hidalgo', 'Toreo', 'Copilco', 86);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DF8441', 'Miguel Hidalgo', 'Toreo', 'Molinito', 77);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZP0315', 'Azcapotzalco', 'Sonora', 'Coapa', 32);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NB6970', 'Miguel Hidalgo', 'Toreo', 'Rep. Brasil', 51);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EH3275', 'Azcapotzalco', 'Sonora', 'Coapa', 34);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AF0084', 'Miguel Hidalgo', 'Universidad', 'Coapa', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JO2677', 'Miguel Hidalgo', 'Sonora', 'Molinito', 35);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MK9482', 'Cuauhtemoc', 'Roma', 'Rep. Costa Rica', 73);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IJ5624', 'Azcapotzalco', 'Sonora', 'Coapa', 91);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YS1208', 'Azcapotzalco', 'Sonora', 'Molinito', 50);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NE0540', 'Cuauhtemoc', 'Sonora', 'Molinito', 87);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BF0599', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QJ8907', 'Miguel Hidalgo', 'Sonora', 'Coapa', 3);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KC3826', 'Miguel Hidalgo', 'Sonora', 'Doctor Vertiz', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ON9976', 'Cuauhtemoc', 'Toreo', 'Coapa', 71);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YH6278', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 14);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FS1118', 'Miguel Hidalgo', 'Sonora', 'Molinito', 18);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FJ5302', 'Miguel Hidalgo', 'Universidad', 'Coapa', 45);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NU7292', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UG9530', 'Miguel Hidalgo', 'Doctores', 'Rep. Costa Rica', 5);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DW0060', 'Miguel Hidalgo', 'Toreo', 'Coapa', 26);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WX1019', 'Benito Juarez', 'Universidad', 'Coapa', 53);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ON0742', 'Miguel Hidalgo', 'Sonora', 'Molinito', 11);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DV9354', 'Iztacalco', 'Toreo', 'Coapa', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YN6677', 'Azcapotzalco', 'Sonora', 'Coapa', 31);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HI7727', 'Miguel Hidalgo', 'Toreo', 'Molinito', 100);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IC0564', 'Azcapotzalco', 'Toreo', 'Rep. Costa Rica', 82);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HC3849', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 9);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IX1537', 'Tlalpan', 'Universidad', 'Coapa', 84);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LM5001', 'Azcapotzalco', 'Universidad', 'Molinito', 46);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NH1208', 'Cuauhtemoc', 'Universidad', 'Coapa', 59);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MW3913', 'Azcapotzalco', 'Universidad', 'Coapa', 23);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MO5914', 'Miguel Hidalgo', 'Sonora', 'Coapa', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PO7648', 'Coyoacan', 'Sonora', 'Salto del Agua', 45);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CI3495', 'Miguel Hidalgo', 'Universidad', 'Molinito', 38);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NR7322', 'Miguel Hidalgo', 'Universidad', 'Molinito', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UO8890', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 39);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SM8615', 'Miguel Hidalgo', 'Sonora', 'Molinito', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VT5304', 'Miguel Hidalgo', 'Roma', 'Coapa', 21);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AI9101', 'Coyoacan', 'Ciudad Universitaria', 'Rep. Costa Rica', 90);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YN0851', 'Miguel Hidalgo', 'Universidad', 'Coapa', 75);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MM3005', 'Miguel Hidalgo', 'Universidad', 'Coapa', 77);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DJ6536', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 40);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QK3989', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 45);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HB1782', 'Miguel Hidalgo', 'Toreo', 'Coapa', 75);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JX0112', 'Azcapotzalco', 'Universidad', 'Coapa', 98);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KG9732', 'Miguel Hidalgo', 'Universidad', 'Molinito', 41);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RM4520', 'Miguel Hidalgo', 'Sonora', 'Coapa', 66);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VL5162', 'Azcapotzalco', 'Sonora', 'Doctor Vertiz', 16);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AA2981', 'Iztacalco', 'Sonora', 'Molinito', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YK2033', 'Benito Juarez', 'Sonora', 'Coapa', 60);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VV4676', 'Miguel Hidalgo', 'Universidad', 'Coapa', 53);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NI7308', 'Azcapotzalco', 'Sonora', 'Molinito', 83);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QF3987', 'Miguel Hidalgo', 'Sonora', 'Coapa', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GQ5556', 'Benito Juarez', 'Sonora', 'Molinito', 44);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VS4785', 'Azcapotzalco', 'Universidad', 'Doctor Vertiz', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SJ8368', 'Benito Juarez', 'Sonora', 'Rep. Costa Rica', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SF2992', 'Miguel Hidalgo', 'Universidad', 'Coapa', 22);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VB2599', 'Miguel Hidalgo', 'Sonora', 'Coapa', 47);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HX7000', 'Miguel Hidalgo', 'Sonora', 'Coapa', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MA7132', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 5);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DP6753', 'Miguel Hidalgo', 'Sonora', 'Molinito', 12);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BR4707', 'Miguel Hidalgo', 'Sonora', 'Coapa', 95);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FK6511', 'Coyoacan', 'Zacatepec', 'Molinito', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SI7200', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BH9766', 'Miguel Hidalgo', 'Sonora', 'Coapa', 31);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KZ5890', 'Azcapotzalco', 'Toreo', 'Coapa', 55);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AU2884', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OI5463', 'Miguel Hidalgo', 'Sonora', 'Coapa', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PB0338', 'Azcapotzalco', 'Ciudad Universitaria', 'Coapa', 36);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VU8724', 'Miguel Hidalgo', 'Sonora', 'Coapa', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TZ9740', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 90);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GZ8217', 'Benito Juarez', 'Sonora', 'Coapa', 79);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MM5028', 'Azcapotzalco', 'Toreo', 'Molinito', 16);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UA6296', 'Azcapotzalco', 'Universidad', 'Molinito', 13);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AW4548', 'Miguel Hidalgo', 'Sonora', 'Coapa', 72);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WS5116', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Molinito', 98);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CX3776', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 23);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YZ4472', 'Miguel Hidalgo', 'Sonora', 'Molinito', 44);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QO3613', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YH5226', 'Miguel Hidalgo', 'Sonora', 'Coapa', 37);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PO1967', 'Azcapotzalco', 'Zacatepec', 'Rep. Costa Rica', 78);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FA5104', 'Azcapotzalco', 'Sonora', 'Molinito', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MP6493', 'Azcapotzalco', 'Sonora', 'Coapa', 75);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ST8512', 'Benito Juarez', 'Ciudad Universitaria', 'Coapa', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EO8483', 'Miguel Hidalgo', 'Toreo', 'Coapa', 12);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RC8462', 'Azcapotzalco', 'Sonora', 'Rep. Brasil', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UP4011', 'Benito Juarez', 'Sonora', 'Rep. Brasil', 99);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CZ4838', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 43);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GB2441', 'Miguel Hidalgo', 'Universidad', 'Coapa', 47);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AH6874', 'Cuauhtemoc', 'Universidad', 'Coapa', 55);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KH5251', 'Miguel Hidalgo', 'Toreo', 'Coapa', 48);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TR2650', 'Benito Juarez', 'Universidad', 'Molinito', 2);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QX2259', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 94);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MJ6337', 'Miguel Hidalgo', 'Sonora', 'Coapa', 99);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GL9594', 'Miguel Hidalgo', 'Toreo', 'Coapa', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PS8341', 'Benito Juarez', 'Universidad', 'Coapa', 74);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GQ0687', 'Azcapotzalco', 'Zacatepec', 'Coapa', 23);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZX7808', 'Miguel Hidalgo', 'Universidad', 'Coapa', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WL2554', 'Cuauhtemoc', 'Sonora', 'Molinito', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GJ1232', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 18);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TR1547', 'Cuauhtemoc', 'Sonora', 'Coapa', 41);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IU0405', 'Benito Juarez', 'Toreo', 'Molinito', 12);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SH1007', 'Miguel Hidalgo', 'Sonora', 'Molinito', 41);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PM8287', 'Miguel Hidalgo', 'Universidad', 'Coapa', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VU8978', 'Miguel Hidalgo', 'Toreo', 'Coapa', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XM5040', 'Miguel Hidalgo', 'Sonora', 'Coapa', 50);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SK5896', 'Azcapotzalco', 'Sonora', 'Coapa', 26);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DS4740', 'Benito Juarez', 'Universidad', 'Coapa', 76);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RR8947', 'Miguel Hidalgo', 'Toreo', 'Coapa', 49);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('XJ7079', 'Azcapotzalco', 'Sonora', 'Molinito', 57);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NB9990', 'Miguel Hidalgo', 'Universidad', 'Coapa', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JY2650', 'Gustavo A. Madero', 'Zacatepec', 'Coapa', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DZ2041', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 58);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZT9119', 'Azcapotzalco', 'Universidad', 'Coapa', 46);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ED4742', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 68);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CR5226', 'Miguel Hidalgo', 'Sonora', 'Molinito', 75);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JK2211', 'Coyoacan', 'Sonora', 'Rep. Brasil', 98);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OX8950', 'Miguel Hidalgo', 'Sonora', 'Coapa', 13);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BE2371', 'Benito Juarez', 'Sonora', 'Molinito', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BA5188', 'Miguel Hidalgo', 'Sonora', 'Molinito', 11);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QZ3110', 'Benito Juarez', 'Universidad', 'Coapa', 55);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MW9855', 'Miguel Hidalgo', 'Toreo', 'Coapa', 71);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OS7212', 'Benito Juarez', 'Sonora', 'Coapa', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RK5776', 'Azcapotzalco', 'Zacatepec', 'Molinito', 5);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LM6867', 'Miguel Hidalgo', 'Sonora', 'Coapa', 32);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZU4525', 'Cuauhtemoc', 'Ciudad Universitaria', 'Coapa', 73);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IY8672', 'Benito Juarez', 'Toreo', 'Molinito', 44);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AP9358', 'Miguel Hidalgo', 'Sonora', 'Coapa', 2);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('OK2316', 'Miguel Hidalgo', 'Sonora', 'Coapa', 40);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NH3070', 'Tlalpan', 'Sonora', 'Coapa', 28);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QI7127', 'Coyoacan', 'Zacatepec', 'Salto del Agua', 77);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GF7675', 'Cuauhtemoc', 'Toreo', 'Coapa', 61);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JP7057', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 30);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VW9614', 'Azcapotzalco', 'Zacatepec', 'Coapa', 61);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QJ0262', 'Tlalpan', 'Universidad', 'Coapa', 57);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NF1545', 'Cuauhtemoc', 'Sonora', 'Coapa', 85);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DV6811', 'Azcapotzalco', 'Sonora', 'Molinito', 58);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PP3833', 'Miguel Hidalgo', 'Toreo', 'Coapa', 91);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AW9087', 'Miguel Hidalgo', 'Sonora', 'Coapa', 46);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZX5287', 'Azcapotzalco', 'Toreo', 'Molinito', 47);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QC7784', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 43);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JS7670', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 83);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SE7426', 'Miguel Hidalgo', 'Sonora', 'Coapa', 41);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FB8043', 'Miguel Hidalgo', 'Sonora', 'Coapa', 17);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('GK6827', 'Miguel Hidalgo', 'Sonora', 'Coapa', 60);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('JW6530', 'Miguel Hidalgo', 'Insurgentes', 'Coapa', 84);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BV4948', 'Coyoacan', 'Universidad', 'Coapa', 54);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VO0827', 'Azcapotzalco', 'Sonora', 'Coapa', 6);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LG9699', 'Azcapotzalco', 'Sonora', 'Coapa', 49);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RR2687', 'Miguel Hidalgo', 'Universidad', 'Coapa', 91);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NV5830', 'Azcapotzalco', 'Sonora', 'Coapa', 23);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IZ1601', 'Miguel Hidalgo', 'Sonora', 'Coapa', 80);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FZ6404', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QV7179', 'Miguel Hidalgo', 'Universidad', 'Coapa', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QE9194', 'Miguel Hidalgo', 'Sonora', 'Coapa', 11);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AU8579', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 21);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('FA4292', 'Azcapotzalco', 'Universidad', 'Coapa', 48);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SV3770', 'Azcapotzalco', 'Toreo', 'Coapa', 63);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IT7712', 'Cuauhtemoc', 'Sonora', 'Coapa', 96);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BB5336', 'Miguel Hidalgo', 'Universidad', 'Coapa', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('TF9558', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZQ8481', 'Cuauhtemoc', 'Universidad', 'Molinito', 22);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZE0922', 'Gustavo A. Madero', 'Sonora', 'Coapa', 91);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BI5606', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 82);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MC3623', 'Miguel Hidalgo', 'Sonora', 'Molinito', 62);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LJ3541', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 88);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RB6409', 'Cuauhtemoc', 'Universidad', 'Coapa', 7);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WQ4134', 'Cuauhtemoc', 'Sonora', 'Molinito', 81);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('IK6418', 'Miguel Hidalgo', 'Universidad', 'Molinito', 33);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('RP6659', 'Cuauhtemoc', 'Toreo', 'Coapa', 98);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DJ0696', 'Miguel Hidalgo', 'Toreo', 'Coapa', 16);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZD0799', 'Cuauhtemoc', 'Sonora', 'Coapa', 39);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('AY2602', 'Cuauhtemoc', 'Toreo', 'Coapa', 13);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KE1626', 'Benito Juarez', 'Ciudad Universitaria', 'Coapa', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PB2305', 'Miguel Hidalgo', 'Universidad', 'Coapa', 42);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DZ0925', 'Azcapotzalco', 'Sonora', 'Coapa', 88);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BH1277', 'Azcapotzalco', 'Sonora', 'Coapa', 83);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QU0189', 'Cuauhtemoc', 'Universidad', 'Coapa', 10);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('DH2521', 'Cuauhtemoc', 'Garibaldi', 'Coapa', 28);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KI1825', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 28);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('HL4651', 'Azcapotzalco', 'Sonora', 'Coapa', 9);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('YR4550', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 37);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VZ5583', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 32);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QK8599', 'Miguel Hidalgo', 'Universidad', 'Coapa', 42);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LX5355', 'Miguel Hidalgo', 'Universidad', 'Coapa', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('KR4538', 'Azcapotzalco', 'Toreo', 'Coapa', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('WD2130', 'Miguel Hidalgo', 'Toreo', 'Rep. Brasil', 92);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('PQ2166', 'Azcapotzalco', 'Sonora', 'Molinito', 3);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ER2032', 'Benito Juarez', 'Sonora', 'Coapa', 3);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VJ9279', 'Miguel Hidalgo', 'Zacatepec', 'Salto del Agua', 25);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BF7374', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 15);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('BX7681', 'Gustavo A. Madero', 'Universidad', 'Rep. Brasil', 35);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('VX7151', 'Coyoacan', 'Sonora', 'Molinito', 30);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('QS0448', 'Cuauhtemoc', 'Toreo', 'Coapa', 90);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('NF8856', 'Benito Juarez', 'Toreo', 'Coapa', 61);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UB5833', 'Miguel Hidalgo', 'Sonora', 'Molinito', 64);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('MA1303', 'Miguel Hidalgo', 'Sonora', 'Coapa', 27);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZP3640', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 56);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UQ9934', 'Miguel Hidalgo', 'Sonora', 'Coapa', 100);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EX6403', 'Cuauhtemoc', 'Sonora', 'Coapa', 30);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('SA6109', 'Miguel Hidalgo', 'Universidad', 'Coapa', 94);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('LE7441', 'Azcapotzalco', 'Zacatepec', 'Molinito', 67);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('EV1724', 'Miguel Hidalgo', 'Sonora', 'Molinito', 55);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('ZW6273', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 53);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('CA7281', 'Miguel Hidalgo', 'Universidad', 'Molinito', 71);
insert into direccion (id_persona, delegacion, colonia, calle, lote) values ('UE8539', 'Miguel Hidalgo', 'Toreo', 'Coapa', 41);
