insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (10002, 'Tlahuac', 'Morelos', 'Centro', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (10468, 'Cuajimalpa', 'Tacubaya', 'Centro', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (10543, 'Tlahuac', 'Tacubaya', 'Centro', 83);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (10927, 'Xochimilco', 'Bondojito', 'Centro', 96);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (11041, 'Cuajimalpa', 'Morelos', 'Centro', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (11266, 'Azcapotzalco', 'Morelos', 'Centro', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (11339, 'Iztapalapa', 'Tacubaya', 'Centro', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (12327, 'Tlahuac', 'Romero Rubio', 'Centro', 24);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (12571, 'Xochimilco', 'Guerrero', 'Zapata', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (12666, 'Tlahuac', 'Tacubaya', 'Centro', 49);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (12866, 'Cuajimalpa', 'Tacubaya', 'Hidalgo', 64);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (13686, 'Tlahuac', 'Tacubaya', 'Hidalgo', 79);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (14261, 'Xochimilco', 'Tacubaya', 'Hidalgo', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (14748, 'Cuajimalpa', 'Bondojito', 'Centro', 69);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (14967, 'Cuajimalpa', 'Bondojito', 'Hidalgo', 67);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (16740, 'Tlahuac', 'Tacubaya', 'Centro', 81);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (16758, 'Iztacalco', 'Romero Rubio', 'Centro', 93);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (17331, 'Cuajimalpa', 'Tacubaya', 'Hidalgo', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (17386, 'Tlahuac', 'Tacubaya', 'Centro', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (17550, 'Iztapalapa', 'Bondojito', 'Centro', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (17866, 'Azcapotzalco', 'Morelos', 'Centro', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (17903, 'Tlahuac', 'Guerrero', 'Centro', 51);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (17924, 'Tlahuac', 'Bondojito', 'Hidalgo', 9);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (18176, 'Xochimilco', 'Tacubaya', 'Centro', 5);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (18218, 'Tlahuac', 'Tacubaya', 'Centro', 20);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (18276, 'Cuajimalpa', 'Tacubaya', 'Zapata', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (18447, 'Tlahuac', 'Tacubaya', 'Centro', 7);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (18660, 'Iztapalapa', 'Tacubaya', 'Hidalgo', 5);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (18683, 'Xochimilco', 'Tacubaya', 'Centro', 67);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (18720, 'Cuajimalpa', 'Tacubaya', 'Rep. Costa Rica', 48);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (20358, 'Cuajimalpa', 'Romero Rubio', 'Centro', 37);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (20624, 'Xochimilco', 'Bondojito', 'Centro', 16);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (20870, 'Tlahuac', 'Romero Rubio', 'Hidalgo', 77);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (22237, 'Xochimilco', 'Bondojito', 'Centro', 68);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (22400, 'Tlahuac', 'Tacubaya', 'Centro', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (23079, 'Tlahuac', 'Bondojito', 'Centro', 42);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (23160, 'Tlahuac', 'Tacubaya', 'Hidalgo', 69);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (24025, 'Xochimilco', 'Bondojito', 'Zapata', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (24893, 'Xochimilco', 'Tacubaya', 'Zapata', 79);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (25589, 'Tlahuac', 'Bondojito', 'Rep. Costa Rica', 40);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (25700, 'Tlahuac', 'Romero Rubio', 'Zapata', 57);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (25969, 'Cuajimalpa', 'Tacubaya', 'Centro', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (26052, 'Tlahuac', 'Tacubaya', 'Centro', 9);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (26929, 'Cuajimalpa', 'Tacubaya', 'Mixiuhca', 22);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (27679, 'Xochimilco', 'Bondojito', 'Centro', 5);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (29454, 'Tlahuac', 'Tacubaya', 'Zapata', 47);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (29539, 'Tlahuac', 'Bondojito', 'Centro', 53);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (29894, 'Tlahuac', 'Tacubaya', 'Centro', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (30211, 'Tlahuac', 'Tacubaya', 'Centro', 33);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (30678, 'Iztapalapa', 'Tacubaya', 'Centro', 99);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (30720, 'Iztacalco', 'Tacubaya', 'Centro', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (31348, 'Cuajimalpa', 'Tacubaya', 'Centro', 71);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (31408, 'Xochimilco', 'Tacubaya', 'Hidalgo', 44);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (31496, 'Tlahuac', 'Tacubaya', 'Centro', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (31886, 'Tlahuac', 'Morelos', 'Centro', 80);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (32011, 'Tlahuac', 'Guerrero', 'Hidalgo', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (32219, 'Xochimilco', 'Tacubaya', 'Hidalgo', 71);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (32354, 'Cuajimalpa', 'Tacubaya', 'Centro', 1);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (33005, 'Tlahuac', 'Tacubaya', 'Centro', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (33223, 'Tlahuac', 'Tacubaya', 'Calle 11', 74);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (33437, 'Xochimilco', 'Tacubaya', 'Hidalgo', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (33621, 'Tlahuac', 'Tacubaya', 'Zapata', 58);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (33784, 'Tlahuac', 'Tacubaya', 'Zapata', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (34185, 'Tlahuac', 'Tacubaya', 'Centro', 81);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (34632, 'Iztapalapa', 'Bondojito', 'Centro', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (35879, 'Tlahuac', 'Tacubaya', 'Hidalgo', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (36052, 'Tlahuac', 'Morelos', 'Hidalgo', 51);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (37875, 'Tlahuac', 'Bondojito', 'Centro', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (38209, 'Tlahuac', 'Bondojito', 'Hidalgo', 70);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (38384, 'Tlahuac', 'Morelos', 'Rep. Costa Rica', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (38704, 'Iztapalapa', 'Bondojito', 'Zapata', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (38738, 'Tlahuac', 'Tacubaya', 'Centro', 69);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (39196, 'Cuajimalpa', 'Tacubaya', 'Centro', 95);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (39362, 'Iztacalco', 'Tacubaya', 'Mixiuhca', 57);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (39715, 'Tlahuac', 'Romero Rubio', 'Centro', 42);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (39803, 'Tlahuac', 'Tacubaya', 'Centro', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (40446, 'Tlahuac', 'Tacubaya', 'Hidalgo', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (40596, 'Iztapalapa', 'Bondojito', 'Calle 11', 40);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (40604, 'Cuajimalpa', 'Romero Rubio', 'Hidalgo', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (40617, 'Iztacalco', 'Tacubaya', 'Zapata', 98);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (40621, 'Xochimilco', 'Tacubaya', 'Hidalgo', 24);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (40690, 'Xochimilco', 'Tacubaya', 'Zapata', 42);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (41662, 'Xochimilco', 'Bondojito', 'Rep. Costa Rica', 16);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (42384, 'Xochimilco', 'Guerrero', 'Centro', 99);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (43764, 'Xochimilco', 'Tacubaya', 'Zapata', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (43771, 'Cuajimalpa', 'Tacubaya', 'Centro', 35);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (44534, 'Xochimilco', 'Tacubaya', 'Mixiuhca', 12);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (46132, 'Xochimilco', 'Tacubaya', 'Centro', 62);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (47802, 'Iztapalapa', 'Tacubaya', 'Centro', 14);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (48197, 'Tlahuac', 'Tacubaya', 'Hidalgo', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (48468, 'Tlahuac', 'Tacubaya', 'Centro', 28);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (48594, 'Xochimilco', 'Morelos', 'Centro', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (48715, 'Tlahuac', 'Bondojito', 'Centro', 25);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (49160, 'Tlahuac', 'Romero Rubio', 'Centro', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (49266, 'Cuajimalpa', 'Tacubaya', 'Calle 11', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (49333, 'Tlahuac', 'Tacubaya', 'Hidalgo', 61);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (50550, 'Tlahuac', 'Tacubaya', 'Centro', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (50677, 'Xochimilco', 'Bondojito', 'Hidalgo', 18);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (50744, 'Cuajimalpa', 'Tacubaya', 'Centro', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (51498, 'Cuajimalpa', 'Tacubaya', 'Centro', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (51731, 'Cuajimalpa', 'Tacubaya', 'Zapata', 20);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (52175, 'Tlahuac', 'Bondojito', 'Mixiuhca', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (52571, 'Tlahuac', 'Romero Rubio', 'Centro', 1);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (53054, 'Tlahuac', 'Tacubaya', 'Centro', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (54094, 'Xochimilco', 'Tacubaya', 'Centro', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (54438, 'Azcapotzalco', 'Bondojito', 'Centro', 86);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (54733, 'Xochimilco', 'Guerrero', 'Hidalgo', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (56204, 'Tlahuac', 'Tacubaya', 'Hidalgo', 75);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (56680, 'Tlahuac', 'Tacubaya', 'Centro', 100);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (57254, 'Tlahuac', 'Tacubaya', 'Zapata', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (57316, 'Cuajimalpa', 'Bondojito', 'Centro', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (58134, 'Tlahuac', 'Bondojito', 'Centro', 22);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (58816, 'Tlahuac', 'Tacubaya', 'Centro', 39);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (58914, 'Xochimilco', 'Guerrero', 'Hidalgo', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (58934, 'Cuajimalpa', 'Morelos', 'Mixiuhca', 73);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (58966, 'Iztapalapa', 'Bondojito', 'Zapata', 12);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (59215, 'Cuajimalpa', 'Tacubaya', 'Hidalgo', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (59337, 'Tlahuac', 'Tacubaya', 'Centro', 20);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (59340, 'Tlahuac', 'Bondojito', 'Centro', 64);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (59637, 'Tlahuac', 'Guerrero', 'Mixiuhca', 88);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (60829, 'Tlahuac', 'Tacubaya', 'Hidalgo', 87);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (60886, 'Tlahuac', 'Bondojito', 'Mixiuhca', 91);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (60949, 'Tlahuac', 'Tacubaya', 'Zapata', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (60958, 'Tlahuac', 'Bondojito', 'Centro', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (61951, 'Tlahuac', 'Bondojito', 'Centro', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (62548, 'Xochimilco', 'Bondojito', 'Hidalgo', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (62646, 'Tlahuac', 'Bondojito', 'Zapata', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (63211, 'Xochimilco', 'Tacubaya', 'Zapata', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (63687, 'Tlahuac', 'Bondojito', 'Centro', 35);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (63970, 'Tlahuac', 'Bondojito', 'Centro', 56);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (64262, 'Tlahuac', 'Bondojito', 'Mixiuhca', 47);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (66024, 'Tlahuac', 'Morelos', 'Centro', 98);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (67468, 'Cuajimalpa', 'Bondojito', 'Zapata', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (68132, 'Xochimilco', 'Tacubaya', 'Centro', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (68198, 'Xochimilco', 'Tacubaya', 'Hidalgo', 24);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (69448, 'Tlahuac', 'Morelos', 'Centro', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (69805, 'Tlahuac', 'Tacubaya', 'Centro', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (69822, 'Tlahuac', 'Romero Rubio', 'Centro', 40);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (70102, 'Iztacalco', 'Tacubaya', 'Centro', 83);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (70672, 'Tlahuac', 'Tacubaya', 'Centro', 71);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (70912, 'Xochimilco', 'Tacubaya', 'Centro', 47);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (72910, 'Cuajimalpa', 'Tacubaya', 'Hidalgo', 61);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (73187, 'Xochimilco', 'Tacubaya', 'Centro', 53);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (73591, 'Tlahuac', 'Tacubaya', 'Hidalgo', 88);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (74189, 'Tlahuac', 'Bondojito', 'Hidalgo', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (74460, 'Tlahuac', 'Tacubaya', 'Centro', 1);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (74522, 'Iztapalapa', 'Morelos', 'Centro', 62);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (74998, 'Tlahuac', 'Bondojito', 'Hidalgo', 99);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (75075, 'Tlahuac', 'Bondojito', 'Centro', 70);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (75428, 'Cuajimalpa', 'Guerrero', 'Centro', 20);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (75430, 'Tlahuac', 'Tacubaya', 'Rep. Costa Rica', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (75588, 'Tlahuac', 'Guerrero', 'Centro', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (76422, 'Tlahuac', 'Tacubaya', 'Zapata', 26);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (76487, 'Tlahuac', 'Tacubaya', 'Centro', 11);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (78131, 'Xochimilco', 'Bondojito', 'Rep. Costa Rica', 96);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (78154, 'Tlahuac', 'Tacubaya', 'Centro', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (78522, 'Xochimilco', 'Tacubaya', 'Centro', 40);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (79003, 'Cuajimalpa', 'Tacubaya', 'Centro', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (79360, 'Tlahuac', 'Tacubaya', 'Centro', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (79386, 'Xochimilco', 'Tacubaya', 'Centro', 48);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (79439, 'Azcapotzalco', 'Tacubaya', 'Mixiuhca', 57);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (79891, 'Tlahuac', 'Tacubaya', 'Zapata', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (80698, 'Tlahuac', 'Tacubaya', 'Centro', 99);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (80970, 'Tlahuac', 'Tacubaya', 'Centro', 78);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (81167, 'Tlahuac', 'Morelos', 'Centro', 42);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (81392, 'Iztapalapa', 'Tacubaya', 'Centro', 61);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (81523, 'Tlahuac', 'Bondojito', 'Zapata', 14);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (81920, 'Xochimilco', 'Romero Rubio', 'Hidalgo', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (81963, 'Cuajimalpa', 'Romero Rubio', 'Centro', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (82246, 'Xochimilco', 'Tacubaya', 'Centro', 12);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (82687, 'Xochimilco', 'Bondojito', 'Centro', 47);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (83690, 'Tlahuac', 'Guerrero', 'Zapata', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (84021, 'Tlahuac', 'Bondojito', 'Centro', 10);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (84487, 'Tlahuac', 'Tacubaya', 'Hidalgo', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (84614, 'Tlahuac', 'Tacubaya', 'Hidalgo', 82);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (85369, 'Xochimilco', 'Guerrero', 'Centro', 98);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (86158, 'Tlahuac', 'Romero Rubio', 'Hidalgo', 90);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (86349, 'Tlahuac', 'Tacubaya', 'Calle 11', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (87594, 'Iztacalco', 'Tacubaya', 'Hidalgo', 12);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (87775, 'Iztacalco', 'Tacubaya', 'Mixiuhca', 96);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (88987, 'Xochimilco', 'Bondojito', 'Zapata', 80);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (89609, 'Xochimilco', 'Tacubaya', 'Centro', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (90057, 'Tlahuac', 'Tacubaya', 'Centro', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (90630, 'Xochimilco', 'Guerrero', 'Centro', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (90909, 'Tlahuac', 'Tacubaya', 'Hidalgo', 5);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (91488, 'Tlahuac', 'Bondojito', 'Hidalgo', 90);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (92665, 'Tlahuac', 'Romero Rubio', 'Hidalgo', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (92973, 'Tlahuac', 'Tacubaya', 'Hidalgo', 74);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (93139, 'Tlahuac', 'Romero Rubio', 'Hidalgo', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (93586, 'Cuajimalpa', 'Bondojito', 'Centro', 93);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (94382, 'Tlahuac', 'Tacubaya', 'Zapata', 20);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (95064, 'Tlahuac', 'Tacubaya', 'Centro', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (95591, 'Xochimilco', 'Romero Rubio', 'Hidalgo', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (96113, 'Tlahuac', 'Tacubaya', 'Hidalgo', 5);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (96892, 'Xochimilco', 'Tacubaya', 'Centro', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (97725, 'Xochimilco', 'Bondojito', 'Centro', 100);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (97727, 'Cuajimalpa', 'Tacubaya', 'Centro', 67);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (97799, 'Iztapalapa', 'Tacubaya', 'Hidalgo', 8);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (99026, 'Iztacalco', 'Tacubaya', 'Centro', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (99071, 'Tlahuac', 'Bondojito', 'Zapata', 75);
