insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('72334593661', 'Magdalena Contreras', 'Rep. Brasil', 'Santa Rosa', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('84206428364', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('05497896858', 'Xochimilco', 'Nopalera', 'San Mateo', 30);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('90374627806', 'Magdalena Contreras', 'Polanco', 'San Bartolo', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('04699858166', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('38062030460', 'Magdalena Contreras', 'Nopalera', 'Universidad', 39);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49242196111', 'Xochimilco', 'Insurgentes', 'San Bartolo', 68);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('38110150167', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('83478290790', 'Iztacalco', 'Nopalera', 'Santa Rosa', 6);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('87224059816', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 69);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('79747881121', 'Xochimilco', 'Nopalera', 'San Bartolo', 76);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('83080008156', 'Tlahuac', 'Polanco', 'Santa Rosa', 29);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('65099994612', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 81);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('91758137826', 'Iztapalapa', 'Nopalera', 'San Bartolo', 91);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('34247780457', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 96);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('51523065165', 'Milpa Alta', 'Zapata', 'Santa Rosa', 88);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('65062645939', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 73);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('60928501881', 'Iztacalco', 'Insurgentes', 'Santa Rosa', 11);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('85656795549', 'Magdalena Contreras', 'Polanco', 'San Mateo', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('14407402673', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 64);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('18983698502', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 4);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('03208206603', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 41);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('90934333207', 'Xochimilco', 'Nopalera', 'Santa Rosa', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('29500970544', 'Milpa Alta', 'Polanco', 'San Mateo', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('45508020707', 'Milpa Alta', 'Polanco', 'Santa Rosa', 77);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('04101596299', 'Xochimilco', 'Insurgentes', 'Santa Rosa', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('56688711598', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 53);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('85473075020', 'Milpa Alta', 'Polanco', 'San Bartolo', 64);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('36377130444', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('14330829889', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 53);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('18932588772', 'Tlahuac', 'Insurgentes', 'Santa Rosa', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('65089877986', 'Iztapalapa', 'Insurgentes', 'San Bartolo', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49456280594', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('79213853104', 'Magdalena Contreras', 'Nopalera', 'Odontologia', 13);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('58876883343', 'Iztacalco', 'Insurgentes', 'Santa Rosa', 94);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('73068878939', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 8);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('98846062480', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 88);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('90580545681', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 12);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('05895912146', 'Magdalena Contreras', 'Nopalera', 'Ecatepec', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('73658515946', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('78863810085', 'Magdalena Contreras', 'Insurgentes', 'San Bartolo', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('18148708963', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 16);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('07362096123', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('74654872803', 'Iztacalco', 'Polanco', 'Santa Rosa', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('67914182079', 'Magdalena Contreras', 'Polanco', 'Santa Rosa', 70);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('61748634354', 'Magdalena Contreras', 'Nopalera', 'Tlanenplantla', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('96866123371', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('96730057710', 'Magdalena Contreras', 'Polanco', 'Santa Rosa', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('93700554152', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 71);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('03225669321', 'Tlahuac', 'Nopalera', 'San Bartolo', 47);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('44351960179', 'Magdalena Contreras', 'Insurgentes', 'San Bartolo', 28);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('90306129939', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('79575482278', 'Milpa Alta', 'Nopalera', 'Universidad', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('29804532639', 'Magdalena Contreras', 'Polanco', 'Santa Rosa', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('09657955086', 'Tlahuac', 'Nopalera', 'Odontologia', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('28186613654', 'Milpa Alta', 'Nopalera', 'San Bartolo', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('27098467340', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 48);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('44863145330', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 70);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('87098096200', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 20);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('56049111723', 'Magdalena Contreras', 'Insurgentes', 'San Bartolo', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('41279509048', 'Magdalena Contreras', 'Nopalera', 'Odontologia', 86);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('69276638474', 'Milpa Alta', 'Nopalera', 'Odontologia', 30);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('69368932970', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('16847234688', 'Milpa Alta', 'Insurgentes', 'San Bartolo', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('02811812073', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 7);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('42444195136', 'Xochimilco', 'Doctores', 'San Mateo', 39);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('23452016092', 'Iztacalco', 'Nopalera', 'Odontologia', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('96090859863', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 21);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('21154407683', 'Iztacalco', 'Nopalera', 'San Mateo', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('44850173639', 'Magdalena Contreras', 'Polanco', 'Santa Rosa', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('24658895692', 'Magdalena Contreras', 'Polanco', 'Santa Rosa', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('80306919090', 'Xochimilco', 'Nopalera', 'San Bartolo', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('92803281229', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('87378938067', 'Xochimilco', 'Polanco', 'San Bartolo', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('12039039957', 'Iztapalapa', 'Insurgentes', 'Odontologia', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('52004936957', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 87);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('29507395640', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 51);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('60471546092', 'Milpa Alta', 'Insurgentes', 'San Mateo', 51);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('00111593161', 'Magdalena Contreras', 'Zapata', 'San Bartolo', 83);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49890034193', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 21);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('54193343259', 'Milpa Alta', 'Nopalera', 'San Bartolo', 77);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('40221385009', 'Milpa Alta', 'Nopalera', 'San Bartolo', 80);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('62850754288', 'Iztapalapa', 'Insurgentes', 'San Bartolo', 8);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('74918019551', 'Milpa Alta', 'Insurgentes', 'San Bartolo', 82);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49745142908', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 87);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('44120744682', 'Xochimilco', 'Doctores', 'Ecatepec', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('28107321613', 'Xochimilco', 'Nopalera', 'Santa Rosa', 12);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('70625939702', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 55);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('59465289571', 'Magdalena Contreras', 'Doctores', 'San Mateo', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('72281773785', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 56);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('36368386469', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('32512572533', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('17804317932', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('59183216528', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('30126291211', 'Magdalena Contreras', 'Zapata', 'Universidad', 73);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('28840174892', 'Milpa Alta', 'Insurgentes', 'San Mateo', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49208723421', 'Magdalena Contreras', 'Polanco', 'Odontologia', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('93251880130', 'Magdalena Contreras', 'Insurgentes', 'Odontologia', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('76398869968', 'Cuauhtemoc', 'Polanco', 'San Mateo', 48);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('07007326519', 'Milpa Alta', 'Insurgentes', 'Santa Rosa', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('20046601299', 'Xochimilco', 'Zapata', 'Santa Rosa', 77);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('13420533061', 'Xochimilco', 'Insurgentes', 'San Mateo', 28);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('74129425747', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 67);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('20805759273', 'Magdalena Contreras', 'Polanco', 'Santa Rosa', 35);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('87471683905', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 90);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('48859457270', 'Magdalena Contreras', 'Nopalera', 'Ecatepec', 67);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('51488787285', 'Milpa Alta', 'Polanco', 'San Bartolo', 61);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('43856511180', 'Magdalena Contreras', 'Polanco', 'San Mateo', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('40254524167', 'Magdalena Contreras', 'Insurgentes', 'San Bartolo', 49);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('13583332222', 'Xochimilco', 'Nopalera', 'Santa Rosa', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('18916547087', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 92);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('12331792853', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 93);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('24798711286', 'Magdalena Contreras', 'Zapata', 'Santa Rosa', 81);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('88185410054', 'Milpa Alta', 'Zapata', 'Santa Rosa', 100);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('09760955869', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('39573103585', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('39657469334', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('26598733786', 'Xochimilco', 'Nopalera', 'Santa Rosa', 37);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('94895605862', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 69);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49042800756', 'Xochimilco', 'Polanco', 'Santa Rosa', 44);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('82903579878', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 53);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('35949381582', 'Tlahuac', 'Nopalera', 'San Bartolo', 41);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('39583451505', 'Iztapalapa', 'Nopalera', 'Santa Rosa', 99);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('29997581117', 'Milpa Alta', 'Insurgentes', 'San Bartolo', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('72334843689', 'Iztacalco', 'Agricola Oriental', 'San Bartolo', 48);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('27215625409', 'Xochimilco', 'Nopalera', 'Santa Rosa', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('81141800499', 'Magdalena Contreras', 'Rep. Brasil', 'Universidad', 33);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('73630576125', 'Milpa Alta', 'Insurgentes', 'Santa Rosa', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('71818457062', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('07741183175', 'Magdalena Contreras', 'Zapata', 'San Mateo', 72);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('24619129140', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 48);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('00652321275', 'Magdalena Contreras', 'Nopalera', 'Universidad', 18);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('18730865669', 'Xochimilco', 'Nopalera', 'Santa Rosa', 77);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('13420274139', 'Milpa Alta', 'Zapata', 'Santa Rosa', 73);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('39693809913', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('28443779778', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 95);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('09163996110', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 80);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('19069263324', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 26);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('79393222887', 'Magdalena Contreras', 'Nopalera', 'San Mateo', 95);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49401422424', 'Milpa Alta', 'Nopalera', 'San Bartolo', 61);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('45158893360', 'Magdalena Contreras', 'Insurgentes', 'San Mateo', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('39220110880', 'Milpa Alta', 'Doctores', 'Santa Rosa', 57);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('18953234301', 'Magdalena Contreras', 'Zapata', 'Tlanenplantla', 39);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('35536487100', 'Iztacalco', 'Polanco', 'San Mateo', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('24539456011', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 18);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('79491286584', 'Milpa Alta', 'Nopalera', 'San Mateo', 7);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('38732402729', 'Iztacalco', 'Nopalera', 'Santa Rosa', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('60204095688', 'Magdalena Contreras', 'Polanco', 'Santa Rosa', 87);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('90639919856', 'Xochimilco', 'Nopalera', 'San Bartolo', 53);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('30167757980', 'Magdalena Contreras', 'Zapata', 'Santa Rosa', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('70985106616', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('59381264261', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 26);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('31137238901', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 78);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('00194873611', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 56);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('80296257580', 'Magdalena Contreras', 'Nopalera', 'San Bartolo', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('13303367953', 'Magdalena Contreras', 'Insurgentes', 'San Mateo', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('58089498142', 'Milpa Alta', 'Polanco', 'Santa Rosa', 1);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('99498702835', 'Milpa Alta', 'Nopalera', 'San Bartolo', 98);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('55350362763', 'Xochimilco', 'Insurgentes', 'San Bartolo', 80);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('14457485481', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 68);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('98742254552', 'Magdalena Contreras', 'Insurgentes', 'San Mateo', 86);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('22505243149', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('01784496981', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 32);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('15348282704', 'Milpa Alta', 'Nopalera', 'San Mateo', 35);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('52798428539', 'Xochimilco', 'Zapata', 'Santa Rosa', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('49606585295', 'Xochimilco', 'Nopalera', 'Santa Rosa', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('72530103865', 'Magdalena Contreras', 'Agricola Oriental', 'Santa Rosa', 22);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('93110309133', 'Magdalena Contreras', 'Polanco', 'San Bartolo', 95);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('56228782696', 'Magdalena Contreras', 'Insurgentes', 'Santa Rosa', 55);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('35019550850', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('95129511857', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 13);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('60773246612', 'Milpa Alta', 'Nopalera', 'San Bartolo', 41);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('00979825392', 'Magdalena Contreras', 'Insurgentes', 'Universidad', 95);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('61978871630', 'Magdalena Contreras', 'Insurgentes', 'San Mateo', 30);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('84173676448', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('70780504444', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 75);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('13200598528', 'Magdalena Contreras', 'Polanco', 'Odontologia', 100);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('12572752634', 'Xochimilco', 'Insurgentes', 'Santa Rosa', 91);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('73613840338', 'Magdalena Contreras', 'Polanco', 'San Mateo', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('43544823776', 'Xochimilco', 'Nopalera', 'Santa Rosa', 86);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('08416955291', 'Xochimilco', 'Insurgentes', 'San Bartolo', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('30144804597', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 5);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('39425874300', 'Magdalena Contreras', 'Rep. Brasil', 'Santa Rosa', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('26820791521', 'Milpa Alta', 'Zapata', 'Santa Rosa', 37);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('48082891478', 'Xochimilco', 'Insurgentes', 'Santa Rosa', 5);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('05826152463', 'Milpa Alta', 'Insurgentes', 'Santa Rosa', 42);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('25649778483', 'Magdalena Contreras', 'Insurgentes', 'San Bartolo', 16);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('63470420681', 'Milpa Alta', 'Nopalera', 'Odontologia', 95);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('61340473673', 'Magdalena Contreras', 'Doctores', 'Santa Rosa', 4);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('86434718995', 'Magdalena Contreras', 'Nopalera', 'Ecatepec', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('30387015802', 'Milpa Alta', 'Nopalera', 'Santa Rosa', 73);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('75579141413', 'Magdalena Contreras', 'Insurgentes', 'San Bartolo', 78);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('54970819284', 'Milpa Alta', 'Polanco', 'Santa Rosa', 26);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('92033385192', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 1);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('62781263722', 'Iztapalapa', 'Insurgentes', 'Santa Rosa', 91);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('98374959389', 'Milpa Alta', 'Insurgentes', 'San Mateo', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('52858894702', 'Magdalena Contreras', 'Nopalera', 'Santa Rosa', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('72394618318', 'Milpa Alta', 'Insurgentes', 'San Mateo', 62);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('12972013725', 'Magdalena Contreras', 'Nopalera', 'Odontologia', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values ('75642805907', 'Iztapalapa', 'Insurgentes', 'San Bartolo', 53);
