insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 42);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Escruadron', 82);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Romero Rubio', 'Escandon', 73);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Escandon', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 55);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Tepito', 'Rep. Brasil', 70);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Merced', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Escandon', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztapalapa', 'Navarte', 'Escandon', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Morelos', 'Merced', 92);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escandon', 86);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Tepito', 'Escruadron', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escruadron', 41);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Tepito', 'Merced', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 91);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Rep. Brasil', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Merced', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Morelos', 'Escandon', 93);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escruadron', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztapalapa', 'Morelos', 'Escandon', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 55);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Escruadron', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Merced', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Merced', 11);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Minnesota', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Merced', 71);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Tepito', 'Merced', 21);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Rep. Brasil', 81);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Rep. Brasil', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escandon', 80);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 33);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztapalapa', 'Navarte', 'Merced', 73);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Navarte', 'Merced', 88);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Guerrero', 'Merced', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escruadron', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 35);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Escruadron', 88);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Escandon', 40);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Merced', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Escandon', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Morelos', 'Merced', 76);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Rep. Brasil', 44);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztapalapa', 'Navarte', 'Escandon', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Tlalpan', 'Navarte', 'Merced', 66);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Morelos', 'Rep. Brasil', 14);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 44);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Romero Rubio', 'Escandon', 47);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escandon', 62);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escruadron', 92);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escruadron', 23);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Tlalpan', 'Romero Rubio', 'Merced', 40);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escruadron', 92);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escruadron', 29);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Morelos', 'Escruadron', 20);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 75);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escruadron', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Escandon', 75);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escruadron', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Romero Rubio', 'Escandon', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Romero Rubio', 'Merced', 68);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Rep. Brasil', 29);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 33);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Navarte', 'Escandon', 37);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 44);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 22);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 94);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Merced', 44);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Coyoacan', 'Navarte', 'Merced', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Escandon', 30);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escruadron', 48);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Romero Rubio', 'Merced', 33);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Romero Rubio', 'Escruadron', 90);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Merced', 78);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Morelos', 'Merced', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Tepito', 'Escandon', 90);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Escruadron', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 7);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 43);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escruadron', 72);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Tepito', 'Merced', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 7);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Tepito', 'Merced', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escandon', 33);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Escandon', 8);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Romero Rubio', 'Escruadron', 87);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 98);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Navarte', 'Escandon', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escandon', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 94);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Merced', 78);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztapalapa', 'Guerrero', 'Merced', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Merced', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escruadron', 25);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Escandon', 68);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Rep. Brasil', 45);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Minnesota', 70);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Escandon', 30);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Escandon', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Tepito', 'Merced', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Tlalpan', 'Navarte', 'Merced', 9);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Merced', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 65);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztapalapa', 'Romero Rubio', 'Escandon', 49);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Romero Rubio', 'Escruadron', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Romero Rubio', 'Escandon', 57);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 63);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Merced', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztapalapa', 'Navarte', 'Merced', 78);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Rep. Brasil', 78);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Morelos', 'Merced', 74);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Merced', 53);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Merced', 86);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escruadron', 12);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Navarte', 'Merced', 55);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Escandon', 75);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Guerrero', 'Merced', 68);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 59);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Merced', 8);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Merced', 84);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Tepito', 'Minnesota', 57);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 82);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Tlalpan', 'Navarte', 'Merced', 96);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Merced', 51);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 16);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Merced', 88);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztapalapa', 'Romero Rubio', 'Escandon', 3);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Coyoacan', 'Tepito', 'Escandon', 17);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Tlalpan', 'Morelos', 'Escandon', 7);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Merced', 92);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escandon', 70);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Escandon', 79);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Tepito', 'Escruadron', 30);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztapalapa', 'Romero Rubio', 'Escruadron', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escandon', 71);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Merced', 94);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 15);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Romero Rubio', 'Minnesota', 52);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 90);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztacalco', 'Navarte', 'Merced', 54);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Calle 10', 31);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Coyoacan', 'Navarte', 'Merced', 58);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Escandon', 67);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Romero Rubio', 'Merced', 61);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 60);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Escandon', 46);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Merced', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 87);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztapalapa', 'Tepito', 'Calle 10', 10);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escruadron', 39);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 36);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Guerrero', 'Merced', 28);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Guerrero', 'Merced', 11);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escruadron', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escruadron', 85);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Minnesota', 61);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztapalapa', 'Navarte', 'Merced', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Escandon', 92);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Escruadron', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Escruadron', 2);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 19);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Iztapalapa', 'Navarte', 'Merced', 77);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Tlalpan', 'Romero Rubio', 'Escandon', 37);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Azcapotzalco', 'Navarte', 'Escruadron', 72);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Merced', 64);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Romero Rubio', 'Merced', 33);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Morelos', 'Merced', 40);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Tepito', 'Merced', 74);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Escandon', 99);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Merced', 24);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 30);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Navarte', 'Escruadron', 18);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Merced', 97);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Guerrero', 'Merced', 34);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztacalco', 'Navarte', 'Merced', 29);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escruadron', 58);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Escandon', 50);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Milpa Alta', 'Navarte', 'Merced', 90);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Romero Rubio', 'Merced', 89);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 98);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Azcapotzalco', 'Romero Rubio', 'Merced', 24);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (1000000, 'Iztapalapa', 'Tepito', 'Merced', 38);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Tepito', 'Merced', 27);
insert into direccion_infraccion (num_infraccion, delegacion, colonia, calle, lote) values (999999, 'Milpa Alta', 'Navarte', 'Merced', 34);
