insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('30659', 'Azcapotzalco', 'Toreo', 'Rep. Costa Rica', 83);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('21319', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('29087', 'Benito Juarez', 'Sonora', 'Coapa', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('50806', 'Cuauhtemoc', 'Sonora', 'Coapa', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('26296', 'Miguel Hidalgo', 'Sonora', 'Coapa', 15);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('56032', 'Miguel Hidalgo', 'Sonora', 'Coapa', 7);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('38573', 'Miguel Hidalgo', 'Universidad', 'Molinito', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('72169', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Rep. Costa Rica', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('35821', 'Miguel Hidalgo', 'Sonora', 'Coapa', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('53834', 'Azcapotzalco', 'Sonora', 'Molinito', 74);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('72751', 'Cuauhtemoc', 'Universidad', 'Salto del Agua', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05596', 'Miguel Hidalgo', 'Universidad', 'Coapa', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('50855', 'Cuauhtemoc', 'Universidad', 'Molinito', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('36862', 'Miguel Hidalgo', 'Sonora', 'Coapa', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('51239', 'Azcapotzalco', 'Sonora', 'Coapa', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('34976', 'Miguel Hidalgo', 'Sonora', 'Coapa', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('42853', 'Miguel Hidalgo', 'Sonora', 'Coapa', 31);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('49964', 'Cuauhtemoc', 'Universidad', 'Coapa', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05813', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('84029', 'Miguel Hidalgo', 'Universidad', 'Coapa', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02680', 'Azcapotzalco', 'Sonora', 'Coapa', 41);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('75629', 'Cuauhtemoc', 'Universidad', 'Rep. Brasil', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('07557', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('86537', 'Tlalpan', 'Sonora', 'Rep. Brasil', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20228', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55422', 'Benito Juarez', 'Toreo', 'Doctor Vertiz', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05999', 'Cuauhtemoc', 'Universidad', 'Coapa', 51);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('96888', 'Benito Juarez', 'Sonora', 'Coapa', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('40715', 'Azcapotzalco', 'Universidad', 'Molinito', 51);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05841', 'Miguel Hidalgo', 'Sonora', 'Molinito', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83453', 'Miguel Hidalgo', 'Sonora', 'Coapa', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('73961', 'Azcapotzalco', 'Toreo', 'Rep. Brasil', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76854', 'Cuauhtemoc', 'Sonora', 'Molinito', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63866', 'Tlalpan', 'Universidad', 'Rep. Brasil', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('22732', 'Azcapotzalco', 'Sonora', 'Rep. Brasil', 67);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('41788', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03737', 'Azcapotzalco', 'Sonora', 'Coapa', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('66923', 'Miguel Hidalgo', 'Toreo', 'Coapa', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('48807', 'Miguel Hidalgo', 'Sonora', 'Coapa', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('51857', 'Cuauhtemoc', 'Sonora', 'Coapa', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('23058', 'Cuauhtemoc', 'Universidad', 'Coapa', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20507', 'Miguel Hidalgo', 'Universidad', 'Coapa', 64);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('18233', 'Miguel Hidalgo', 'Universidad', 'Coapa', 14);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('96307', 'Benito Juarez', 'Sonora', 'Rep. Costa Rica', 89);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('64783', 'Miguel Hidalgo', 'Sonora', 'Doctor Vertiz', 65);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('24926', 'Benito Juarez', 'Universidad', 'Coapa', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('11235', 'Miguel Hidalgo', 'Universidad', 'Coapa', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('01309', 'Miguel Hidalgo', 'Sonora', 'Coapa', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('94782', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('40338', 'Azcapotzalco', 'Zacatepec', 'Coapa', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('18778', 'Cuauhtemoc', 'Universidad', 'Coapa', 26);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('46649', 'Miguel Hidalgo', 'Universidad', 'Coapa', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('48673', 'Miguel Hidalgo', 'Sonora', 'Doctor Vertiz', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02477', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('67055', 'Coyoacan', 'Sonora', 'Coapa', 64);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('50487', 'Miguel Hidalgo', 'Sonora', 'Coapa', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20426', 'Miguel Hidalgo', 'Sonora', 'Coapa', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('59055', 'Miguel Hidalgo', 'Universidad', 'Odontologia', 44);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('66490', 'Cuauhtemoc', 'Ciudad Universitaria', 'Coapa', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('32046', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('98180', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('00333', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 49);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('31506', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('42759', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 26);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63579', 'Miguel Hidalgo', 'Sonora', 'Coapa', 92);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('71591', 'Miguel Hidalgo', 'Sonora', 'Molinito', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('24649', 'Miguel Hidalgo', 'Universidad', 'Molinito', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('14084', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('91488', 'Miguel Hidalgo', 'Universidad', 'Coapa', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83826', 'Azcapotzalco', 'Sonora', 'Coapa', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('31504', 'Miguel Hidalgo', 'Sonora', 'Coapa', 41);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('16505', 'Miguel Hidalgo', 'Toreo', 'Molinito', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('86194', 'Azcapotzalco', 'Universidad', 'Molinito', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('40904', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('97156', 'Azcapotzalco', 'Sonora', 'Molinito', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02306', 'Azcapotzalco', 'Sonora', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('80809', 'Azcapotzalco', 'Sonora', 'Coapa', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('38567', 'Miguel Hidalgo', 'Sonora', 'Molinito', 70);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('00724', 'Miguel Hidalgo', 'Sonora', 'Molinito', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05645', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 67);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('65957', 'Coyoacan', 'Sonora', 'Coapa', 72);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('43316', 'Miguel Hidalgo', 'Universidad', 'Coapa', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('28034', 'Miguel Hidalgo', 'Sonora', 'Coapa', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('07549', 'Coyoacan', 'Universidad', 'Coapa', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('13212', 'Miguel Hidalgo', 'Toreo', 'Molinito', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('85195', 'Cuauhtemoc', 'Universidad', 'Molinito', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('61721', 'Miguel Hidalgo', 'Roma', 'Coapa', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02221', 'Azcapotzalco', 'Sonora', 'Molinito', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('15493', 'Benito Juarez', 'Universidad', 'Coapa', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('22488', 'Miguel Hidalgo', 'Sonora', 'Coapa', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('72517', 'Miguel Hidalgo', 'Sonora', 'Molinito', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('74435', 'Azcapotzalco', 'Universidad', 'Coapa', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('73272', 'Miguel Hidalgo', 'Universidad', 'Molinito', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('82060', 'Azcapotzalco', 'Universidad', 'Coapa', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('88147', 'Benito Juarez', 'Coapa', 'Coapa', 37);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('71132', 'Miguel Hidalgo', 'Sonora', 'Molinito', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('08943', 'Miguel Hidalgo', 'Toreo', 'Coapa', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('77047', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('74424', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 14);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('97356', 'Azcapotzalco', 'Sonora', 'Coapa', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('88905', 'Magdalena Contreras', 'Sonora', 'Coapa', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('60875', 'Azcapotzalco', 'Universidad', 'Molinito', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('32347', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('87488', 'Cuauhtemoc', 'Universidad', 'Molinito', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('67500', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 72);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('49965', 'Azcapotzalco', 'Sonora', 'Coapa', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('47404', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 82);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('82080', 'Azcapotzalco', 'Sonora', 'Molinito', 42);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('69919', 'Cuauhtemoc', 'Sonora', 'Coapa', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('68565', 'Coyoacan', 'Universidad', 'Molinito', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('13982', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('84198', 'Azcapotzalco', 'Sonora', 'Coapa', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('97788', 'Miguel Hidalgo', 'Universidad', 'Coapa', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('66009', 'Miguel Hidalgo', 'Universidad', 'Molinito', 72);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('10016', 'Miguel Hidalgo', 'Sonora', 'Molinito', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63430', 'Miguel Hidalgo', 'Universidad', 'Coapa', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37430', 'Benito Juarez', 'Universidad', 'Rep. Brasil', 83);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('64738', 'Miguel Hidalgo', 'Universidad', 'Coapa', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('25112', 'Azcapotzalco', 'Universidad', 'Coapa', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('40336', 'Miguel Hidalgo', 'Toreo', 'Coapa', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63627', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('29273', 'Coyoacan', 'Universidad', 'Molinito', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('32438', 'Miguel Hidalgo', 'Universidad', 'Coapa', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79028', 'Azcapotzalco', 'Universidad', 'Coapa', 19);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('01761', 'Miguel Hidalgo', 'Sonora', 'Coapa', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('92027', 'Miguel Hidalgo', 'Sonora', 'Coapa', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('91327', 'Cuauhtemoc', 'Universidad', 'Rep. Brasil', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('04957', 'Miguel Hidalgo', 'Toreo', 'Molinito', 44);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('90002', 'Azcapotzalco', 'Toreo', 'Salto del Agua', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('69447', 'Miguel Hidalgo', 'Sonora', 'Molinito', 86);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20948', 'Azcapotzalco', 'Zacatepec', 'Coapa', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('81154', 'Azcapotzalco', 'Toreo', 'Coapa', 51);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('74749', 'Azcapotzalco', 'Universidad', 'Coapa', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('40042', 'Miguel Hidalgo', 'Sonora', 'Molinito', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76859', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('41528', 'Azcapotzalco', 'Universidad', 'Molinito', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('85224', 'Miguel Hidalgo', 'Sonora', 'Coapa', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('18628', 'Coyoacan', 'Sonora', 'Coapa', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('88507', 'Miguel Hidalgo', 'Sonora', 'Molinito', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('92163', 'Miguel Hidalgo', 'Sonora', 'Coapa', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('97754', 'Miguel Hidalgo', 'Universidad', 'Coapa', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79547', 'Cuauhtemoc', 'Sonora', 'Coapa', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('11098', 'Benito Juarez', 'Sonora', 'Coapa', 49);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55349', 'Cuauhtemoc', 'Sonora', 'Rep. Costa Rica', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('50029', 'Azcapotzalco', 'Sonora', 'Coapa', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37069', 'Azcapotzalco', 'Toreo', 'Coapa', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('41948', 'Miguel Hidalgo', 'Sonora', 'Coapa', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76596', 'Benito Juarez', 'Ciudad Universitaria', 'Coapa', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('23311', 'Miguel Hidalgo', 'Sonora', 'Molinito', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('36459', 'Tlalpan', 'Sonora', 'Coapa', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('47258', 'Coyoacan', 'Toreo', 'Molinito', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('50334', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 65);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('91164', 'Benito Juarez', 'Toreo', 'Coapa', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99758', 'Miguel Hidalgo', 'Sonora', 'Coapa', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20538', 'Gustavo A. Madero', 'Sonora', 'Coapa', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('58427', 'Azcapotzalco', 'Toreo', 'Coapa', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('58791', 'Benito Juarez', 'Sonora', 'Coapa', 92);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37217', 'Cuauhtemoc', 'Sonora', 'Coapa', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('12285', 'Azcapotzalco', 'Universidad', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('62865', 'Miguel Hidalgo', 'Sonora', 'Molinito', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('96937', 'Cuauhtemoc', 'Sonora', 'Salto del Agua', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('56727', 'Azcapotzalco', 'Toreo', 'Coapa', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('67286', 'Miguel Hidalgo', 'Sonora', 'Coapa', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('39232', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 42);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03982', 'Miguel Hidalgo', 'Universidad', 'Coapa', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55888', 'Miguel Hidalgo', 'Sonora', 'Molinito', 42);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05157', 'Azcapotzalco', 'Sonora', 'Coapa', 83);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83110', 'Azcapotzalco', 'Universidad', 'Coapa', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03082', 'Cuauhtemoc', 'Universidad', 'Molinito', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('96454', 'Miguel Hidalgo', 'Toreo', 'Salto del Agua', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('13435', 'Azcapotzalco', 'Zacatepec', 'Molinito', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('26314', 'Miguel Hidalgo', 'Coapa', 'Rep. Costa Rica', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('34864', 'Miguel Hidalgo', 'Toreo', 'Coapa', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('74457', 'Cuauhtemoc', 'Sonora', 'Coapa', 41);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63763', 'Miguel Hidalgo', 'Sonora', 'Molinito', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('95529', 'Azcapotzalco', 'Universidad', 'Coapa', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79586', 'Miguel Hidalgo', 'Sonora', 'Coapa', 64);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('27504', 'Cuauhtemoc', 'Zacatepec', 'Molinito', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('36804', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('90298', 'Miguel Hidalgo', 'Sonora', 'Molinito', 52);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('72257', 'Miguel Hidalgo', 'Sonora', 'Coapa', 70);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('21930', 'Cuauhtemoc', 'Toreo', 'Molinito', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('51793', 'Azcapotzalco', 'Sonora', 'Molinito', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('78143', 'Miguel Hidalgo', 'Sonora', 'Coapa', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('06705', 'Miguel Hidalgo', 'Universidad', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('38238', 'Miguel Hidalgo', 'Sonora', 'Molinito', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('69597', 'Azcapotzalco', 'Universidad', 'Coapa', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55870', 'Miguel Hidalgo', 'Sonora', 'Molinito', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('27345', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 31);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('82083', 'Cuauhtemoc', 'Ciudad Universitaria', 'Rep. Brasil', 86);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('68435', 'Miguel Hidalgo', 'Sonora', 'Molinito', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('38958', 'Miguel Hidalgo', 'Sonora', 'Coapa', 67);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('27396', 'Miguel Hidalgo', 'Universidad', 'Coapa', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('38492', 'Azcapotzalco', 'Sonora', 'Coapa', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('39837', 'Cuauhtemoc', 'Universidad', 'Coapa', 42);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('64543', 'Benito Juarez', 'Ciudad Universitaria', 'Coapa', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('39259', 'Benito Juarez', 'Toreo', 'Coapa', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('72926', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63928', 'Miguel Hidalgo', 'Sonora', 'Molinito', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('00110', 'Azcapotzalco', 'Sonora', 'Doctor Vertiz', 92);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05020', 'Azcapotzalco', 'Sonora', 'Molinito', 82);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('24339', 'Miguel Hidalgo', 'Sonora', 'Molinito', 92);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('04078', 'Azcapotzalco', 'Sonora', 'Coapa', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('65793', 'Benito Juarez', 'Universidad', 'Coapa', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79834', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('48958', 'Miguel Hidalgo', 'Sonora', 'Molinito', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('11799', 'Cuauhtemoc', 'Sonora', 'Coapa', 44);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('46668', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76109', 'Miguel Hidalgo', 'Universidad', 'Coapa', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('61451', 'Coyoacan', 'Universidad', 'Molinito', 53);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('17520', 'Cuauhtemoc', 'Sonora', 'Coapa', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('86137', 'Miguel Hidalgo', 'Sonora', 'Coapa', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('71360', 'Miguel Hidalgo', 'Toreo', 'Molinito', 53);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('54000', 'Coyoacan', 'Sonora', 'Coapa', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99175', 'Azcapotzalco', 'Zacatepec', 'Coapa', 86);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('49977', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('15186', 'Cuauhtemoc', 'Zacatepec', 'Rep. Costa Rica', 19);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('69750', 'Azcapotzalco', 'Sonora', 'Molinito', 7);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('91614', 'Azcapotzalco', 'Sonora', 'Coapa', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('12090', 'Cuauhtemoc', 'Sonora', 'Rep. Brasil', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('91139', 'Azcapotzalco', 'Universidad', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99470', 'Cuauhtemoc', 'Sonora', 'Coapa', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76281', 'Azcapotzalco', 'Sonora', 'Coapa', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('18703', 'Cuauhtemoc', 'Zacatepec', 'Coapa', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('91336', 'Azcapotzalco', 'Universidad', 'Molinito', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('33954', 'Azcapotzalco', 'Universidad', 'Coapa', 47);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('64807', 'Miguel Hidalgo', 'Sonora', 'Coapa', 95);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('87043', 'Azcapotzalco', 'Sonora', 'Coapa', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('96149', 'Azcapotzalco', 'Zacatepec', 'Coapa', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('30641', 'Miguel Hidalgo', 'Roma', 'Coapa', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('14695', 'Miguel Hidalgo', 'Toreo', 'Molinito', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('23898', 'Cuauhtemoc', 'Universidad', 'Coapa', 53);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('00364', 'Miguel Hidalgo', 'Sonora', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('36758', 'Azcapotzalco', 'Zacatepec', 'Molinito', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('80825', 'Miguel Hidalgo', 'Universidad', 'Molinito', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('31417', 'Miguel Hidalgo', 'Sonora', 'Coapa', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('88274', 'Benito Juarez', 'Sonora', 'Rep. Costa Rica', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('98665', 'Miguel Hidalgo', 'Toreo', 'Molinito', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('24472', 'Azcapotzalco', 'Universidad', 'Coapa', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79387', 'Cuauhtemoc', 'Toreo', 'Molinito', 33);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37568', 'Cuauhtemoc', 'Sonora', 'Coapa', 52);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('57637', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 53);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('14881', 'Cuauhtemoc', 'Sonora', 'Salto del Agua', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('26398', 'Cuauhtemoc', 'Universidad', 'Molinito', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55806', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 49);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('68312', 'Miguel Hidalgo', 'Sonora', 'Coapa', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('98553', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('43749', 'Miguel Hidalgo', 'Sonora', 'Coapa', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('64585', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('60579', 'Miguel Hidalgo', 'Sonora', 'Salto del Agua', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('70226', 'Azcapotzalco', 'Sonora', 'Coapa', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('06124', 'Miguel Hidalgo', 'Sonora', 'Coapa', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76431', 'Miguel Hidalgo', 'Sonora', 'Coapa', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('92859', 'Miguel Hidalgo', 'Sonora', 'Molinito', 19);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('57698', 'Azcapotzalco', 'Sonora', 'Molinito', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('94009', 'Azcapotzalco', 'Toreo', 'Rep. Costa Rica', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('31376', 'Benito Juarez', 'Sonora', 'Coapa', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79947', 'Miguel Hidalgo', 'Sonora', 'Coapa', 82);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('28969', 'Benito Juarez', 'Sonora', 'Odontologia', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('29206', 'Cuauhtemoc', 'Universidad', 'Coapa', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('74101', 'Cuauhtemoc', 'Sonora', 'Coapa', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('29991', 'Miguel Hidalgo', 'Universidad', 'Coapa', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02098', 'Miguel Hidalgo', 'Universidad', 'Coapa', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('41549', 'Miguel Hidalgo', 'Sonora', 'Coapa', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('40614', 'Miguel Hidalgo', 'Sonora', 'Coapa', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('12450', 'Azcapotzalco', 'Zacatepec', 'Rep. Brasil', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('73677', 'Cuauhtemoc', 'Universidad', 'Coapa', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('98433', 'Benito Juarez', 'Sonora', 'Coapa', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('45277', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76368', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('68091', 'Azcapotzalco', 'Universidad', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03942', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('42286', 'Miguel Hidalgo', 'Toreo', 'Coapa', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('90791', 'Azcapotzalco', 'Toreo', 'Rep. Costa Rica', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('14925', 'Miguel Hidalgo', 'Sonora', 'Molinito', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('58420', 'Azcapotzalco', 'Sonora', 'Molinito', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('67272', 'Azcapotzalco', 'Toreo', 'Salto del Agua', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('77398', 'Benito Juarez', 'Toreo', 'Coapa', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('24659', 'Azcapotzalco', 'Sonora', 'Coapa', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('36761', 'Benito Juarez', 'Universidad', 'Rep. Costa Rica', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('29065', 'Miguel Hidalgo', 'Zacatepec', 'Rep. Costa Rica', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('51396', 'Miguel Hidalgo', 'Sonora', 'Coapa', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('49446', 'Miguel Hidalgo', 'Sonora', 'Coapa', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('44937', 'Azcapotzalco', 'Universidad', 'Coapa', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('36434', 'Azcapotzalco', 'Toreo', 'Rep. Costa Rica', 95);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('82227', 'Benito Juarez', 'Universidad', 'Coapa', 41);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('06334', 'Azcapotzalco', 'Sonora', 'Molinito', 41);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('90180', 'Miguel Hidalgo', 'Insurgentes', 'Rep. Costa Rica', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('81459', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('18717', 'Miguel Hidalgo', 'Sonora', 'Coapa', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('77772', 'Miguel Hidalgo', 'Universidad', 'Molinito', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('80328', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99322', 'Azcapotzalco', 'Toreo', 'Rep. Brasil', 37);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('01661', 'Azcapotzalco', 'Toreo', 'Coapa', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('16788', 'Miguel Hidalgo', 'Sonora', 'Molinito', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('51251', 'Azcapotzalco', 'Sonora', 'Molinito', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('41286', 'Miguel Hidalgo', 'Sonora', 'Coapa', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('35033', 'Gustavo A. Madero', 'Zacatepec', 'Rep. Brasil', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('18655', 'Miguel Hidalgo', 'Sonora', 'Molinito', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('10554', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('78937', 'Miguel Hidalgo', 'Sonora', 'Molinito', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('00359', 'Cuauhtemoc', 'Universidad', 'Rep. Costa Rica', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('59601', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 70);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('87028', 'Coyoacan', 'Sonora', 'Molinito', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('26116', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('85055', 'Miguel Hidalgo', 'Universidad', 'Coapa', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('73320', 'Miguel Hidalgo', 'Universidad', 'Rep. Costa Rica', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83880', 'Coyoacan', 'Garibaldi', 'Rep. Costa Rica', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('61834', 'Azcapotzalco', 'Universidad', 'Molinito', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05257', 'Miguel Hidalgo', 'Sonora', 'Coapa', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('95659', 'Miguel Hidalgo', 'Sonora', 'Coapa', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('66266', 'Cuauhtemoc', 'Zacatepec', 'Molinito', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('17411', 'Miguel Hidalgo', 'Sonora', 'Molinito', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63110', 'Miguel Hidalgo', 'Sonora', 'Coapa', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76139', 'Miguel Hidalgo', 'Universidad', 'Coapa', 74);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('22611', 'Miguel Hidalgo', 'Universidad', 'Coapa', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('16577', 'Miguel Hidalgo', 'Universidad', 'Molinito', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('15908', 'Azcapotzalco', 'Sonora', 'Coapa', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('27578', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Rep. Costa Rica', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('49390', 'Azcapotzalco', 'Toreo', 'Coapa', 74);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('78397', 'Azcapotzalco', 'Sonora', 'Salto del Agua', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('57987', 'Miguel Hidalgo', 'Toreo', 'Rep. Brasil', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('60659', 'Azcapotzalco', 'Sonora', 'Coapa', 15);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03850', 'Miguel Hidalgo', 'Universidad', 'Coapa', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('68403', 'Miguel Hidalgo', 'Sonora', 'Coapa', 37);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('25491', 'Miguel Hidalgo', 'Toreo', 'Doctor Vertiz', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('82345', 'Miguel Hidalgo', 'Universidad', 'Molinito', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('60731', 'Azcapotzalco', 'Sonora', 'Minnesota', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99473', 'Miguel Hidalgo', 'Toreo', 'Molinito', 33);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('34370', 'Miguel Hidalgo', 'Universidad', 'Coapa', 67);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('93855', 'Azcapotzalco', 'Universidad', 'Rep. Brasil', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('93193', 'Miguel Hidalgo', 'Sonora', 'Coapa', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55399', 'Tlalpan', 'Universidad', 'Coapa', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('72670', 'Azcapotzalco', 'Sonora', 'Molinito', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('89416', 'Cuauhtemoc', 'Universidad', 'Rep. Costa Rica', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20230', 'Azcapotzalco', 'Sonora', 'Molinito', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('57906', 'Miguel Hidalgo', 'Toreo', 'Coapa', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('45363', 'Miguel Hidalgo', 'Sonora', 'Coapa', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('68339', 'Miguel Hidalgo', 'Sonora', 'Coapa', 31);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('94335', 'Benito Juarez', 'Sonora', 'Coapa', 41);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('42998', 'Miguel Hidalgo', 'Sonora', 'Coapa', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('74688', 'Miguel Hidalgo', 'Universidad', 'Coapa', 47);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76628', 'Azcapotzalco', 'Universidad', 'Coapa', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('43513', 'Azcapotzalco', 'Sonora', 'Coapa', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('30052', 'Cuauhtemoc', 'Zacatepec', 'Molinito', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79957', 'Azcapotzalco', 'Sonora', 'Rep. Brasil', 67);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('77217', 'Miguel Hidalgo', 'Sonora', 'Coapa', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('87561', 'Miguel Hidalgo', 'Universidad', 'Minnesota', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63831', 'Azcapotzalco', 'Universidad', 'Coapa', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('64655', 'Benito Juarez', 'Universidad', 'Coapa', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('32908', 'Miguel Hidalgo', 'Sonora', 'Coapa', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('10894', 'Miguel Hidalgo', 'Sonora', 'Molinito', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('65611', 'Miguel Hidalgo', 'Sonora', 'Coapa', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('28384', 'Miguel Hidalgo', 'Sonora', 'Coapa', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02949', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 13);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('35288', 'Azcapotzalco', 'Sonora', 'Coapa', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('08911', 'Miguel Hidalgo', 'Sonora', 'Coapa', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('45929', 'Azcapotzalco', 'Sonora', 'Coapa', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('43809', 'Miguel Hidalgo', 'Sonora', 'Molinito', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('38619', 'Miguel Hidalgo', 'Toreo', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03907', 'Miguel Hidalgo', 'Toreo', 'Molinito', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76931', 'Miguel Hidalgo', 'Sonora', 'Molinito', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('51287', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Rep. Costa Rica', 52);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('80516', 'Miguel Hidalgo', 'Garibaldi', 'Molinito', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79460', 'Miguel Hidalgo', 'Sonora', 'Molinito', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99114', 'Coyoacan', 'Sonora', 'Molinito', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('10241', 'Miguel Hidalgo', 'Toreo', 'Coapa', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('25681', 'Azcapotzalco', 'Sonora', 'Coapa', 89);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('70375', 'Cuauhtemoc', 'Insurgentes', 'Molinito', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('69735', 'Coyoacan', 'Sonora', 'Rep. Costa Rica', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('82061', 'Miguel Hidalgo', 'Sonora', 'Molinito', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('16856', 'Benito Juarez', 'Universidad', 'Molinito', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('47746', 'Miguel Hidalgo', 'Sonora', 'Coapa', 13);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('97010', 'Cuauhtemoc', 'Ciudad Universitaria', 'Rep. Costa Rica', 70);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('12963', 'Cuauhtemoc', 'Sonora', 'Coapa', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('86217', 'Miguel Hidalgo', 'Sonora', 'Coapa', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83012', 'Miguel Hidalgo', 'Sonora', 'Coapa', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('89600', 'Benito Juarez', 'Sonora', 'Coapa', 83);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('43346', 'Azcapotzalco', 'Sonora', 'Rep. Brasil', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('25808', 'Azcapotzalco', 'Sonora', 'Coapa', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('31951', 'Cuauhtemoc', 'Sonora', 'Coapa', 89);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('08445', 'Azcapotzalco', 'Toreo', 'Molinito', 44);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('78616', 'Azcapotzalco', 'Zacatepec', 'Rep. Costa Rica', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('04232', 'Cuauhtemoc', 'Universidad', 'Rep. Costa Rica', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('22895', 'Miguel Hidalgo', 'Zacatepec', 'Molinito', 82);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('89956', 'Azcapotzalco', 'Sonora', 'Molinito', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99128', 'Miguel Hidalgo', 'Toreo', 'Molinito', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('46737', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('58821', 'Benito Juarez', 'Sonora', 'Molinito', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05659', 'Miguel Hidalgo', 'Universidad', 'Molinito', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('21202', 'Miguel Hidalgo', 'Sonora', 'Molinito', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('42806', 'Miguel Hidalgo', 'Sonora', 'Coapa', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('07443', 'Azcapotzalco', 'Zacatepec', 'Rep. Brasil', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('73785', 'Miguel Hidalgo', 'Coapa', 'Coapa', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05261', 'Miguel Hidalgo', 'Toreo', 'Coapa', 23);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('06795', 'Coyoacan', 'Sonora', 'Coapa', 78);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('09734', 'Miguel Hidalgo', 'Sonora', 'Molinito', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('97774', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02207', 'Miguel Hidalgo', 'Universidad', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('76579', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('11006', 'Miguel Hidalgo', 'Toreo', 'Coapa', 65);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('99777', 'Cuauhtemoc', 'Sonora', 'Coapa', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('88464', 'Azcapotzalco', 'Universidad', 'Coapa', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('01965', 'Miguel Hidalgo', 'Sonora', 'Coapa', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('59498', 'Azcapotzalco', 'Toreo', 'Coapa', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('84165', 'Miguel Hidalgo', 'Sonora', 'Rep. Brasil', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83628', 'Miguel Hidalgo', 'Sonora', 'Coapa', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('81169', 'Miguel Hidalgo', 'Universidad', 'Coapa', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('92599', 'Cuauhtemoc', 'Sonora', 'Coapa', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('09619', 'Azcapotzalco', 'Sonora', 'Coapa', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('93615', 'Azcapotzalco', 'Universidad', 'Coapa', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('74817', 'Miguel Hidalgo', 'Toreo', 'Coapa', 13);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('88666', 'Cuauhtemoc', 'Sonora', 'Coapa', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('56449', 'Cuauhtemoc', 'Roma', 'Coapa', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('71995', 'Coyoacan', 'Universidad', 'Coapa', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83934', 'Miguel Hidalgo', 'Sonora', 'Molinito', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('13340', 'Coyoacan', 'Sonora', 'Rep. Brasil', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('90919', 'Azcapotzalco', 'Toreo', 'Molinito', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37364', 'Azcapotzalco', 'Sonora', 'Salto del Agua', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('62696', 'Miguel Hidalgo', 'Sonora', 'Coapa', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('93318', 'Azcapotzalco', 'Sonora', 'Coapa', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('69114', 'Miguel Hidalgo', 'Universidad', 'Molinito', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('54247', 'Azcapotzalco', 'Sonora', 'Rep. Brasil', 72);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('22060', 'Azcapotzalco', 'Universidad', 'Molinito', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('56495', 'Miguel Hidalgo', 'Universidad', 'Coapa', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('66550', 'Cuauhtemoc', 'Sonora', 'Coapa', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('45133', 'Miguel Hidalgo', 'Sonora', 'Coapa', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('14987', 'Miguel Hidalgo', 'Sonora', 'Molinito', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20917', 'Miguel Hidalgo', 'Toreo', 'Molinito', 89);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('32502', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('79422', 'Miguel Hidalgo', 'Sonora', 'Coapa', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('82634', 'Miguel Hidalgo', 'Sonora', 'Coapa', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('07699', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('92305', 'Cuauhtemoc', 'Universidad', 'Coapa', 47);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('45003', 'Miguel Hidalgo', 'Toreo', 'Rep. Costa Rica', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('23899', 'Azcapotzalco', 'Universidad', 'Coapa', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('11562', 'Miguel Hidalgo', 'Universidad', 'Coapa', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03402', 'Azcapotzalco', 'Sonora', 'Molinito', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('75823', 'Miguel Hidalgo', 'Sonora', 'Coapa', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55232', 'Miguel Hidalgo', 'Sonora', 'Coapa', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('86136', 'Miguel Hidalgo', 'Sonora', 'Coapa', 26);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('89792', 'Miguel Hidalgo', 'Universidad', 'Rep. Brasil', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('85492', 'Cuauhtemoc', 'Garibaldi', 'Salto del Agua', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('70207', 'Miguel Hidalgo', 'Garibaldi', 'Coapa', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('55075', 'Miguel Hidalgo', 'Sonora', 'Coapa', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('36637', 'Azcapotzalco', 'Universidad', 'Salto del Agua', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('68810', 'Miguel Hidalgo', 'Toreo', 'Coapa', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('47835', 'Miguel Hidalgo', 'Sonora', 'Coapa', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('19510', 'Miguel Hidalgo', 'Universidad', 'Molinito', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('33830', 'Miguel Hidalgo', 'Sonora', 'Coapa', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('39659', 'Azcapotzalco', 'Ciudad Universitaria', 'Molinito', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('88315', 'Azcapotzalco', 'Roma', 'Molinito', 15);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('81385', 'Azcapotzalco', 'Zacatepec', 'Coapa', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('32495', 'Cuauhtemoc', 'Toreo', 'Coapa', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('73370', 'Miguel Hidalgo', 'Sonora', 'Coapa', 33);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('06313', 'Azcapotzalco', 'Sonora', 'Coapa', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('33277', 'Azcapotzalco', 'Universidad', 'Rep. Costa Rica', 64);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('65669', 'Miguel Hidalgo', 'Sonora', 'Molinito', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37081', 'Azcapotzalco', 'Sonora', 'Rep. Costa Rica', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('84966', 'Miguel Hidalgo', 'Toreo', 'Molinito', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('28526', 'Coyoacan', 'Toreo', 'Rep. Costa Rica', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37926', 'Benito Juarez', 'Toreo', 'Molinito', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63365', 'Benito Juarez', 'Sonora', 'Molinito', 47);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('28677', 'Miguel Hidalgo', 'Sonora', 'Rep. Costa Rica', 26);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('05755', 'Azcapotzalco', 'Universidad', 'Coapa', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('46318', 'Cuauhtemoc', 'Sonora', 'Coapa', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('03356', 'Cuauhtemoc', 'Sonora', 'Coapa', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('02980', 'Miguel Hidalgo', 'Sonora', 'Coapa', 52);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('56793', 'Azcapotzalco', 'Zacatepec', 'Coapa', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('48521', 'Benito Juarez', 'Sonora', 'Molinito', 33);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('78067', 'Miguel Hidalgo', 'Universidad', 'Salto del Agua', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('83540', 'Miguel Hidalgo', 'Universidad', 'Molinito', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('27863', 'Benito Juarez', 'Sonora', 'Rep. Costa Rica', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('48408', 'Benito Juarez', 'Universidad', 'Molinito', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('49628', 'Miguel Hidalgo', 'Universidad', 'Coapa', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63189', 'Benito Juarez', 'Sonora', 'Molinito', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('31742', 'Miguel Hidalgo', 'Sonora', 'Coapa', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('97561', 'Azcapotzalco', 'Sonora', 'Molinito', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('20860', 'Coyoacan', 'Sonora', 'Coapa', 74);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('84860', 'Azcapotzalco', 'Sonora', 'Coapa', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('35212', 'Miguel Hidalgo', 'Sonora', 'Molinito', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('63807', 'Cuauhtemoc', 'Ciudad Universitaria', 'Molinito', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('65648', 'Azcapotzalco', 'Sonora', 'Coapa', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('65225', 'Cuauhtemoc', 'Sonora', 'Coapa', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('48924', 'Cuauhtemoc', 'Sonora', 'Coapa', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('11135', 'Gustavo A. Madero', 'Universidad', 'Coapa', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('47155', 'Cuauhtemoc', 'Sonora', 'Coapa', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('18090', 'Azcapotzalco', 'Toreo', 'Coapa', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('46785', 'Cuauhtemoc', 'Universidad', 'Rep. Costa Rica', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('31782', 'Miguel Hidalgo', 'Zacatepec', 'Coapa', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('81589', 'Cuauhtemoc', 'Zacatepec', 'Coapa', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('01082', 'Miguel Hidalgo', 'Sonora', 'Molinito', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37861', 'Miguel Hidalgo', 'Toreo', 'Molinito', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('45557', 'Miguel Hidalgo', 'Ciudad Universitaria', 'Coapa', 49);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('37924', 'Cuauhtemoc', 'Sonora', 'Coapa', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('07896', 'Miguel Hidalgo', 'Sonora', 'Coapa', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('34401', 'Azcapotzalco', 'Zacatepec', 'Coapa', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('43884', 'Azcapotzalco', 'Universidad', 'Rep. Brasil', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('39483', 'Cuauhtemoc', 'Sonora', 'Coapa', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values ('17895', 'Miguel Hidalgo', 'Garibaldi', 'Molinito', 22);
