insert into origen (id_viaje, delegacion, colonia, calle, lote) values (71221, 'Coyoacan', 'Insurgentes', 'Odontologia', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (12171, 'Iztalapa', 'Ermita', 'Masaryk', 31);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (61709, 'Iztalapa', 'Insurgentes', 'Torres', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (76407, 'Tlalpan', 'Insurgentes', 'Copilco', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99051, 'Iztalapa', 'Ermita', 'Torres', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (91531, 'Tlalpan', 'Ciudad Universitaria', 'Masaryk', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (29168, 'Magdalena Contreras', 'Ciudad Universitaria', 'Odontologia', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45333, 'Iztalapa', 'Universidad', 'Masaryk', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (68242, 'Tlalpan', 'Insurgentes', 'Masaryk', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52488, 'Iztalapa', 'Ermita', 'Masaryk', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81353, 'Iztalapa', 'Universidad', 'Torres', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (60104, 'Tlalpan', 'Ciudad Universitaria', 'Torres', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (43805, 'Iztalapa', 'Ermita', 'Copilco', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (83874, 'Coyoacan', 'Ermita', 'Copilco', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (63987, 'Iztalapa', 'Ermita', 'Masaryk', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99199, 'Coyoacan', 'Insurgentes', 'Masaryk', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (91584, 'Coyoacan', 'Ermita', 'Odontologia', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52293, 'Magdalena Contreras', 'Ermita', 'Torres', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (68306, 'Iztalapa', 'Insurgentes', 'Masaryk', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52414, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (44897, 'Tlalpan', 'Ermita', 'Torres', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (31144, 'Iztalapa', 'Ermita', 'Copilco', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94574, 'Iztalapa', 'Ermita', 'Torres', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (15900, 'Coyoacan', 'Ermita', 'Masaryk', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (42555, 'Coyoacan', 'Ciudad Universitaria', 'Torres', 23);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (86830, 'Iztalapa', 'Ermita', 'Torres', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81946, 'Magdalena Contreras', 'Insurgentes', 'Masaryk', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (18602, 'Coyoacan', 'Insurgentes', 'Torres', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (39379, 'Tlalpan', 'Ermita', 'Masaryk', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (35551, 'Tlalpan', 'Ciudad Universitaria', 'Torres', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (59924, 'Iztalapa', 'Ermita', 'Odontologia', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (88106, 'Iztalapa', 'Ermita', 'Torres', 13);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (56343, 'Iztalapa', 'Ermita', 'Torres', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81992, 'Magdalena Contreras', 'Universidad', 'Masaryk', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (16018, 'Iztalapa', 'Ermita', 'Torres', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (79898, 'Iztalapa', 'Ermita', 'Masaryk', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (16798, 'Magdalena Contreras', 'Ermita', 'Torres', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (83943, 'Iztalapa', 'Ermita', 'Masaryk', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (28358, 'Coyoacan', 'Ermita', 'Torres', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (44773, 'Tlalpan', 'Ermita', 'Torres', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99915, 'Magdalena Contreras', 'Ciudad Universitaria', 'Torres', 18);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (25773, 'Iztalapa', 'Ermita', 'Torres', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (38352, 'Coyoacan', 'Insurgentes', 'Torres', 44);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (29516, 'Tlalpan', 'Insurgentes', 'Masaryk', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (84425, 'Iztalapa', 'Ermita', 'Torres', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (73807, 'Coyoacan', 'Universidad', 'Torres', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (13360, 'Iztalapa', 'Ermita', 'Torres', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (68739, 'Iztalapa', 'Insurgentes', 'Copilco', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (23957, 'Iztalapa', 'Ermita', 'Torres', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (83946, 'Tlalpan', 'Ermita', 'Copilco', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (82583, 'Coyoacan', 'Ermita', 'Torres', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (85010, 'Iztalapa', 'Universidad', 'Odontologia', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (48599, 'Iztalapa', 'Insurgentes', 'Copilco', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (67964, 'Iztalapa', 'Universidad', 'Torres', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (65840, 'Tlalpan', 'Insurgentes', 'Copilco', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (95963, 'Iztalapa', 'Ermita', 'Torres', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (66041, 'Tlalpan', 'Ermita', 'Odontologia', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58204, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 15);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (73866, 'Coyoacan', 'Ermita', 'Torres', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (62465, 'Coyoacan', 'Insurgentes', 'Torres', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (78416, 'Tlalpan', 'Ciudad Universitaria', 'Masaryk', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (15286, 'Tlalpan', 'Ermita', 'Copilco', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (14294, 'Iztalapa', 'Insurgentes', 'Torres', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94502, 'Coyoacan', 'Universidad', 'Masaryk', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58164, 'Tlalpan', 'Ermita', 'Copilco', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (60898, 'Iztalapa', 'Universidad', 'Odontologia', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (86407, 'Tlalpan', 'Ciudad Universitaria', 'Torres', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (62815, 'Magdalena Contreras', 'Ermita', 'Torres', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52311, 'Magdalena Contreras', 'Ermita', 'Torres', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (73755, 'Iztalapa', 'Insurgentes', 'Copilco', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (19101, 'Iztalapa', 'Ciudad Universitaria', 'Masaryk', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (44851, 'Magdalena Contreras', 'Ermita', 'Masaryk', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (42325, 'Tlalpan', 'Ermita', 'Masaryk', 26);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (55680, 'Iztalapa', 'Ciudad Universitaria', 'Odontologia', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45930, 'Coyoacan', 'Ermita', 'Torres', 67);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (36252, 'Iztalapa', 'Insurgentes', 'Torres', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (27538, 'Iztalapa', 'Ermita', 'Masaryk', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (98142, 'Tlalpan', 'Insurgentes', 'Copilco', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (62011, 'Tlalpan', 'Insurgentes', 'Torres', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (35819, 'Magdalena Contreras', 'Ermita', 'Copilco', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (95111, 'Tlalpan', 'Universidad', 'Masaryk', 26);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (23538, 'Iztalapa', 'Universidad', 'Masaryk', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (62406, 'Coyoacan', 'Ermita', 'Torres', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (38623, 'Coyoacan', 'Ermita', 'Odontologia', 19);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (10464, 'Magdalena Contreras', 'Universidad', 'Copilco', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (30412, 'Coyoacan', 'Ermita', 'Masaryk', 72);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (66586, 'Coyoacan', 'Ermita', 'Torres', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (55178, 'Coyoacan', 'Ermita', 'Masaryk', 74);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52770, 'Coyoacan', 'Universidad', 'Copilco', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (24575, 'Iztalapa', 'Ciudad Universitaria', 'Copilco', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (63492, 'Iztalapa', 'Ermita', 'Copilco', 52);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (15078, 'Iztalapa', 'Insurgentes', 'Torres', 99);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (71658, 'Iztalapa', 'Insurgentes', 'Torres', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (12525, 'Magdalena Contreras', 'Ermita', 'Torres', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (85461, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (88069, 'Iztalapa', 'Ermita', 'Masaryk', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (38570, 'Tlalpan', 'Universidad', 'Torres', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45181, 'Magdalena Contreras', 'Ermita', 'Torres', 37);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45619, 'Magdalena Contreras', 'Ermita', 'Torres', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (78406, 'Iztalapa', 'Ermita', 'Odontologia', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94257, 'Tlalpan', 'Ermita', 'Masaryk', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (73247, 'Iztalapa', 'Insurgentes', 'Torres', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (61411, 'Iztalapa', 'Insurgentes', 'Masaryk', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (36251, 'Iztalapa', 'Universidad', 'Torres', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58456, 'Iztalapa', 'Insurgentes', 'Torres', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (55105, 'Coyoacan', 'Ermita', 'Copilco', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (79330, 'Iztalapa', 'Ermita', 'Masaryk', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94424, 'Coyoacan', 'Ermita', 'Copilco', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (89936, 'Iztalapa', 'Universidad', 'Torres', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (75926, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (59772, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (98729, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 44);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (10762, 'Iztalapa', 'Insurgentes', 'Copilco', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (93495, 'Magdalena Contreras', 'Insurgentes', 'Masaryk', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (22212, 'Iztalapa', 'Insurgentes', 'Torres', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (79424, 'Iztalapa', 'Ermita', 'Torres', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99050, 'Magdalena Contreras', 'Insurgentes', 'Torres', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (89406, 'Tlalpan', 'Ermita', 'Copilco', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (61966, 'Tlalpan', 'Universidad', 'Copilco', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (21981, 'Magdalena Contreras', 'Insurgentes', 'Odontologia', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (16558, 'Tlalpan', 'Ermita', 'Masaryk', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (37619, 'Tlalpan', 'Ermita', 'Masaryk', 70);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (88010, 'Coyoacan', 'Insurgentes', 'Odontologia', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (44078, 'Coyoacan', 'Insurgentes', 'Odontologia', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52953, 'Tlalpan', 'Ermita', 'Torres', 83);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45893, 'Iztalapa', 'Ermita', 'Torres', 74);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58106, 'Iztalapa', 'Ermita', 'Torres', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (38491, 'Iztalapa', 'Insurgentes', 'Copilco', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (19713, 'Coyoacan', 'Ermita', 'Torres', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (54265, 'Iztalapa', 'Ermita', 'Masaryk', 13);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (70826, 'Tlalpan', 'Insurgentes', 'Masaryk', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (69009, 'Tlalpan', 'Ermita', 'Copilco', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (24231, 'Magdalena Contreras', 'Ermita', 'Torres', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (49533, 'Iztalapa', 'Ermita', 'Torres', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (97379, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45210, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 53);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81363, 'Iztalapa', 'Insurgentes', 'Copilco', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (76919, 'Iztalapa', 'Universidad', 'Odontologia', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99030, 'Magdalena Contreras', 'Ermita', 'Odontologia', 15);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (65531, 'Coyoacan', 'Ermita', 'Masaryk', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (98218, 'Iztalapa', 'Insurgentes', 'Torres', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (42762, 'Magdalena Contreras', 'Ermita', 'Odontologia', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (67490, 'Tlalpan', 'Ciudad Universitaria', 'Masaryk', 33);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (70383, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 49);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45878, 'Iztalapa', 'Ciudad Universitaria', 'Masaryk', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (34438, 'Magdalena Contreras', 'Ciudad Universitaria', 'Torres', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (77580, 'Iztalapa', 'Ermita', 'Torres', 95);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (23644, 'Iztalapa', 'Ermita', 'Copilco', 86);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (19620, 'Iztalapa', 'Ermita', 'Odontologia', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (14443, 'Iztalapa', 'Universidad', 'Torres', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (24241, 'Tlalpan', 'Ermita', 'Masaryk', 89);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (36750, 'Coyoacan', 'Ermita', 'Masaryk', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (67565, 'Iztalapa', 'Ermita', 'Torres', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (80847, 'Tlalpan', 'Ermita', 'Torres', 44);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (64281, 'Iztalapa', 'Ermita', 'Torres', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (14082, 'Iztalapa', 'Ermita', 'Torres', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (25563, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (57957, 'Coyoacan', 'Insurgentes', 'Copilco', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (26833, 'Iztalapa', 'Ermita', 'Masaryk', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (30195, 'Coyoacan', 'Insurgentes', 'Torres', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (66676, 'Iztalapa', 'Ermita', 'Copilco', 26);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99663, 'Iztalapa', 'Ciudad Universitaria', 'Masaryk', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (60383, 'Tlalpan', 'Insurgentes', 'Copilco', 95);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (41453, 'Iztalapa', 'Ermita', 'Odontologia', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (19625, 'Magdalena Contreras', 'Insurgentes', 'Odontologia', 92);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (88760, 'Iztalapa', 'Ermita', 'Torres', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (88722, 'Tlalpan', 'Ermita', 'Torres', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (24803, 'Iztalapa', 'Ciudad Universitaria', 'Odontologia', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (54798, 'Iztalapa', 'Ermita', 'Torres', 47);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (70375, 'Iztalapa', 'Ermita', 'Masaryk', 49);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (77125, 'Coyoacan', 'Ermita', 'Masaryk', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (56254, 'Coyoacan', 'Ermita', 'Odontologia', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (86301, 'Iztalapa', 'Insurgentes', 'Torres', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (32188, 'Iztalapa', 'Ermita', 'Torres', 23);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (96153, 'Magdalena Contreras', 'Ermita', 'Torres', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (27042, 'Coyoacan', 'Ermita', 'Torres', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99754, 'Iztalapa', 'Insurgentes', 'Copilco', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (92599, 'Iztalapa', 'Insurgentes', 'Odontologia', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (93555, 'Coyoacan', 'Insurgentes', 'Torres', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (69389, 'Iztalapa', 'Ermita', 'Torres', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (64825, 'Tlalpan', 'Insurgentes', 'Odontologia', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (22973, 'Coyoacan', 'Ciudad Universitaria', 'Torres', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (83601, 'Iztalapa', 'Universidad', 'Masaryk', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81733, 'Tlalpan', 'Ermita', 'Odontologia', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (22830, 'Iztalapa', 'Ermita', 'Odontologia', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (62586, 'Magdalena Contreras', 'Universidad', 'Torres', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (13208, 'Magdalena Contreras', 'Ermita', 'Copilco', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (97017, 'Magdalena Contreras', 'Insurgentes', 'Torres', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (57194, 'Tlalpan', 'Ermita', 'Masaryk', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (63744, 'Iztalapa', 'Insurgentes', 'Masaryk', 49);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52690, 'Iztalapa', 'Ermita', 'Masaryk', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81143, 'Iztalapa', 'Ciudad Universitaria', 'Torres', 47);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58135, 'Tlalpan', 'Insurgentes', 'Masaryk', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (83379, 'Iztalapa', 'Insurgentes', 'Copilco', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (71517, 'Iztalapa', 'Insurgentes', 'Masaryk', 15);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (13502, 'Iztalapa', 'Ermita', 'Torres', 7);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (85372, 'Coyoacan', 'Ermita', 'Torres', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (10242, 'Coyoacan', 'Universidad', 'Masaryk', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (18839, 'Tlalpan', 'Ciudad Universitaria', 'Torres', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (77939, 'Coyoacan', 'Ermita', 'Copilco', 40);
