insert into origen (id_viaje, delegacion, colonia, calle, lote) values (10223, 'Tlahuac', 'CU', 'Calle 11', 35);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (10484, 'Cuajimalpa', 'CU', 'Calle 11', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (10611, 'Xochimilco', 'Guerrero', 'Pajuil', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (10850, 'Xochimilco', 'Morelos', 'Calle 11', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (11156, 'Iztacalco', 'CU', 'Pajuil', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (11486, 'Xochimilco', 'Romero Rubio', 'Pajuil', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (11819, 'Cuajimalpa', 'Morelos', 'Pajuil', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (12307, 'Tlahuac', 'Bondojito', 'Calle 11', 67);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (13017, 'Tlahuac', 'CU', 'Merced', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (13445, 'Xochimilco', 'Bondojito', 'CU', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (14168, 'Tlahuac', 'CU', 'Calle 11', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (14475, 'Azcapotzalco', 'Bondojito', 'Pajuil', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (15030, 'Tlahuac', 'Romero Rubio', 'Merced', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (16265, 'Tlahuac', 'Romero Rubio', 'Calle 11', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (16329, 'Tlahuac', 'Guerrero', 'Pajuil', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (16412, 'Xochimilco', 'Bondojito', 'Merced', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (17213, 'Tlahuac', 'Romero Rubio', 'Pajuil', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (17388, 'Xochimilco', 'Bondojito', 'Calle 11', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (17694, 'Xochimilco', 'Bondojito', 'Pajuil', 82);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (18595, 'Iztacalco', 'Romero Rubio', 'CU', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (18709, 'Cuajimalpa', 'Guerrero', 'Merced', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (18844, 'Tlahuac', 'Morelos', 'Calle 11', 66);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (19137, 'Cuajimalpa', 'CU', 'CU', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (19349, 'Xochimilco', 'CU', 'CU', 40);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (19656, 'Tlahuac', 'Bondojito', 'CU', 27);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (20003, 'Xochimilco', 'CU', 'CU', 53);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (20577, 'Tlahuac', 'Bondojito', 'Calle 11', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (21263, 'Tlahuac', 'CU', 'Pajuil', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (21428, 'Xochimilco', 'Bondojito', 'CU', 70);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (21575, 'Tlahuac', 'Romero Rubio', 'Calle 11', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (21608, 'Tlahuac', 'Bondojito', 'Merced', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (21929, 'Xochimilco', 'CU', 'Calle 11', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (22170, 'Tlahuac', 'CU', 'CU', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (22282, 'Tlahuac', 'Bondojito', 'Pajuil', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (22772, 'Tlahuac', 'Romero Rubio', 'Calle 11', 13);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (23181, 'Iztacalco', 'CU', 'CU', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (23289, 'Azcapotzalco', 'Bondojito', 'Calle 11', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (23314, 'Tlahuac', 'Morelos', 'Calle 11', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (25549, 'Tlahuac', 'CU', 'Calle 11', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (25556, 'Tlahuac', 'CU', 'Calle 11', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (26285, 'Xochimilco', 'Bondojito', 'Calle 11', 72);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (26370, 'Tlahuac', 'CU', 'Calle 11', 93);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (26788, 'Xochimilco', 'CU', 'Pajuil', 92);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (27015, 'Tlahuac', 'Morelos', 'Calle 11', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (27493, 'Tlahuac', 'Bondojito', 'Calle 11', 43);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (28505, 'Tlahuac', 'Bondojito', 'CU', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (29059, 'Cuajimalpa', 'CU', 'Pajuil', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (29193, 'Tlahuac', 'Romero Rubio', 'Pajuil', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (29363, 'Xochimilco', 'Romero Rubio', 'Merced', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (29627, 'Cuajimalpa', 'CU', 'Pajuil', 89);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (29897, 'Xochimilco', 'CU', 'Calle 11', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (30052, 'Xochimilco', 'CU', 'CU', 56);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (31486, 'Xochimilco', 'Bondojito', 'Pajuil', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (31779, 'Tlahuac', 'Bondojito', 'Calle 11', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (34522, 'Tlahuac', 'CU', 'Calle 11', 78);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (35733, 'Tlahuac', 'Bondojito', 'CU', 41);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (37277, 'Iztapalapa', 'Guerrero', 'Calle 11', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (38272, 'Tlahuac', 'CU', 'Pajuil', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (38631, 'Cuajimalpa', 'Romero Rubio', 'Merced', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (39447, 'Tlahuac', 'CU', 'Calle 11', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (40962, 'Xochimilco', 'CU', 'CU', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (40974, 'Tlahuac', 'Romero Rubio', 'Calle 11', 62);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (41167, 'Xochimilco', 'Bondojito', 'Calle 11', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (42368, 'Tlahuac', 'CU', 'Pajuil', 6);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (42687, 'Xochimilco', 'Bondojito', 'Calle 11', 24);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (42959, 'Xochimilco', 'CU', 'Calle 11', 32);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (43322, 'Tlahuac', 'Morelos', 'Calle 11', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (43357, 'Iztacalco', 'Romero Rubio', 'Calle 11', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (43593, 'Tlahuac', 'Bondojito', 'Calle 11', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (43665, 'Cuajimalpa', 'CU', 'Calle 11', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (43976, 'Tlahuac', 'CU', 'Merced', 65);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (44374, 'Xochimilco', 'CU', 'Calle 11', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (44395, 'Xochimilco', 'CU', 'CU', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (44841, 'Tlahuac', 'Bondojito', 'Pajuil', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (45818, 'Tlahuac', 'Bondojito', 'Calle 11', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (46321, 'Cuajimalpa', 'Bondojito', 'Calle 11', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (46874, 'Tlahuac', 'Bondojito', 'Calle 11', 17);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (46987, 'Cuajimalpa', 'Romero Rubio', 'Calle 11', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (48146, 'Iztacalco', 'CU', 'Calle 11', 1);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (49170, 'Tlahuac', 'CU', 'CU', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (50082, 'Xochimilco', 'Bondojito', 'Pajuil', 16);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (50459, 'Tlahuac', 'CU', 'Pajuil', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (50683, 'Iztapalapa', 'CU', 'Calle 11', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (51274, 'Tlahuac', 'Morelos', 'Pajuil', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (51666, 'Xochimilco', 'CU', 'Pajuil', 13);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (51812, 'Xochimilco', 'Bondojito', 'Pajuil', 86);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52407, 'Tlahuac', 'Bondojito', 'Calle 11', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (52438, 'Tlahuac', 'Romero Rubio', 'Pajuil', 51);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (53259, 'Cuajimalpa', 'Morelos', 'Pajuil', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (53602, 'Cuajimalpa', 'Bondojito', 'Calle 11', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (53737, 'Cuajimalpa', 'CU', 'CU', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (54954, 'Tlahuac', 'Morelos', 'Calle 11', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (54996, 'Tlahuac', 'Bondojito', 'Calle 11', 96);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (55029, 'Tlahuac', 'CU', 'Pajuil', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (55071, 'Tlahuac', 'Bondojito', 'Pajuil', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (56325, 'Tlahuac', 'CU', 'Merced', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (56588, 'Tlahuac', 'Guerrero', 'Calle 11', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (56842, 'Tlahuac', 'CU', 'Calle 11', 20);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (57690, 'Tlahuac', 'CU', 'Calle 11', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (57860, 'Cuajimalpa', 'CU', 'Calle 11', 74);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (57886, 'Xochimilco', 'Romero Rubio', 'Calle 11', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58659, 'Tlahuac', 'Romero Rubio', 'Calle 11', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58816, 'Xochimilco', 'Bondojito', 'Pajuil', 64);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (58939, 'Tlahuac', 'Romero Rubio', 'Pajuil', 12);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (59142, 'Tlahuac', 'CU', 'Calle 11', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (59446, 'Xochimilco', 'Bondojito', 'Calle 11', 85);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (59834, 'Iztapalapa', 'CU', 'Merced', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (60137, 'Tlahuac', 'CU', 'CU', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (60926, 'Xochimilco', 'CU', 'Merced', 95);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (61665, 'Iztacalco', 'CU', 'Calle 11', 34);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (61735, 'Azcapotzalco', 'CU', 'Calle 11', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (61765, 'Xochimilco', 'Bondojito', 'Calle 11', 38);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (62280, 'Tlahuac', 'CU', 'Calle 11', 19);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (62365, 'Tlahuac', 'CU', 'CU', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (63036, 'Cuajimalpa', 'Bondojito', 'Pajuil', 87);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (63771, 'Xochimilco', 'Bondojito', 'CU', 88);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (63851, 'Cuajimalpa', 'CU', 'Merced', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (64105, 'Tlahuac', 'CU', 'Merced', 80);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (64310, 'Cuajimalpa', 'CU', 'Pajuil', 42);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (64532, 'Xochimilco', 'Bondojito', 'Calle 11', 69);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (65321, 'Tlahuac', 'Bondojito', 'Calle 11', 29);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (65424, 'Tlahuac', 'CU', 'Calle 11', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (65975, 'Tlahuac', 'Bondojito', 'Merced', 7);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (66001, 'Xochimilco', 'CU', 'Pajuil', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (66171, 'Iztacalco', 'Bondojito', 'CU', 98);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (66354, 'Tlahuac', 'CU', 'Pajuil', 58);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (67382, 'Tlahuac', 'CU', 'CU', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (67978, 'Tlahuac', 'CU', 'Calle 11', 95);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (68002, 'Xochimilco', 'Bondojito', 'Calle 11', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (69052, 'Tlahuac', 'Bondojito', 'CU', 37);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (69453, 'Cuajimalpa', 'Bondojito', 'Pajuil', 76);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (70201, 'Tlahuac', 'CU', 'Pajuil', 7);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (70341, 'Tlahuac', 'Bondojito', 'Calle 11', 21);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (70367, 'Xochimilco', 'Romero Rubio', 'Pajuil', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (70826, 'Xochimilco', 'CU', 'CU', 8);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (71072, 'Tlahuac', 'Bondojito', 'Merced', 89);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (71620, 'Tlahuac', 'CU', 'Calle 11', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (71664, 'Xochimilco', 'Bondojito', 'Calle 11', 92);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (71798, 'Cuajimalpa', 'CU', 'Pajuil', 22);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (72022, 'Tlahuac', 'Romero Rubio', 'Calle 11', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (73079, 'Tlahuac', 'CU', 'Calle 11', 23);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (74152, 'Xochimilco', 'CU', 'Pajuil', 23);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (74171, 'Tlahuac', 'CU', 'CU', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (74463, 'Tlahuac', 'Morelos', 'Merced', 61);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (74578, 'Cuajimalpa', 'Bondojito', 'Calle 11', 55);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (75218, 'Tlahuac', 'CU', 'Calle 11', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (75842, 'Azcapotzalco', 'CU', 'Calle 11', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (75852, 'Xochimilco', 'CU', 'Calle 11', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (76111, 'Tlahuac', 'CU', 'Calle 11', 54);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (77175, 'Xochimilco', 'Bondojito', 'Merced', 30);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (77411, 'Xochimilco', 'CU', 'Calle 11', 2);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (78055, 'Tlahuac', 'CU', 'CU', 73);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (78527, 'Tlahuac', 'Romero Rubio', 'Calle 11', 59);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (78882, 'Cuajimalpa', 'CU', 'CU', 14);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (79426, 'Tlahuac', 'Guerrero', 'Pajuil', 75);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (79546, 'Xochimilco', 'Bondojito', 'CU', 97);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (79820, 'Tlahuac', 'CU', 'Calle 11', 36);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (80394, 'Tlahuac', 'CU', 'Calle 11', 46);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81264, 'Iztapalapa', 'Romero Rubio', 'Calle 11', 77);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81511, 'Azcapotzalco', 'CU', 'CU', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (81926, 'Tlahuac', 'Bondojito', 'Calle 11', 3);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (82931, 'Tlahuac', 'Guerrero', 'Calle 11', 11);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (83407, 'Xochimilco', 'Morelos', 'Pajuil', 33);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (84862, 'Cuajimalpa', 'Romero Rubio', 'Calle 11', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (85220, 'Tlahuac', 'CU', 'CU', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (85235, 'Iztacalco', 'Romero Rubio', 'Calle 11', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (85777, 'Tlahuac', 'CU', 'Merced', 50);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (85849, 'Cuajimalpa', 'CU', 'Pajuil', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (86499, 'Tlahuac', 'CU', 'Pajuil', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (86530, 'Iztapalapa', 'Bondojito', 'Calle 11', 23);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (87048, 'Iztapalapa', 'CU', 'Calle 11', 81);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (87599, 'Tlahuac', 'Bondojito', 'Pajuil', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (87687, 'Cuajimalpa', 'CU', 'Calle 11', 19);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (87949, 'Tlahuac', 'CU', 'Merced', 28);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (88824, 'Tlahuac', 'CU', 'Pajuil', 9);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (88878, 'Tlahuac', 'Morelos', 'CU', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (89438, 'Tlahuac', 'Bondojito', 'Pajuil', 48);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (89765, 'Tlahuac', 'Bondojito', 'Calle 11', 90);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (90102, 'Tlahuac', 'CU', 'Pajuil', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (90177, 'Tlahuac', 'Morelos', 'Pajuil', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (90478, 'Tlahuac', 'CU', 'Calle 11', 31);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (90847, 'Xochimilco', 'CU', 'Calle 11', 83);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (91573, 'Xochimilco', 'CU', 'Calle 11', 45);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (91677, 'Tlahuac', 'Bondojito', 'Calle 11', 60);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (93705, 'Tlahuac', 'CU', 'Calle 11', 71);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94272, 'Tlahuac', 'CU', 'Pajuil', 68);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94445, 'Tlahuac', 'CU', 'Merced', 10);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94520, 'Iztacalco', 'CU', 'Calle 11', 91);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94790, 'Iztacalco', 'Morelos', 'Calle 11', 100);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (94923, 'Tlahuac', 'CU', 'Merced', 84);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (95541, 'Xochimilco', 'CU', 'Calle 11', 53);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (96039, 'Tlahuac', 'CU', 'Merced', 79);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (96146, 'Cuajimalpa', 'Bondojito', 'Calle 11', 94);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (96567, 'Xochimilco', 'Bondojito', 'Pajuil', 57);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (97196, 'Tlahuac', 'CU', 'Pajuil', 4);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (98417, 'Xochimilco', 'CU', 'Calle 11', 63);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (98473, 'Xochimilco', 'CU', 'Pajuil', 25);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (98552, 'Xochimilco', 'Morelos', 'Calle 11', 5);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (98908, 'Iztapalapa', 'Guerrero', 'Pajuil', 39);
insert into origen (id_viaje, delegacion, colonia, calle, lote) values (99671, 'Iztacalco', 'Guerrero', 'Calle 11', 28);
