insert into rol (id_cliente, rol) values ('99579', 'Cliente normal');
insert into rol (id_cliente, rol) values ('29110', 'Alumno');
insert into rol (id_cliente, rol) values ('11405', 'Trabajador');
insert into rol (id_cliente, rol) values ('41002', 'Alumno');
insert into rol (id_cliente, rol) values ('77152', 'Cliente normal');
insert into rol (id_cliente, rol) values ('19263', 'Cliente normal');
insert into rol (id_cliente, rol) values ('85603', 'Academico');
insert into rol (id_cliente, rol) values ('36112', 'Academico');
insert into rol (id_cliente, rol) values ('11175', 'Cliente normal');
insert into rol (id_cliente, rol) values ('70380', 'Trabajador');
insert into rol (id_cliente, rol) values ('11381', 'Cliente normal');
insert into rol (id_cliente, rol) values ('97967', 'Cliente normal');
insert into rol (id_cliente, rol) values ('07976', 'Trabajador');
insert into rol (id_cliente, rol) values ('69818', 'Cliente normal');
insert into rol (id_cliente, rol) values ('94744', 'Cliente normal');
insert into rol (id_cliente, rol) values ('03844', 'Cliente normal');
insert into rol (id_cliente, rol) values ('26861', 'Trabajador');
insert into rol (id_cliente, rol) values ('19722', 'Cliente normal');
insert into rol (id_cliente, rol) values ('08059', 'Trabajador');
insert into rol (id_cliente, rol) values ('75547', 'Academico');
insert into rol (id_cliente, rol) values ('92242', 'Academico');
insert into rol (id_cliente, rol) values ('10948', 'Cliente normal');
insert into rol (id_cliente, rol) values ('92625', 'Trabajador');
insert into rol (id_cliente, rol) values ('41404', 'Cliente normal');
insert into rol (id_cliente, rol) values ('45715', 'Trabajador');
insert into rol (id_cliente, rol) values ('91305', 'Trabajador');
insert into rol (id_cliente, rol) values ('54843', 'Cliente normal');
insert into rol (id_cliente, rol) values ('24075', 'Academico');
insert into rol (id_cliente, rol) values ('94823', 'Alumno');
insert into rol (id_cliente, rol) values ('35930', 'Trabajador');
insert into rol (id_cliente, rol) values ('41909', 'Trabajador');
insert into rol (id_cliente, rol) values ('75160', 'Trabajador');
insert into rol (id_cliente, rol) values ('57313', 'Trabajador');
insert into rol (id_cliente, rol) values ('30454', 'Cliente normal');
insert into rol (id_cliente, rol) values ('16808', 'Trabajador');
insert into rol (id_cliente, rol) values ('41478', 'Cliente normal');
insert into rol (id_cliente, rol) values ('23809', 'Cliente normal');
insert into rol (id_cliente, rol) values ('73484', 'Academico');
insert into rol (id_cliente, rol) values ('71716', 'Trabajador');
insert into rol (id_cliente, rol) values ('96636', 'Trabajador');
insert into rol (id_cliente, rol) values ('90370', 'Academico');
insert into rol (id_cliente, rol) values ('89504', 'Cliente normal');
insert into rol (id_cliente, rol) values ('49972', 'Trabajador');
insert into rol (id_cliente, rol) values ('45391', 'Trabajador');
insert into rol (id_cliente, rol) values ('68926', 'Trabajador');
insert into rol (id_cliente, rol) values ('15661', 'Cliente normal');
insert into rol (id_cliente, rol) values ('17119', 'Cliente normal');
insert into rol (id_cliente, rol) values ('36226', 'Cliente normal');
insert into rol (id_cliente, rol) values ('93013', 'Cliente normal');
insert into rol (id_cliente, rol) values ('47375', 'Trabajador');
insert into rol (id_cliente, rol) values ('17130', 'Cliente normal');
insert into rol (id_cliente, rol) values ('22141', 'Alumno');
insert into rol (id_cliente, rol) values ('66095', 'Cliente normal');
insert into rol (id_cliente, rol) values ('78723', 'Cliente normal');
insert into rol (id_cliente, rol) values ('93875', 'Cliente normal');
insert into rol (id_cliente, rol) values ('51068', 'Alumno');
insert into rol (id_cliente, rol) values ('55562', 'Cliente normal');
insert into rol (id_cliente, rol) values ('68203', 'Alumno');
insert into rol (id_cliente, rol) values ('35943', 'Cliente normal');
insert into rol (id_cliente, rol) values ('47862', 'Cliente normal');
insert into rol (id_cliente, rol) values ('89293', 'Trabajador');
insert into rol (id_cliente, rol) values ('64142', 'Cliente normal');
insert into rol (id_cliente, rol) values ('53730', 'Cliente normal');
insert into rol (id_cliente, rol) values ('03588', 'Cliente normal');
insert into rol (id_cliente, rol) values ('76392', 'Alumno');
insert into rol (id_cliente, rol) values ('48345', 'Trabajador');
insert into rol (id_cliente, rol) values ('34711', 'Alumno');
insert into rol (id_cliente, rol) values ('68166', 'Cliente normal');
insert into rol (id_cliente, rol) values ('26589', 'Academico');
insert into rol (id_cliente, rol) values ('94853', 'Cliente normal');
insert into rol (id_cliente, rol) values ('82877', 'Cliente normal');
insert into rol (id_cliente, rol) values ('22303', 'Academico');
insert into rol (id_cliente, rol) values ('20879', 'Alumno');
insert into rol (id_cliente, rol) values ('65576', 'Academico');
insert into rol (id_cliente, rol) values ('80578', 'Alumno');
insert into rol (id_cliente, rol) values ('03230', 'Alumno');
insert into rol (id_cliente, rol) values ('56887', 'Academico');
insert into rol (id_cliente, rol) values ('66523', 'Trabajador');
insert into rol (id_cliente, rol) values ('46897', 'Academico');
insert into rol (id_cliente, rol) values ('57858', 'Cliente normal');
insert into rol (id_cliente, rol) values ('12049', 'Cliente normal');
insert into rol (id_cliente, rol) values ('11080', 'Academico');
insert into rol (id_cliente, rol) values ('49939', 'Alumno');
insert into rol (id_cliente, rol) values ('72893', 'Trabajador');
insert into rol (id_cliente, rol) values ('71580', 'Academico');
insert into rol (id_cliente, rol) values ('99783', 'Cliente normal');
insert into rol (id_cliente, rol) values ('42116', 'Trabajador');
insert into rol (id_cliente, rol) values ('61804', 'Alumno');
insert into rol (id_cliente, rol) values ('90429', 'Academico');
insert into rol (id_cliente, rol) values ('43610', 'Cliente normal');
insert into rol (id_cliente, rol) values ('01391', 'Trabajador');
insert into rol (id_cliente, rol) values ('74636', 'Cliente normal');
insert into rol (id_cliente, rol) values ('00633', 'Trabajador');
insert into rol (id_cliente, rol) values ('09728', 'Trabajador');
insert into rol (id_cliente, rol) values ('64345', 'Academico');
insert into rol (id_cliente, rol) values ('30238', 'Cliente normal');
insert into rol (id_cliente, rol) values ('83906', 'Cliente normal');
insert into rol (id_cliente, rol) values ('53257', 'Cliente normal');
insert into rol (id_cliente, rol) values ('07325', 'Academico');
insert into rol (id_cliente, rol) values ('65643', 'Academico');
insert into rol (id_cliente, rol) values ('04751', 'Academico');
insert into rol (id_cliente, rol) values ('78115', 'Cliente normal');
insert into rol (id_cliente, rol) values ('72674', 'Cliente normal');
insert into rol (id_cliente, rol) values ('50348', 'Cliente normal');
insert into rol (id_cliente, rol) values ('63330', 'Trabajador');
insert into rol (id_cliente, rol) values ('01652', 'Cliente normal');
insert into rol (id_cliente, rol) values ('26999', 'Academico');
insert into rol (id_cliente, rol) values ('47925', 'Cliente normal');
insert into rol (id_cliente, rol) values ('66104', 'Academico');
insert into rol (id_cliente, rol) values ('94455', 'Cliente normal');
insert into rol (id_cliente, rol) values ('87242', 'Cliente normal');
insert into rol (id_cliente, rol) values ('70189', 'Trabajador');
insert into rol (id_cliente, rol) values ('34450', 'Alumno');
insert into rol (id_cliente, rol) values ('04342', 'Cliente normal');
insert into rol (id_cliente, rol) values ('49039', 'Trabajador');
insert into rol (id_cliente, rol) values ('71495', 'Cliente normal');
insert into rol (id_cliente, rol) values ('48172', 'Trabajador');
insert into rol (id_cliente, rol) values ('84033', 'Cliente normal');
insert into rol (id_cliente, rol) values ('93541', 'Trabajador');
insert into rol (id_cliente, rol) values ('19401', 'Trabajador');
insert into rol (id_cliente, rol) values ('94468', 'Cliente normal');
insert into rol (id_cliente, rol) values ('41486', 'Cliente normal');
insert into rol (id_cliente, rol) values ('29193', 'Trabajador');
insert into rol (id_cliente, rol) values ('25702', 'Trabajador');
insert into rol (id_cliente, rol) values ('71980', 'Cliente normal');
insert into rol (id_cliente, rol) values ('35772', 'Trabajador');
insert into rol (id_cliente, rol) values ('94638', 'Alumno');
insert into rol (id_cliente, rol) values ('98540', 'Cliente normal');
insert into rol (id_cliente, rol) values ('62579', 'Cliente normal');
insert into rol (id_cliente, rol) values ('64197', 'Academico');
insert into rol (id_cliente, rol) values ('19685', 'Cliente normal');
insert into rol (id_cliente, rol) values ('36349', 'Alumno');
insert into rol (id_cliente, rol) values ('66934', 'Cliente normal');
insert into rol (id_cliente, rol) values ('53184', 'Cliente normal');
insert into rol (id_cliente, rol) values ('24955', 'Cliente normal');
insert into rol (id_cliente, rol) values ('53572', 'Cliente normal');
insert into rol (id_cliente, rol) values ('56041', 'Cliente normal');
insert into rol (id_cliente, rol) values ('34209', 'Trabajador');
insert into rol (id_cliente, rol) values ('73783', 'Cliente normal');
insert into rol (id_cliente, rol) values ('89898', 'Academico');
insert into rol (id_cliente, rol) values ('31644', 'Cliente normal');
insert into rol (id_cliente, rol) values ('09362', 'Cliente normal');
insert into rol (id_cliente, rol) values ('34271', 'Trabajador');
insert into rol (id_cliente, rol) values ('84423', 'Cliente normal');
insert into rol (id_cliente, rol) values ('06077', 'Cliente normal');
insert into rol (id_cliente, rol) values ('70725', 'Cliente normal');
insert into rol (id_cliente, rol) values ('54640', 'Trabajador');
insert into rol (id_cliente, rol) values ('37694', 'Academico');
insert into rol (id_cliente, rol) values ('55018', 'Trabajador');
insert into rol (id_cliente, rol) values ('09721', 'Cliente normal');
insert into rol (id_cliente, rol) values ('50602', 'Cliente normal');
insert into rol (id_cliente, rol) values ('30496', 'Alumno');
insert into rol (id_cliente, rol) values ('31917', 'Trabajador');
insert into rol (id_cliente, rol) values ('36540', 'Alumno');
insert into rol (id_cliente, rol) values ('42063', 'Trabajador');
insert into rol (id_cliente, rol) values ('16130', 'Alumno');
insert into rol (id_cliente, rol) values ('51610', 'Trabajador');
insert into rol (id_cliente, rol) values ('43070', 'Alumno');
insert into rol (id_cliente, rol) values ('09251', 'Cliente normal');
insert into rol (id_cliente, rol) values ('95705', 'Cliente normal');
insert into rol (id_cliente, rol) values ('36947', 'Trabajador');
insert into rol (id_cliente, rol) values ('65429', 'Trabajador');
insert into rol (id_cliente, rol) values ('94485', 'Trabajador');
insert into rol (id_cliente, rol) values ('32392', 'Cliente normal');
insert into rol (id_cliente, rol) values ('03962', 'Academico');
insert into rol (id_cliente, rol) values ('92052', 'Trabajador');
insert into rol (id_cliente, rol) values ('62451', 'Trabajador');
insert into rol (id_cliente, rol) values ('95557', 'Cliente normal');
insert into rol (id_cliente, rol) values ('69154', 'Alumno');
insert into rol (id_cliente, rol) values ('68276', 'Cliente normal');
insert into rol (id_cliente, rol) values ('92993', 'Academico');
insert into rol (id_cliente, rol) values ('29552', 'Academico');
insert into rol (id_cliente, rol) values ('86296', 'Cliente normal');
insert into rol (id_cliente, rol) values ('63238', 'Trabajador');
insert into rol (id_cliente, rol) values ('91003', 'Cliente normal');
insert into rol (id_cliente, rol) values ('52489', 'Cliente normal');
insert into rol (id_cliente, rol) values ('95526', 'Alumno');
insert into rol (id_cliente, rol) values ('56118', 'Cliente normal');
insert into rol (id_cliente, rol) values ('88781', 'Cliente normal');
insert into rol (id_cliente, rol) values ('35061', 'Academico');
insert into rol (id_cliente, rol) values ('65005', 'Academico');
insert into rol (id_cliente, rol) values ('26563', 'Cliente normal');
insert into rol (id_cliente, rol) values ('45234', 'Cliente normal');
insert into rol (id_cliente, rol) values ('17130', 'Cliente normal');
insert into rol (id_cliente, rol) values ('88866', 'Alumno');
insert into rol (id_cliente, rol) values ('40337', 'Academico');
insert into rol (id_cliente, rol) values ('62636', 'Trabajador');
insert into rol (id_cliente, rol) values ('90132', 'Alumno');
insert into rol (id_cliente, rol) values ('29073', 'Cliente normal');
insert into rol (id_cliente, rol) values ('92918', 'Trabajador');
insert into rol (id_cliente, rol) values ('63625', 'Trabajador');
insert into rol (id_cliente, rol) values ('52078', 'Academico');
insert into rol (id_cliente, rol) values ('31001', 'Cliente normal');
insert into rol (id_cliente, rol) values ('26236', 'Cliente normal');
insert into rol (id_cliente, rol) values ('32551', 'Trabajador');
insert into rol (id_cliente, rol) values ('20673', 'Cliente normal');
insert into rol (id_cliente, rol) values ('39694', 'Alumno');
insert into rol (id_cliente, rol) values ('81898', 'Cliente normal');
insert into rol (id_cliente, rol) values ('45589', 'Cliente normal');
insert into rol (id_cliente, rol) values ('46934', 'Cliente normal');
